//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVO_FIJO_TABLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACTIVO_FIJO_TABLA()
        {
            this.AGRUPACION_ACT_FIJO = new HashSet<AGRUPACION_ACT_FIJO>();
            this.HISTORIAL_DEPREC_DT = new HashSet<HISTORIAL_DEPREC_DT>();
            this.MOVIMIENTO_ACTIVO = new HashSet<MOVIMIENTO_ACTIVO>();
        }
    
        public string CODIGO_ACTIVO_FIJO { get; set; }
        public int ENSAMBLE_ACTIVO_FIJO { get; set; }
        public string NOMBRE_DEL_ACTIVO_FIJO { get; set; }
        public string DESCRIPCION_DEL_ACTIVO_FI { get; set; }
        public string TIPO_DE_ACTIVO_FIJO { get; set; }
        public string SUBTIPO_DE_ACTIVO_FIJO { get; set; }
        public string SUBSUBTIPO_DE_ACTIVO_FIJO { get; set; }
        public Nullable<System.DateTime> FECHA_COMPRA_DEL_ACTIVO_F { get; set; }
        public string MONEDA_ORIGEN_CODIGO_DE_M { get; set; }
        public Nullable<decimal> VALOR_COMPRA_MONEDA_ORIGE { get; set; }
        public Nullable<decimal> VALOR_COMPRA_MONEDA_FINAN { get; set; }
        public Nullable<decimal> VALOR_COMPRA_MONEDA_REEXP { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_DEPRECIACION { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMA_DEPRECIACION { get; set; }
        public string METODO_DE_DEPRECIACION { get; set; }
        public Nullable<decimal> DEPREC_ACUM_MONEDA_ORIGEN { get; set; }
        public Nullable<decimal> DEPREC_ACUM_MONEDA_FINANC { get; set; }
        public Nullable<decimal> DEPREC_ACUM_MONEDA_REEXPR { get; set; }
        public Nullable<int> VIDA_UTIL_MESES_ACTIVO_FI { get; set; }
        public string ESTATUS_ACTIVO_FIJO { get; set; }
        public string TIPO_DE_PROPIEDAD { get; set; }
        public string SERIE_DEL_ACTIVO_FIJO { get; set; }
        public string DOCUMENTO_ORIGINAL_ACTIVO { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string PROVEEDOR_DEL_ACTIVO_CODI { get; set; }
        public string RESPONSABLE_CODIGO_BIC { get; set; }
        public string ZONA { get; set; }
        public Nullable<int> CODIGO_DE_AGENCIA { get; set; }
        public string CODIGO_DE_DEPARTAMENTO { get; set; }
        public string SUBDEPARTAMENTO { get; set; }
        public string CLIENTE_CODIGO_BIC { get; set; }
        public string GRUPOACT { get; set; }
    
        public virtual TIPO_ACTIVO_FIJO TIPO_ACTIVO_FIJO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGRUPACION_ACT_FIJO> AGRUPACION_ACT_FIJO { get; set; }
        public virtual DATOS_ADICIONALES_AF DATOS_ADICIONALES_AF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_DEPREC_DT> HISTORIAL_DEPREC_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMIENTO_ACTIVO> MOVIMIENTO_ACTIVO { get; set; }
    }
}
