//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACUMULADOS_PLANILLA
    {
        public string CODIGO_BIC { get; set; }
        public string TIPO_ACUMULADO_PLANILLA { get; set; }
        public string CODIGO_CLASE_DE_PLANILLA { get; set; }
        public int ANO_DE_PLANILLA { get; set; }
        public int MES_DE_PLANILLA { get; set; }
        public Nullable<decimal> VALOR_ACUMULADO_PLANILLA { get; set; }
        public Nullable<decimal> UNIDADES_ACUMULADO_PLANIL { get; set; }
        public Nullable<decimal> DIAS_ACUMULADO_PLANILLA { get; set; }
        public Nullable<decimal> HORAS_ACUMULADO_PLANILLA { get; set; }
    
        public virtual EMPLEADO_TABLA EMPLEADO_TABLA { get; set; }
        public virtual CLASE_DE_PLANILLA CLASE_DE_PLANILLA { get; set; }
        public virtual TIPO_ACUMULADOS TIPO_ACUMULADOS { get; set; }
    }
}
