//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENCIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGENCIA()
        {
            this.CUENTAS_INVENTARIO = new HashSet<CUENTAS_INVENTARIO>();
            this.FACTURA_AGENTE_ADUANERO_CTL = new HashSet<FACTURA_AGENTE_ADUANERO_CTL>();
            this.NOTAS_DBT_CRD_AGENTE_ADUANA = new HashSet<NOTAS_DBT_CRD_AGENTE_ADUANA>();
            this.PUNTO_DE_VENTA = new HashSet<PUNTO_DE_VENTA>();
            this.TRN_INVENTARIO_X_AGENCIT = new HashSet<TRN_INVENTARIO_X_AGENCIT>();
        }
    
        public int CODIGO_DE_AGENCIA { get; set; }
        public string NOMBRE_DE_AGENCIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUENTAS_INVENTARIO> CUENTAS_INVENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_AGENTE_ADUANERO_CTL> FACTURA_AGENTE_ADUANERO_CTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTAS_DBT_CRD_AGENTE_ADUANA> NOTAS_DBT_CRD_AGENTE_ADUANA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUNTO_DE_VENTA> PUNTO_DE_VENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_INVENTARIO_X_AGENCIT> TRN_INVENTARIO_X_AGENCIT { get; set; }
    }
}
