//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGRUPACION_CLIENTE_CTL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGRUPACION_CLIENTE_CTL()
        {
            this.AGRUPACION_CLIENTE_DET = new HashSet<AGRUPACION_CLIENTE_DET>();
            this.CLIENTE_AGRUPACION = new HashSet<CLIENTE_AGRUPACION>();
        }
    
        public string AGRUPACION_CLIENTE_CONTRO { get; set; }
        public string DESCRIPCION_AGRUP_CLIENTE { get; set; }
        public string ABREVIATURA_AGRUP_CLIENTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGRUPACION_CLIENTE_DET> AGRUPACION_CLIENTE_DET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_AGRUPACION> CLIENTE_AGRUPACION { get; set; }
    }
}
