//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGRUPACION_PROVEEDOR_DET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGRUPACION_PROVEEDOR_DET()
        {
            this.PROVEEDOR_AGRUPACION = new HashSet<PROVEEDOR_AGRUPACION>();
        }
    
        public string AGRUPACION_PROVEEDOR_CONT { get; set; }
        public string AGRUPACION_PROVEEDOR_DETA { get; set; }
        public string DESCRIPCION_AGRUP_PROV_DE { get; set; }
        public string ABREVIATURA_AGRUP_PROV_DE { get; set; }
    
        public virtual AGRUPACION_PROVEEDOR_CTL AGRUPACION_PROVEEDOR_CTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROVEEDOR_AGRUPACION> PROVEEDOR_AGRUPACION { get; set; }
    }
}
