//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGRUPACION_ACT_FIJO
    {
        public string CODIGO_ACTIVO_FIJO { get; set; }
        public int ENSAMBLE_ACTIVO_FIJO { get; set; }
        public string CODIGO_AGRUPACION_ACT_FIJ { get; set; }
        public string CODIGO_DETALLE_AGRUP_ACT { get; set; }
    
        public virtual ACTIVO_FIJO_TABLA ACTIVO_FIJO_TABLA { get; set; }
        public virtual AGRUPACION_ACTIVO_C AGRUPACION_ACTIVO_C { get; set; }
    }
}
