//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGRUP_EMPLEADO_DET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGRUP_EMPLEADO_DET()
        {
            this.EMPLEADO_AGRUP = new HashSet<EMPLEADO_AGRUP>();
        }
    
        public string CODIGO_AGRUPACION_EMPLEAD { get; set; }
        public string CODIGO_AGRUPACION_DE_EMPL { get; set; }
        public string NOMBRE_AGRUPACION_DE_EMPL { get; set; }
        public string ABREVIATURA_AGRUPACION_EM { get; set; }
    
        public virtual AGRUP_EMPLEADO_CTL AGRUP_EMPLEADO_CTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_AGRUP> EMPLEADO_AGRUP { get; set; }
    }
}
