//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGRUPACION_ACTIVO_C
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGRUPACION_ACTIVO_C()
        {
            this.AGRUPACION_ACT_FIJO = new HashSet<AGRUPACION_ACT_FIJO>();
            this.AGRUPACION_ACTIVO_D = new HashSet<AGRUPACION_ACTIVO_D>();
        }
    
        public string CODIGO_AGRUPACION_ACT_FIJ { get; set; }
        public string DESCRIPCION_AGRUPACION_AC { get; set; }
        public string ABREVIATURA_AGRUPACION_AC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGRUPACION_ACT_FIJO> AGRUPACION_ACT_FIJO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGRUPACION_ACTIVO_D> AGRUPACION_ACTIVO_D { get; set; }
    }
}
