//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class APERTURA_CIERRE_CAJERO
    {
        public string CODIGO_BIC { get; set; }
        public string CODIGO_ORIGEN_DEL_FONDO { get; set; }
        public System.DateTime FECHA_APERTURA_CAJERO { get; set; }
        public Nullable<System.DateTime> HORA_APERTURA_CAJERO { get; set; }
        public Nullable<System.DateTime> FECHA_CIERRE_CAJERO { get; set; }
        public Nullable<System.DateTime> HORA_CIERRE_CAJERO { get; set; }
        public string ESTA_ABIERTO_O_CERRADO_CA { get; set; }
    
        public virtual CAJERO_TABLA CAJERO_TABLA { get; set; }
        public virtual ORIGEN_DE_LOS_FONDOS ORIGEN_DE_LOS_FONDOS { get; set; }
    }
}
