//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULO_LOTE_SERIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICULO_LOTE_SERIE()
        {
            this.COMPLEMENTO_LOTES_DE_INVT = new HashSet<COMPLEMENTO_LOTES_DE_INVT>();
            this.COMPLEMENTO_LOTES_TRANSFT = new HashSet<COMPLEMENTO_LOTES_TRANSFT>();
        }
    
        public string CODIGO_DE_ARTICULO { get; set; }
        public int ANO_DE_INVENTARIO { get; set; }
        public string CODIGO_DE_BODEGA { get; set; }
        public string CODIGO_DE_EMPAQUE { get; set; }
        public string CODIGO_UNIDAD_DE_MEDIDA { get; set; }
        public string CODIGO_LOTE_SERIE { get; set; }
        public int LOTE { get; set; }
        public string ESTATUS_DEL_LOTE { get; set; }
        public Nullable<decimal> CANTIDAD_ORIGINAL_LOTE { get; set; }
        public Nullable<decimal> COSTO_ORIGINAL_LOTE { get; set; }
        public Nullable<decimal> SALDO_LOTE { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO_LOTE { get; set; }
        public Nullable<System.DateTime> FECHA_VENCE_LOTE { get; set; }
        public Nullable<decimal> CANTIDAD_ENTREGADA_LOTE { get; set; }
    
        public virtual SALDO_DE_ARTICULO SALDO_DE_ARTICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPLEMENTO_LOTES_DE_INVT> COMPLEMENTO_LOTES_DE_INVT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPLEMENTO_LOTES_TRANSFT> COMPLEMENTO_LOTES_TRANSFT { get; set; }
    }
}
