//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULO_DESC_ADIC
    {
        public string CODIGO_DE_ARTICULO { get; set; }
        public string DESCRIPCION_ADICIONAL_ART { get; set; }
    
        public virtual ARTICULO_TABLA ARTICULO_TABLA { get; set; }
    }
}
