//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATENCIONES_MEDICAS_DETALLE
    {
        public string CODIGO_BIC { get; set; }
        public System.DateTime FECHA_DE_ATENCION { get; set; }
        public string DOMICILIO_O_ALDEA { get; set; }
        public int EXPEDIENTE { get; set; }
        public string TIPO_CONSULTA_CITA { get; set; }
        public string EDAD_DEL_PACIENTE_CITA { get; set; }
        public string PACIENTE_CITA { get; set; }
        public string DETECCION_CITA { get; set; }
        public string MOTIVO_CONSULTA_EMBARAZO { get; set; }
        public string MOTIVO_CONSULTA_PUERPERIO { get; set; }
        public string MOTIVOCONSULTAPLANFAMILIA { get; set; }
        public string MOTIVOCONSULTAPLANFAMI7L6 { get; set; }
        public string MOTIVO_CONSULTA_DIARREA { get; set; }
        public string MOTIVO_CONSULTA_IRA { get; set; }
        public string MOTIVOCONSULTACRECIMIENTO { get; set; }
        public string MOTIVOCONSULTACRECIMIE7LB { get; set; }
        public string MOTIVO_CONSULTA_DIAGNOSTI { get; set; }
        public string ENTERMEDAD { get; set; }
    
        public virtual ATENCIONES_MEDICAS_CONTROL ATENCIONES_MEDICAS_CONTROL { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
