//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANCO_TABLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANCO_TABLA()
        {
            this.CUENTA_DE_BANCO = new HashSet<CUENTA_DE_BANCO>();
            this.TARJETAS_DE_CREDITO = new HashSet<TARJETAS_DE_CREDITO>();
        }
    
        public string CODIGO_BIC { get; set; }
        public string OFICIAL_DE_CREDITO_ASIGNA { get; set; }
        public string ESTATUS_DEL_BANCO { get; set; }
    
        public virtual BASE_INFO_CENTRAL BASE_INFO_CENTRAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUENTA_DE_BANCO> CUENTA_DE_BANCO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARJETAS_DE_CREDITO> TARJETAS_DE_CREDITO { get; set; }
    }
}
