//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_INFO_CENTRAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BASE_INFO_CENTRAL()
        {
            this.PG_TRN_PRESUPUESTO_BENEFICIARIOS = new HashSet<PG_TRN_PRESUPUESTO_BENEFICIARIOS>();
            this.RUTAS_MENSAJERIA_DETALLT = new HashSet<RUTAS_MENSAJERIA_DETALLT>();
            this.SOLICITUD_PAGO_CTL = new HashSet<SOLICITUD_PAGO_CTL>();
        }
    
        public string CODIGO_BIC { get; set; }
        public string TIPO_BIC { get; set; }
        public string APELLIDO_BIC { get; set; }
        public string NOMBRE_BIC { get; set; }
        public string TELEFONO_BIC { get; set; }
        public string FAX_BIC { get; set; }
        public string CELULAR_BIC { get; set; }
        public string LOCALIZADOR_BIC { get; set; }
        public string DIRECCION_ELECTRONICA_BIC { get; set; }
        public string PAGINA_WEB_BIC { get; set; }
        public string METODO_COMUNICACION_BIC { get; set; }
        public string DIRECCION_BIC { get; set; }
        public string CIUDAD_BIC { get; set; }
        public string CODIGO_POSTAL_BIC { get; set; }
        public string CODIGO_DE_PAIS { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO_BIC { get; set; }
        public string DOCUMENTO_DE_IDENTIFICACI { get; set; }
        public string NOTAS_BIC { get; set; }
    
        public virtual BANCO_TABLA BANCO_TABLA { get; set; }
        public virtual PAIS_PHYSICAL_TABLE PAIS_PHYSICAL_TABLE { get; set; }
        public virtual CAJERO_TABLA CAJERO_TABLA { get; set; }
        public virtual CLIENTE_TABLA CLIENTE_TABLA { get; set; }
        public virtual COBRADOR_TABLA COBRADOR_TABLA { get; set; }
        public virtual EMPLEADO_TABLA EMPLEADO_TABLA { get; set; }
        public virtual INSTRUCTOR_PHYSICAL_TABLE INSTRUCTOR_PHYSICAL_TABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PG_TRN_PRESUPUESTO_BENEFICIARIOS> PG_TRN_PRESUPUESTO_BENEFICIARIOS { get; set; }
        public virtual PROVEEDOR_TABLA PROVEEDOR_TABLA { get; set; }
        public virtual PUNTO_DE_VENTA PUNTO_DE_VENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RUTAS_MENSAJERIA_DETALLT> RUTAS_MENSAJERIA_DETALLT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD_PAGO_CTL> SOLICITUD_PAGO_CTL { get; set; }
        public virtual TECNICO_TABLA TECNICO_TABLA { get; set; }
        public virtual VENDEDOR_TABLA VENDEDOR_TABLA { get; set; }
    }
}
