//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class BODEGA_TABLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BODEGA_TABLA()
        {
            this.ARTICULO_BODEGA_PRES = new HashSet<ARTICULO_BODEGA_PRES>();
            this.ARTICULO_PRESUPUESTO_TRIT = new HashSet<ARTICULO_PRESUPUESTO_TRIT>();
            this.BODEGA_TIPO_CUENTA_CONTAB = new HashSet<BODEGA_TIPO_CUENTA_CONTAB>();
            this.COMPRA_DETALLE = new HashSet<COMPRA_DETALLE>();
            this.COMPRA_TABLA = new HashSet<COMPRA_TABLA>();
            this.CUENTAS_INVENTARIO = new HashSet<CUENTAS_INVENTARIO>();
            this.FACTURA_DIARIA_CONTROL = new HashSet<FACTURA_DIARIA_CONTROL>();
            this.ORDEN_DE_TRABAJO_DETALLE = new HashSet<ORDEN_DE_TRABAJO_DETALLE>();
            this.PUNTO_DE_VENTA = new HashSet<PUNTO_DE_VENTA>();
            this.RECETA_MASIVA_MEDICAMENTT = new HashSet<RECETA_MASIVA_MEDICAMENTT>();
            this.RECETA_PLANTILLA_MEDICAMT = new HashSet<RECETA_PLANTILLA_MEDICAMT>();
            this.RECETAS_SIN_DESPACHAR = new HashSet<RECETAS_SIN_DESPACHAR>();
            this.REQUISICION_CONTROL = new HashSet<REQUISICION_CONTROL>();
            this.REQUISICION_DETALLE = new HashSet<REQUISICION_DETALLE>();
            this.TRANSFERENCIA_INVENTA3E4T = new HashSet<TRANSFERENCIA_INVENTA3E4T>();
            this.TRANSFERENCIA_INVENTA3E4T1 = new HashSet<TRANSFERENCIA_INVENTA3E4T>();
            this.TRANSFERENCIA_INVENTARIT = new HashSet<TRANSFERENCIA_INVENTARIT>();
            this.TRANSFERENCIA_INVENTARIT1 = new HashSet<TRANSFERENCIA_INVENTARIT>();
            this.TRN_INVENTARIO_HIST_DET = new HashSet<TRN_INVENTARIO_HIST_DET>();
        }
    
        public string CODIGO_DE_BODEGA { get; set; }
        public string NOMBRE_DE_BODEGA { get; set; }
        public string ABREVIATURA_DE_BODEGA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO_BODEGA_PRES> ARTICULO_BODEGA_PRES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO_PRESUPUESTO_TRIT> ARTICULO_PRESUPUESTO_TRIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BODEGA_TIPO_CUENTA_CONTAB> BODEGA_TIPO_CUENTA_CONTAB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA_DETALLE> COMPRA_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA_TABLA> COMPRA_TABLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUENTAS_INVENTARIO> CUENTAS_INVENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_DIARIA_CONTROL> FACTURA_DIARIA_CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_DE_TRABAJO_DETALLE> ORDEN_DE_TRABAJO_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUNTO_DE_VENTA> PUNTO_DE_VENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECETA_MASIVA_MEDICAMENTT> RECETA_MASIVA_MEDICAMENTT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECETA_PLANTILLA_MEDICAMT> RECETA_PLANTILLA_MEDICAMT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECETAS_SIN_DESPACHAR> RECETAS_SIN_DESPACHAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUISICION_CONTROL> REQUISICION_CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUISICION_DETALLE> REQUISICION_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSFERENCIA_INVENTA3E4T> TRANSFERENCIA_INVENTA3E4T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSFERENCIA_INVENTA3E4T> TRANSFERENCIA_INVENTA3E4T1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSFERENCIA_INVENTARIT> TRANSFERENCIA_INVENTARIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSFERENCIA_INVENTARIT> TRANSFERENCIA_INVENTARIT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_INVENTARIO_HIST_DET> TRN_INVENTARIO_HIST_DET { get; set; }
    }
}
