//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class BODEGA_TIPO_CUENTA_CONTAB
    {
        public string CODIGO_DE_BODEGA { get; set; }
        public string CODIGO_TIPO_INVENTARIO { get; set; }
        public string TIPO_DE_PARTIDA { get; set; }
        public string CODIGO_DE_CUENTA { get; set; }
    
        public virtual BODEGA_TABLA BODEGA_TABLA { get; set; }
        public virtual CATALOGO_DE_CUENTAS CATALOGO_DE_CUENTAS { get; set; }
    }
}
