//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJERO_TABLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAJERO_TABLA()
        {
            this.APERTURA_CIERRE_CAJERO = new HashSet<APERTURA_CIERRE_CAJERO>();
            this.ARQUEO_CAJERO_HOSPITAL_PT = new HashSet<ARQUEO_CAJERO_HOSPITAL_PT>();
            this.RECIBO_SERVICIOS_HOSPITAL_CTL = new HashSet<RECIBO_SERVICIOS_HOSPITAL_CTL>();
        }
    
        public string CODIGO_BIC { get; set; }
        public string ESTATUS_DEL_CAJERO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APERTURA_CIERRE_CAJERO> APERTURA_CIERRE_CAJERO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARQUEO_CAJERO_HOSPITAL_PT> ARQUEO_CAJERO_HOSPITAL_PT { get; set; }
        public virtual BASE_INFO_CENTRAL BASE_INFO_CENTRAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECIBO_SERVICIOS_HOSPITAL_CTL> RECIBO_SERVICIOS_HOSPITAL_CTL { get; set; }
    }
}
