//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALENDARIO_DETALLE_FECHAS
    {
        public string CALENDARIO { get; set; }
        public System.DateTime FECHA_CALENDARIO { get; set; }
        public string DESCRIPCION_CALENDARIO { get; set; }
        public string ESTATUS_CALENDARIO { get; set; }
    
        public virtual CALENDARIO_PHYSICAL_TABLE CALENDARIO_PHYSICAL_TABLE { get; set; }
    }
}
