//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUSAS_DE_BAJA
    {
        public string CODIGO_CAUSA_BAJA { get; set; }
        public string DESCRIPCION_CAUSA_BAJA { get; set; }
        public string ABREVIATURA_CAUSA_BAJA { get; set; }
    }
}
