//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTRO_DE_CAPACITACION_PT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CENTRO_DE_CAPACITACION_PT()
        {
            this.GRUPO_DE_CURSO = new HashSet<GRUPO_DE_CURSO>();
        }
    
        public string CODIGO_CENTRO_CAPACITACIO { get; set; }
        public string DESCRIPCION_CENTRO_CAPACI { get; set; }
        public string ABREVIATURA_CENTRO_CAPACI { get; set; }
        public string TIPO_CENTRO_CAPACITACION { get; set; }
        public string UBICACION_CENTRO_CAPACITA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRUPO_DE_CURSO> GRUPO_DE_CURSO { get; set; }
    }
}
