//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHEQUE_GENERADO_TABLA
    {
        public string CODIGO_BIC { get; set; }
        public string CUENTA_BANCARIA { get; set; }
        public string PREFIJO_PARTIDA_CONTABLE { get; set; }
        public int NUMERO_DE_CHEQUE { get; set; }
        public Nullable<decimal> VALOR_DEL_CHEQUE { get; set; }
        public string NOMBRE_DEL_BENEFICIARIO { get; set; }
        public Nullable<System.DateTime> FECHA_DEL_CHEQUE { get; set; }
        public string ESTATUS_DEL_CHEQUE { get; set; }
        public string ENTREGADO_A { get; set; }
        public string IDENTIFICACION_ENTREGADO { get; set; }
        public Nullable<System.DateTime> FECHA_DE_ENTREGA_DEL_CHEQ { get; set; }
        public string COMENTARIOS { get; set; }
        public string IMPRESO_POR { get; set; }
        public Nullable<System.DateTime> FECHA_DE_IMPRESION_CHEQUE { get; set; }
        public Nullable<System.DateTime> HORA_DE_IMPRESION_DEL_CHE { get; set; }
        public string ANULADO_POR { get; set; }
        public Nullable<System.DateTime> FECHA_DE_ANULACION_DEL_CH { get; set; }
        public Nullable<System.DateTime> HORA_DE_ANULACION_DEL_CHE { get; set; }
        public Nullable<int> NUMERO_SOLICITUD_PAGO { get; set; }
        public string LY3qeA { get; set; }
    }
}
