//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHEQUES_NO_CONCILIADOS
    {
        public string CODIGO_BIC { get; set; }
        public string CUENTA_BANCARIA { get; set; }
        public string CODIGO_DE_CHEQUE_NO_CONCI { get; set; }
        public Nullable<decimal> VALOR_DEL_CHEQUE_NO_CONCI { get; set; }
        public string LY4m8A { get; set; }
    
        public virtual CUENTA_DE_BANCO CUENTA_DE_BANCO { get; set; }
    }
}
