//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CICLO_DE_VACACIONES_PHYST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CICLO_DE_VACACIONES_PHYST()
        {
            this.SALDOS_DE_VACACIONES = new HashSet<SALDOS_DE_VACACIONES>();
        }
    
        public int ANO_DE_CICLO_DE_VACACIONE { get; set; }
        public int NUMERO_DE_CICLO_DE_VACACI { get; set; }
        public string DESCRIPCION_CICLO_VACACIO { get; set; }
        public Nullable<System.DateTime> FECHA_DE_INICIO_CICLO_VAC { get; set; }
        public Nullable<System.DateTime> FECHA_DE_FIN_CICLO_VACACI { get; set; }
        public Nullable<int> DIAS_HABILES_DE_VACACIONE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALDOS_DE_VACACIONES> SALDOS_DE_VACACIONES { get; set; }
    }
}
