//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CICLO_INVENTARIO_FISICO_T
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CICLO_INVENTARIO_FISICO_T()
        {
            this.INVENTARIO_FISICO = new HashSet<INVENTARIO_FISICO>();
        }
    
        public int ANO_CICLO_INVENTARIO_FISI { get; set; }
        public int NUMERO_CICLO_INVENTARIO_F { get; set; }
        public string DESCRIPCION_CICLO_INVENT { get; set; }
        public Nullable<System.DateTime> FECHA_CICLO_INVENT_FISICO { get; set; }
        public Nullable<int> ANO_DEL_PERIODO { get; set; }
        public Nullable<int> NUMERO_DEL_PERIODO { get; set; }
        public string CODIGO_BIC { get; set; }
    
        public virtual EMPLEADO_TABLA EMPLEADO_TABLA { get; set; }
        public virtual PERIODO_CONTABLE PERIODO_CONTABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTARIO_FISICO> INVENTARIO_FISICO { get; set; }
    }
}
