//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITAS_MEDICAS_DETALLE_PHT
    {
        public System.DateTime LH7m6A { get; set; }
        public decimal CORRELATIVO_DE_LA_CITA { get; set; }
        public string CODIGO_BIC { get; set; }
        public Nullable<int> EXPEDIENTE { get; set; }
        public string TIPO_DE_CITA { get; set; }
        public string VIENE_A_CITA { get; set; }
        public string SE_PRESENTO_A_CITA { get; set; }
        public Nullable<decimal> NUMERO_ORDEN_CITA { get; set; }
        public Nullable<System.DateTime> HORA_ADICION { get; set; }
        public Nullable<System.DateTime> FECHA_ADICION { get; set; }
        public string USUARIO_ADICION { get; set; }
        public Nullable<System.DateTime> HORA_ULTIMO_CAMBIO { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_CAMBIO { get; set; }
        public string USUARIO_ULTIMO_CAMBIO { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
