//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASE_DE_PLANILLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLASE_DE_PLANILLA()
        {
            this.ACUMULADOS_PLANILLA = new HashSet<ACUMULADOS_PLANILLA>();
            this.DEF_TRN_PLA_CTL = new HashSet<DEF_TRN_PLA_CTL>();
            this.EMPLEADO_TABLA = new HashSet<EMPLEADO_TABLA>();
            this.EMPLEADO_TRN_FIJAS_PHYSIT = new HashSet<EMPLEADO_TRN_FIJAS_PHYSIT>();
            this.FICHA_DE_GRABACION_NOMINT = new HashSet<FICHA_DE_GRABACION_NOMINT>();
            this.PERIODO_DE_PLANILLA = new HashSet<PERIODO_DE_PLANILLA>();
            this.TIPO_DE_PLANILLA = new HashSet<TIPO_DE_PLANILLA>();
            this.TRANSAC_PLA_CTL = new HashSet<TRANSAC_PLA_CTL>();
        }
    
        public string CODIGO_CLASE_DE_PLANILLA { get; set; }
        public string DESCRIPCION_CLASE_DE_PLAN { get; set; }
        public string ABREVIATURA_CLASE_DE_PLAN { get; set; }
        public string NOMBRE_VARIABLE_CLASE_01 { get; set; }
        public string NOMBRE_VARIABLE_CLASE_02 { get; set; }
        public string NOMBRE_VARIABLE_CLASE_03 { get; set; }
        public string NOMBRE_VARIABLE_CLASE_04 { get; set; }
        public string NOMBRE_VARIABLE_CLASE_05 { get; set; }
        public Nullable<decimal> VALOR_VARIABLE_CLASE_P01 { get; set; }
        public Nullable<decimal> VALOR_VARIABLE_CLASE_P02 { get; set; }
        public Nullable<decimal> VALOR_VARIABLE_CLASE_P03 { get; set; }
        public Nullable<decimal> VALOR_VARIABLE_CLASE_P04 { get; set; }
        public Nullable<decimal> VALOR_VARIABLE_CLASE_P05 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACUMULADOS_PLANILLA> ACUMULADOS_PLANILLA { get; set; }
        public virtual CLASE_PLANILLA_ESTRUCTURA CLASE_PLANILLA_ESTRUCTURA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEF_TRN_PLA_CTL> DEF_TRN_PLA_CTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_TABLA> EMPLEADO_TABLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_TRN_FIJAS_PHYSIT> EMPLEADO_TRN_FIJAS_PHYSIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FICHA_DE_GRABACION_NOMINT> FICHA_DE_GRABACION_NOMINT { get; set; }
        public virtual FICHA_DE_GRABACION_RECOLT FICHA_DE_GRABACION_RECOLT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERIODO_DE_PLANILLA> PERIODO_DE_PLANILLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_DE_PLANILLA> TIPO_DE_PLANILLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSAC_PLA_CTL> TRANSAC_PLA_CTL { get; set; }
    }
}
