//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_AGRUPACION
    {
        public string CODIGO_BIC { get; set; }
        public string AGRUPACION_CLIENTE_CONTRO { get; set; }
        public string AGRUPACION_DE_CLIENTE_DET { get; set; }
    
        public virtual AGRUPACION_CLIENTE_CTL AGRUPACION_CLIENTE_CTL { get; set; }
        public virtual AGRUPACION_CLIENTE_DET AGRUPACION_CLIENTE_DET { get; set; }
        public virtual CLIENTE_TABLA CLIENTE_TABLA { get; set; }
    }
}
