//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_TABLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE_TABLA()
        {
            this.CLIENTE_AGRUPACION = new HashSet<CLIENTE_AGRUPACION>();
            this.CLIENTE_DESCUENTO = new HashSet<CLIENTE_DESCUENTO>();
            this.FACTURA_AGENTE_ADUANERO_CTL = new HashSet<FACTURA_AGENTE_ADUANERO_CTL>();
            this.FACTURA_DIARIA_CONTROL = new HashSet<FACTURA_DIARIA_CONTROL>();
            this.FACTURAS_SERVICIOS_CONTROL = new HashSet<FACTURAS_SERVICIOS_CONTROL>();
            this.NOTAS_DBT_CRD_AGENTE_ADUANA = new HashSet<NOTAS_DBT_CRD_AGENTE_ADUANA>();
            this.ORDEN_DE_TRABAJO_CONTROL = new HashSet<ORDEN_DE_TRABAJO_CONTROL>();
            this.SALDO_DE_CLIENTE_PHYSICAT = new HashSet<SALDO_DE_CLIENTE_PHYSICAT>();
            this.TRN_CLIENTE_DIARIO_DET = new HashSet<TRN_CLIENTE_DIARIO_DET>();
            this.TRN_CLIENTE_HIST_DETALLT = new HashSet<TRN_CLIENTE_HIST_DETALLT>();
        }
    
        public string CODIGO_BIC { get; set; }
        public string CODIGO_TIPO_DE_CLIENTE { get; set; }
        public string CODIGO_CONDICION_COBRO { get; set; }
        public string CODIGO_DE_CUENTA { get; set; }
    
        public virtual BASE_INFO_CENTRAL BASE_INFO_CENTRAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_AGRUPACION> CLIENTE_AGRUPACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_DESCUENTO> CLIENTE_DESCUENTO { get; set; }
        public virtual TIPO_CLIENTE TIPO_CLIENTE { get; set; }
        public virtual CONDICIONES_COBRO CONDICIONES_COBRO { get; set; }
        public virtual CONTRATO_SERVICIOS_CONTROL CONTRATO_SERVICIOS_CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_AGENTE_ADUANERO_CTL> FACTURA_AGENTE_ADUANERO_CTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_DIARIA_CONTROL> FACTURA_DIARIA_CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURAS_SERVICIOS_CONTROL> FACTURAS_SERVICIOS_CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTAS_DBT_CRD_AGENTE_ADUANA> NOTAS_DBT_CRD_AGENTE_ADUANA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_DE_TRABAJO_CONTROL> ORDEN_DE_TRABAJO_CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALDO_DE_CLIENTE_PHYSICAT> SALDO_DE_CLIENTE_PHYSICAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_CLIENTE_DIARIO_DET> TRN_CLIENTE_DIARIO_DET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_CLIENTE_HIST_DETALLT> TRN_CLIENTE_HIST_DETALLT { get; set; }
    }
}
