//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA_TABLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPRA_TABLA()
        {
            this.COMPRA_DETALLE = new HashSet<COMPRA_DETALLE>();
        }
    
        public int NUMERO_DE_COMPRA { get; set; }
        public string CODIGO_DE_BODEGA { get; set; }
        public string CODIGO_BIC { get; set; }
        public string RECIBIDO_POR_CODIGO_BIC { get; set; }
        public string DOCUMENTO_ORIGEN_PROVEEDO { get; set; }
        public Nullable<System.DateTime> FECHA_DE_COMPRA { get; set; }
        public Nullable<int> ANO_DEL_PERIODO { get; set; }
        public Nullable<int> NUMERO_DEL_PERIODO { get; set; }
        public string CODIGO_DE_MONEDA { get; set; }
        public Nullable<decimal> TOTAL_COMPRA_MONEDA_ORIGE { get; set; }
        public Nullable<decimal> TOTAL_IMPUESTO_MONEDA_ORI { get; set; }
        public string ESTATUS_DE_LA_COMPRA { get; set; }
        public Nullable<int> NUMERO_ORDEN_DE_COMPRA { get; set; }
        public string NUMERO_DE_LICITACION { get; set; }
        public string NUMERO_DE_ACTA { get; set; }
        public string NUMERO_DE_CONTRATO { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual BODEGA_TABLA BODEGA_TABLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA_DETALLE> COMPRA_DETALLE { get; set; }
        public virtual MONEDA_TABLA MONEDA_TABLA { get; set; }
        public virtual EMPLEADO_TABLA EMPLEADO_TABLA { get; set; }
        public virtual PERIODO_CONTABLE PERIODO_CONTABLE { get; set; }
    }
}
