//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPANIA()
        {
            this.CATALOGO_CONTABLE_CONSOLIDADO = new HashSet<CATALOGO_CONTABLE_CONSOLIDADO>();
            this.COMPAÑIA_MODULO = new HashSet<COMPAÑIA_MODULO>();
            this.OS12T = new HashSet<OS12T>();
        }
    
        public string CODIGO_DE_COMPANIA { get; set; }
        public string NOMBRE_LARGO_DE_COMPANIA { get; set; }
        public string NOMBRE_CORTO_DE_COMPANIA { get; set; }
        public string ESTATUS_DE_COMPANIA { get; set; }
        public string NIVEL_1_NOMBRE { get; set; }
        public Nullable<int> NIVEL_1_INICIO { get; set; }
        public Nullable<int> NIVEL_1_LONGITUD { get; set; }
        public string NIVEL_1_SIGNO { get; set; }
        public string NIVEL_2_NOMBRE { get; set; }
        public Nullable<int> NIVEL_2_INICIO { get; set; }
        public Nullable<int> NIVEL_2_LONGITUD { get; set; }
        public string NIVEL_2_SIGNO { get; set; }
        public string NIVEL_3_NOMBRE { get; set; }
        public Nullable<int> NIVEL_3_INICIO { get; set; }
        public Nullable<int> NIVEL_3_LONGITUD { get; set; }
        public string NIVEL_3_SIGNO { get; set; }
        public string NIVEL_4_NOMBRE { get; set; }
        public Nullable<int> NIVEL_4_INICIO { get; set; }
        public Nullable<int> NIVEL_4_LONGITUD { get; set; }
        public string NIVEL_4_SIGNO { get; set; }
        public string NIVEL_5_NOMBRE { get; set; }
        public Nullable<int> NIVEL_5_INICIO { get; set; }
        public Nullable<int> NIVEL_5_LONGITUD { get; set; }
        public string NIVEL_5_SIGNO { get; set; }
        public string NIVEL_6_NOMBRE { get; set; }
        public Nullable<int> NIVEL_6_INICIO { get; set; }
        public Nullable<int> NIVEL_6_LONGITUD { get; set; }
        public string NIVEL_6_SIGNO { get; set; }
        public Nullable<int> NIVEL_7_INICIO { get; set; }
        public string NIVEL_7_NOMBRE { get; set; }
        public Nullable<int> NIVEL_7_LONGITUD { get; set; }
        public string NIVEL_7_SIGNO { get; set; }
        public string NIVEL_8_NOMBRE { get; set; }
        public Nullable<int> NIVEL_8_INICIO { get; set; }
        public Nullable<int> NIVEL_8_LONGITUD { get; set; }
        public string NIVEL_8_SIGNO { get; set; }
        public string NIVEL_9_NOMBRE { get; set; }
        public Nullable<int> NIVEL_9_INICIO { get; set; }
        public Nullable<int> NIVEL_9_LONGITUD { get; set; }
        public string CODIGO_DE_MONEDA { get; set; }
        public string CODIGO_MONEDA_REEXPRESION { get; set; }
        public string AMBIENTE { get; set; }
        public string BASE_DE_DATOS_DE_COMPANIA { get; set; }
        public string NOMBRE_DEL_SERVIDOR { get; set; }
        public string DIRECTORIO_DE_FOTOS { get; set; }
        public string DIRECTORIO_DE_FOTOS_ACTIV { get; set; }
        public string DIRECTORIO_DE_FOTOS_INVEN { get; set; }
        public string NOMBRE_DEL_GERENTE { get; set; }
        public string DIRECCION_DE_LA_COMPANIA { get; set; }
        public string TELEFONO_DE_LA_COMPANIA { get; set; }
        public string FAX_DE_LA_COMPANIA { get; set; }
        public string CORREO_ELECTRONICO_COMPAN { get; set; }
        public string PAGINA_WEB { get; set; }
        public string GIRO_DE_LA_COMPANIA { get; set; }
        public string REGISTRO_FISCAL { get; set; }
        public string DOCUMENTO_1_COMPANIA { get; set; }
        public string NUMERO_1_COMPANIA { get; set; }
        public string DOCUMENTO_2_COMPANIA { get; set; }
        public string NUMERO_2_COMPANIA { get; set; }
        public string DOCUMENTO_3_COMPANIA { get; set; }
        public string NUMERO_3_COMPANIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATALOGO_CONTABLE_CONSOLIDADO> CATALOGO_CONTABLE_CONSOLIDADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPAÑIA_MODULO> COMPAÑIA_MODULO { get; set; }
        public virtual COMPAÑIA_NOMBRE_CONTABLES COMPAÑIA_NOMBRE_CONTABLES { get; set; }
        public virtual VALORES_DEL_SISTEMA_POR_DEFAULT VALORES_DEL_SISTEMA_POR_DEFAULT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OS12T> OS12T { get; set; }
    }
}
