//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPAÑIA_NOMBRE_CONTABLES
    {
        public string CODIGO_DE_COMPANIA { get; set; }
        public string NOMBRE_DEL_SUBCATALOGO_1 { get; set; }
        public string NOMBRE_DEL_SUBCATALOGO_2 { get; set; }
        public string NOMBRE_DEL_SUBCATALOGO_3 { get; set; }
    
        public virtual COMPANIA COMPANIA { get; set; }
    }
}
