//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONCILIACION_BANCARIA_CTL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONCILIACION_BANCARIA_CTL()
        {
            this.CONCILIACION_BANCARIA_DET = new HashSet<CONCILIACION_BANCARIA_DET>();
        }
    
        public string CODIGO_BIC { get; set; }
        public string CUENTA_BANCARIA { get; set; }
        public int ANO_DEL_PERIODO { get; set; }
        public int NUMERO_DEL_PERIODO { get; set; }
        public string ESTADO_CONCILIACION { get; set; }
    
        public virtual CUENTA_DE_BANCO CUENTA_DE_BANCO { get; set; }
        public virtual PERIODO_CONTABLE PERIODO_CONTABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONCILIACION_BANCARIA_DET> CONCILIACION_BANCARIA_DET { get; set; }
        public virtual CONCILIACION_BANCARIA_RES CONCILIACION_BANCARIA_RES { get; set; }
    }
}
