//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONCILIACION_BANCARIA_RES
    {
        public string CODIGO_BIC { get; set; }
        public string CUENTA_BANCARIA { get; set; }
        public int ANO_DEL_PERIODO { get; set; }
        public int NUMERO_DEL_PERIODO { get; set; }
        public string LH6x1A { get; set; }
        public Nullable<decimal> LH6x2A { get; set; }
        public Nullable<decimal> LH6x3A { get; set; }
        public Nullable<decimal> LH6x4A { get; set; }
        public Nullable<decimal> LH6x5A { get; set; }
    
        public virtual CONCILIACION_BANCARIA_CTL CONCILIACION_BANCARIA_CTL { get; set; }
    }
}
