//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDICIONES_PAGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONDICIONES_PAGO()
        {
            this.PROVEEDOR_TABLA = new HashSet<PROVEEDOR_TABLA>();
        }
    
        public string CONDICION_DE_PAGO { get; set; }
        public string DESCRIPCION_CONDICION_DE { get; set; }
        public string ABREVIATURA_CONDICION_DE { get; set; }
        public Nullable<int> DIAS_CONDICION_DE_PAGO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROVEEDOR_TABLA> PROVEEDOR_TABLA { get; set; }
    }
}
