//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDICIONES_COBRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONDICIONES_COBRO()
        {
            this.CLIENTE_TABLA = new HashSet<CLIENTE_TABLA>();
        }
    
        public string CODIGO_CONDICION_COBRO { get; set; }
        public string DESCRIPCION_CONDICION_COB { get; set; }
        public string ABREVIATURA_CONDICION_COB { get; set; }
        public Nullable<int> DIAS_CONDICION_COBRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_TABLA> CLIENTE_TABLA { get; set; }
    }
}
