//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO_SERVICIOS_NEG_ESP
    {
        public string CLIENTE_CODIGO_BIC { get; set; }
        public decimal LINEA_NEGOCIACION_ESPECIA { get; set; }
        public Nullable<int> ANO_DEL_PERIODO { get; set; }
        public Nullable<int> NUMERO_DEL_PERIODO { get; set; }
        public Nullable<decimal> PORCENTAJE_NEGOCIADO { get; set; }
        public string CODIGO_DE_SERVICIO { get; set; }
        public string CODIGO_TIPO_SERVICIO { get; set; }
        public string CODIGO_DETALLE_SERVICIO { get; set; }
        public string DESCRIPCION_DEL_SERVICIO { get; set; }
        public Nullable<decimal> VALOR_DEL_SERVICIO { get; set; }
    
        public virtual CONTRATO_SERVICIOS_CONTROL CONTRATO_SERVICIOS_CONTROL { get; set; }
        public virtual SERVICIOS_PHYSICAL_TABLE SERVICIOS_PHYSICAL_TABLE { get; set; }
        public virtual PERIODO_CONTABLE PERIODO_CONTABLE { get; set; }
        public virtual TIPOS_DE_SERVICIOS_PHYSIT TIPOS_DE_SERVICIOS_PHYSIT { get; set; }
        public virtual DETALLE_DEL_SERVICIO_PHYT DETALLE_DEL_SERVICIO_PHYT { get; set; }
    }
}
