//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO_SERVICIOS_CONTROL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTRATO_SERVICIOS_CONTROL()
        {
            this.CONTRATO_SERVICIOS_DETALLE = new HashSet<CONTRATO_SERVICIOS_DETALLE>();
            this.CONTRATO_SERVICIOS_NEG_ESP = new HashSet<CONTRATO_SERVICIOS_NEG_ESP>();
        }
    
        public string CLIENTE_CODIGO_BIC { get; set; }
        public string MONEDA_ORIGEN_CODIGO_DE_M { get; set; }
        public Nullable<System.DateTime> FECHA_DE_INICIO_DEL_CONTR { get; set; }
        public Nullable<System.DateTime> FECHA_DE_FIN_DEL_CONTRATO { get; set; }
        public string ESTADO_DEL_CONTRATO { get; set; }
        public string FRECUENCIA_DE_FACTURACION { get; set; }
        public string VENDEDOR_CODIGO_BIC { get; set; }
        public Nullable<int> ANO_DEL_PERIODO { get; set; }
        public Nullable<int> NUMERO_DEL_PERIODO { get; set; }
        public string CODIGO_DE_IMPUESTO { get; set; }
        public string USUARIO_QUE_AGREGO { get; set; }
        public Nullable<System.DateTime> FECHA_QUE_AGREGO { get; set; }
        public Nullable<System.DateTime> HORA_QUE_AGREGO { get; set; }
        public string USUARIO_QUE_MODIFICO { get; set; }
        public Nullable<System.DateTime> FECHA_QUE_MODIFICO { get; set; }
        public Nullable<System.DateTime> HORA_QUE_MODIFICO { get; set; }
    
        public virtual CLIENTE_TABLA CLIENTE_TABLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO_SERVICIOS_DETALLE> CONTRATO_SERVICIOS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO_SERVICIOS_NEG_ESP> CONTRATO_SERVICIOS_NEG_ESP { get; set; }
        public virtual MONEDA_TABLA MONEDA_TABLA { get; set; }
        public virtual VENDEDOR_TABLA VENDEDOR_TABLA { get; set; }
    }
}
