//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class COTIZACION_RESPUESTA
    {
        public int NUMERO_DE_COTIZACION { get; set; }
        public int NUMERO_DE_LINEA { get; set; }
        public string CODIGO_BIC { get; set; }
        public Nullable<decimal> VALOR_TOTAL_GRABADO { get; set; }
        public string IMPUESTO_INCLUIDO { get; set; }
        public string EXENTA { get; set; }
        public string COMENTARIOS { get; set; }
    
        public virtual COTIZACION_DETALLE COTIZACION_DETALLE { get; set; }
        public virtual COTIZACION_PROVEEDOR COTIZACION_PROVEEDOR { get; set; }
        public virtual COTIZACION_SELECCIONADA COTIZACION_SELECCIONADA { get; set; }
    }
}
