//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class COTIZACION_PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COTIZACION_PROVEEDOR()
        {
            this.COTIZACION_RESPUESTA = new HashSet<COTIZACION_RESPUESTA>();
        }
    
        public int NUMERO_DE_COTIZACION { get; set; }
        public string CODIGO_BIC { get; set; }
        public Nullable<int> DIAS_VALIDEZ_DE_COTIZACIO { get; set; }
        public Nullable<int> DIAS_DE_ENTREGA { get; set; }
        public Nullable<System.DateTime> FECHA_DE_ENTREGA { get; set; }
        public Nullable<decimal> DESCUENTO_POR_PRONTO_PAGO { get; set; }
        public Nullable<decimal> OTROS_DESCUENTOS { get; set; }
        public Nullable<decimal> OTROS_DESCUENTOS_VALOR { get; set; }
        public string CODIGO_DE_MONEDA { get; set; }
        public string CONDICION_DE_PAGO { get; set; }
    
        public virtual COTIZACION_CONTROL COTIZACION_CONTROL { get; set; }
        public virtual PROVEEDOR_TABLA PROVEEDOR_TABLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COTIZACION_RESPUESTA> COTIZACION_RESPUESTA { get; set; }
    }
}
