//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTAS_INVENTARIO
    {
        public string CODIGO_DE_BODEGA { get; set; }
        public int CODIGO_DE_AGENCIA { get; set; }
        public string CODIGO_CENTRO_DE_COSTO { get; set; }
        public string DEFINICION_DEL_PROCESO { get; set; }
        public string CODIGO_DE_CUENTA { get; set; }
        public string TIPO_DE_PARTIDA { get; set; }
        public string TIPO_DE_PARTIDA_CONTABLE { get; set; }
    
        public virtual AGENCIA AGENCIA { get; set; }
        public virtual BODEGA_TABLA BODEGA_TABLA { get; set; }
        public virtual CATALOGO_DE_CUENTAS CATALOGO_DE_CUENTAS { get; set; }
        public virtual INFORMACION_CENTRAL INFORMACION_CENTRAL { get; set; }
    }
}
