//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUESTIONARIO_EVALUACION_PREGUNTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUESTIONARIO_EVALUACION_PREGUNTA()
        {
            this.CUESTIONARIO_EVALUACION_RESPUEST = new HashSet<CUESTIONARIO_EVALUACION_RESPUEST>();
            this.EMPLEADO_EVALUACION_RESPUESTAS = new HashSet<EMPLEADO_EVALUACION_RESPUESTAS>();
        }
    
        public string CUESTIONARIO { get; set; }
        public string FACTOR_DE_EVALUACION { get; set; }
        public int NUMERO_DE_PREGUNTA { get; set; }
        public string DESCRIPCION_DE_PREGUNTA { get; set; }
        public string TIPO_DE_PREGUNTA { get; set; }
        public Nullable<decimal> PONDERACION_DE_LA_PREGUNT { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual CUESTIONARIO_EVALUACION_FACTORES CUESTIONARIO_EVALUACION_FACTORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUESTIONARIO_EVALUACION_RESPUEST> CUESTIONARIO_EVALUACION_RESPUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_EVALUACION_RESPUESTAS> EMPLEADO_EVALUACION_RESPUESTAS { get; set; }
    }
}
