//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUESTIONARIO_EVALUACION_CONTROL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUESTIONARIO_EVALUACION_CONTROL()
        {
            this.CUESTIONARIO_EVALUACION_CONCEPTO = new HashSet<CUESTIONARIO_EVALUACION_CONCEPTO>();
            this.CUESTIONARIO_EVALUACION_FACTORES = new HashSet<CUESTIONARIO_EVALUACION_FACTORES>();
            this.EMPLEADO_EVALUACION_CONTROL = new HashSet<EMPLEADO_EVALUACION_CONTROL>();
        }
    
        public string CUESTIONARIO { get; set; }
        public string DESCRIPCION_DEL_CUESTIONA { get; set; }
        public string ABREVIATURA_DEL_CUESTIONA { get; set; }
        public string OBSERVACIONES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUESTIONARIO_EVALUACION_CONCEPTO> CUESTIONARIO_EVALUACION_CONCEPTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUESTIONARIO_EVALUACION_FACTORES> CUESTIONARIO_EVALUACION_FACTORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_EVALUACION_CONTROL> EMPLEADO_EVALUACION_CONTROL { get; set; }
    }
}
