//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUESTIONARIO_EVALUACION_CONCEPTO
    {
        public string CUESTIONARIO { get; set; }
        public int LIMITE_INFERIOR { get; set; }
        public int LIMITE_SUPERIOR { get; set; }
        public string DESCRIP_CONCEPTO_CALIFICA { get; set; }
        public string ABREV_CONCEPTO_CALIFICACI { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual CUESTIONARIO_EVALUACION_CONTROL CUESTIONARIO_EVALUACION_CONTROL { get; set; }
    }
}
