//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUESTIONARIO_EVALUACION_FACTORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUESTIONARIO_EVALUACION_FACTORES()
        {
            this.CUESTIONARIO_EVALUACION_PREGUNTA = new HashSet<CUESTIONARIO_EVALUACION_PREGUNTA>();
            this.CUESTIONARIO_EVALUACION_RESPUEST = new HashSet<CUESTIONARIO_EVALUACION_RESPUEST>();
            this.EMPLEADO_EVALUACION_FACTORES = new HashSet<EMPLEADO_EVALUACION_FACTORES>();
        }
    
        public string CUESTIONARIO { get; set; }
        public string FACTOR_DE_EVALUACION { get; set; }
        public string DESCRIPCION_DEL_FACTOR { get; set; }
        public string ABREVIATURA_DEL_FACTOR { get; set; }
        public Nullable<decimal> PONDERACION_DEL_FACTOR { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual CUESTIONARIO_EVALUACION_CONTROL CUESTIONARIO_EVALUACION_CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUESTIONARIO_EVALUACION_PREGUNTA> CUESTIONARIO_EVALUACION_PREGUNTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUESTIONARIO_EVALUACION_RESPUEST> CUESTIONARIO_EVALUACION_RESPUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_EVALUACION_FACTORES> EMPLEADO_EVALUACION_FACTORES { get; set; }
    }
}
