//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUESTIONARIO_EVALUACION_RESPUEST
    {
        public string CUESTIONARIO { get; set; }
        public string FACTOR_DE_EVALUACION { get; set; }
        public int NUMERO_DE_PREGUNTA { get; set; }
        public int NUMERO_DE_RESPUESTA { get; set; }
        public string DESCRIPCION_DE_LA_RESPUES { get; set; }
        public Nullable<int> PUNTOS_DE_LA_RESPUESTA { get; set; }
    
        public virtual CUESTIONARIO_EVALUACION_FACTORES CUESTIONARIO_EVALUACION_FACTORES { get; set; }
        public virtual CUESTIONARIO_EVALUACION_PREGUNTA CUESTIONARIO_EVALUACION_PREGUNTA { get; set; }
    }
}
