//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSO_DE_CAPACITACION_PHT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CURSO_DE_CAPACITACION_PHT()
        {
            this.GRUPO_DE_CURSO = new HashSet<GRUPO_DE_CURSO>();
            this.HISTORIAL_DE_CAPACITACION = new HashSet<HISTORIAL_DE_CAPACITACION>();
        }
    
        public string CODIGO_DE_CURSO { get; set; }
        public string NOMBRE_DEL_CURSO { get; set; }
        public string ABREVIATURA_DEL_CURSO { get; set; }
        public Nullable<decimal> COSTO_ESTANDAR_PARTICIPAN { get; set; }
        public Nullable<short> TIEMPO_PROMEDIO_DURACION { get; set; }
        public string DESCRIPCION_DEL_CURSO { get; set; }
        public string OBJETIVOS_DEL_CURSO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRUPO_DE_CURSO> GRUPO_DE_CURSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_DE_CAPACITACION> HISTORIAL_DE_CAPACITACION { get; set; }
    }
}
