//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CXP_MULTIPLE_DOCUMENT6L0T
    {
        public string CODIGO_BIC { get; set; }
        public int ANO_DEL_PERIODO { get; set; }
        public int NUMERO_DEL_PERIODO { get; set; }
        public string DOCUMENTO_TRANSACCION_ICP { get; set; }
        public decimal NUMERO_LINEA { get; set; }
        public string CODIGO_DE_CUENTA { get; set; }
        public Nullable<decimal> VALOR_TRANSACCION_ORIGEN { get; set; }
        public Nullable<decimal> VALOR_TRANSACCION_ORIG2JT { get; set; }
        public string DESCRIPCION_PARTIDA_DETAL { get; set; }
        public string CXP_ESTADO_MULTIPLE_DOCTO { get; set; }
        public string CODIGO_CENTRO_DE_COSTO { get; set; }
        public string CODIGO_TIPO_DE_GASTO { get; set; }
    
        public virtual CATALOGO_DE_CUENTAS CATALOGO_DE_CUENTAS { get; set; }
        public virtual CXP_MULTIPLE_DOCUMENT6KUT CXP_MULTIPLE_DOCUMENT6KUT { get; set; }
    }
}
