//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CXP_MULTIPLE_DOCUMENT6KUT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CXP_MULTIPLE_DOCUMENT6KUT()
        {
            this.CXP_MULTIPLE_DOCUMENT6L0T = new HashSet<CXP_MULTIPLE_DOCUMENT6L0T>();
        }
    
        public string CODIGO_BIC { get; set; }
        public int ANO_DEL_PERIODO { get; set; }
        public int NUMERO_DEL_PERIODO { get; set; }
        public string DOCUMENTO_TRANSACCION_ICP { get; set; }
        public Nullable<System.DateTime> FECHA_DE_FACTURA { get; set; }
        public string CODIGO_FORMAS_PAGO { get; set; }
        public string CODIGO_DE_MONEDA { get; set; }
        public Nullable<decimal> VALOR_FACTURA { get; set; }
        public Nullable<decimal> IMPUESTO_FACTURA { get; set; }
        public Nullable<decimal> RETENCION_IMPUESTO { get; set; }
        public Nullable<decimal> VALOR_TASA_DE_CAMBIO { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO_FACTURA { get; set; }
        public string DESCRIPCION_PARTIDA_DETAL { get; set; }
        public string CXP_ESTADO_MULTIPLE_DOCTO { get; set; }
        public string PREFIJO_PARTIDA_CONTABLE { get; set; }
        public Nullable<int> NUMERO_DE_PARTIDA { get; set; }
    
        public virtual FORMAS_DE_PAGO FORMAS_DE_PAGO { get; set; }
        public virtual MONEDA_TABLA MONEDA_TABLA { get; set; }
        public virtual CXP_MULTIPLE_DOCUMENTOS_T CXP_MULTIPLE_DOCUMENTOS_T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CXP_MULTIPLE_DOCUMENT6L0T> CXP_MULTIPLE_DOCUMENT6L0T { get; set; }
    }
}
