//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class CXP_FACTURASPENDIENTEXPRT
    {
        public string CODIGO_BIC { get; set; }
        public string DOCUMENTO_TRANSACCION_ICP { get; set; }
        public string CODIGO_DE_MONEDA { get; set; }
        public Nullable<decimal> VALOR_FACTURA { get; set; }
        public Nullable<decimal> LH6o0A { get; set; }
        public Nullable<System.DateTime> FECHA_DE_FACTURA { get; set; }
        public Nullable<decimal> LY6agA { get; set; }
        public Nullable<decimal> VALOR_TASA_DE_CAMBIO { get; set; }
    
        public virtual PROVEEDOR_TABLA PROVEEDOR_TABLA { get; set; }
        public virtual MONEDA_TABLA MONEDA_TABLA { get; set; }
    }
}
