//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOS_ADICIONALES_AF
    {
        public string CODIGO_ACTIVO_FIJO { get; set; }
        public int ENSAMBLE_ACTIVO_FIJO { get; set; }
        public string Datos_Adicionales_1 { get; set; }
        public string Datos_Adicionales_2 { get; set; }
        public string Datos_Adicionales_3 { get; set; }
        public string Datos_Adicionales_4 { get; set; }
        public string Datos_Adicionales_5 { get; set; }
        public string Datos_Adicionales_6 { get; set; }
        public string Datos_Adicionales_7 { get; set; }
        public string Datos_Adicionales_8 { get; set; }
        public string Datos_Adicionales_9 { get; set; }
        public string Datos_Adicionales_10 { get; set; }
    
        public virtual ACTIVO_FIJO_TABLA ACTIVO_FIJO_TABLA { get; set; }
    }
}
