//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEF_TRN_PLA_ACUM
    {
        public string CODIGO_DEF_TRN_PLANILLA { get; set; }
        public string TIPO_ACUMULADO_PLANILLA { get; set; }
        public string OPERACION_TIPO_ACUMULADO { get; set; }
    
        public virtual DEF_TRN_PLA_CTL DEF_TRN_PLA_CTL { get; set; }
        public virtual TIPO_ACUMULADOS TIPO_ACUMULADOS { get; set; }
    }
}
