//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEF_TRN_PLA_CTL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEF_TRN_PLA_CTL()
        {
            this.DEF_TRN_PLA_ACUM = new HashSet<DEF_TRN_PLA_ACUM>();
            this.DEF_TRN_PLA_DET = new HashSet<DEF_TRN_PLA_DET>();
            this.EMPLEADO_TRN_FIJAS_PHYSIT = new HashSet<EMPLEADO_TRN_FIJAS_PHYSIT>();
            this.EMPLEADO_DISTRIBUCION_CONTABLE = new HashSet<EMPLEADO_DISTRIBUCION_CONTABLE>();
            this.FICHA_DE_GRABACION_NOMINT = new HashSet<FICHA_DE_GRABACION_NOMINT>();
            this.FICHA_DE_GRABACION_RECOLT = new HashSet<FICHA_DE_GRABACION_RECOLT>();
            this.PLANILLA_HISTORICA = new HashSet<PLANILLA_HISTORICA>();
            this.PLANILLA_MENSUAL_PDA_HOSPITAL = new HashSet<PLANILLA_MENSUAL_PDA_HOSPITAL>();
            this.TIPO_SALDOS_PLA = new HashSet<TIPO_SALDOS_PLA>();
            this.TRANSAC_PLA_CTL = new HashSet<TRANSAC_PLA_CTL>();
            this.TRN_CNT_DIARIO_PLA_NUM = new HashSet<TRN_CNT_DIARIO_PLA_NUM>();
            this.TRN_CONTABLE_DIARIO_PLA = new HashSet<TRN_CONTABLE_DIARIO_PLA>();
        }
    
        public string CODIGO_DEF_TRN_PLANILLA { get; set; }
        public string NOMBRE_DEF_TRN_PLANILLA { get; set; }
        public string ABREVIATURA_DEF_TRN_PLANI { get; set; }
        public string TIPO_DEF_TRN_PLANILLA { get; set; }
        public string TIPO_CALC_TRN_PLANILLA { get; set; }
        public Nullable<int> SECUENCIA_CALC_DEF_TRN_PL { get; set; }
        public string PIDE_VALOR { get; set; }
        public string NOMBRE_VALOR { get; set; }
        public Nullable<decimal> VALOR_A_ASUMIR { get; set; }
        public string PIDE_HORAS { get; set; }
        public string NOMBRE_HORAS { get; set; }
        public Nullable<decimal> HORAS_A_ASUMIR { get; set; }
        public string PIDE_DIAS { get; set; }
        public string NOMBRE_DIAS { get; set; }
        public Nullable<decimal> DIAS_A_ASUMIR { get; set; }
        public string PIDE_UNIDADES { get; set; }
        public string NOMBRE_UNIDADES { get; set; }
        public Nullable<decimal> UNIDADES_A_ASUMIR { get; set; }
        public string DEFINICION_DEL_PROCESO { get; set; }
        public string NOMBRE_VAR_1_DEF_TRN_PLAN { get; set; }
        public Nullable<decimal> VALOR_VAR_1_DEF_TRN_PLANI { get; set; }
        public string NOMBRE_VAR_2_DEF_TRN_PLAN { get; set; }
        public Nullable<decimal> VALOR_VAR_2_DEF_TRN_PLANI { get; set; }
        public string NOMBRE_VAR_3_DEF_TRN_PLAN { get; set; }
        public Nullable<decimal> VALOR_VAR_3_DEF_TRN_PLANI { get; set; }
        public string NOMBRE_VAR_4_DEF_TRN_PLAN { get; set; }
        public Nullable<decimal> VALOR_VAR_4_DEF_TRN_PLANI { get; set; }
        public string NOMBRE_VAR_5_DEF_TRN_PLAN { get; set; }
        public Nullable<decimal> VALOR_VAR_5_DEF_TRN_PLANI { get; set; }
        public string CODIGO_CLASE_DE_PLANILLA { get; set; }
        public string CODIGO_TIPO_DE_PLANILLA { get; set; }
    
        public virtual CLASE_DE_PLANILLA CLASE_DE_PLANILLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEF_TRN_PLA_ACUM> DEF_TRN_PLA_ACUM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEF_TRN_PLA_DET> DEF_TRN_PLA_DET { get; set; }
        public virtual INFORMACION_CENTRAL INFORMACION_CENTRAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_TRN_FIJAS_PHYSIT> EMPLEADO_TRN_FIJAS_PHYSIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_DISTRIBUCION_CONTABLE> EMPLEADO_DISTRIBUCION_CONTABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FICHA_DE_GRABACION_NOMINT> FICHA_DE_GRABACION_NOMINT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FICHA_DE_GRABACION_RECOLT> FICHA_DE_GRABACION_RECOLT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANILLA_HISTORICA> PLANILLA_HISTORICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANILLA_MENSUAL_PDA_HOSPITAL> PLANILLA_MENSUAL_PDA_HOSPITAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_SALDOS_PLA> TIPO_SALDOS_PLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSAC_PLA_CTL> TRANSAC_PLA_CTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_CNT_DIARIO_PLA_NUM> TRN_CNT_DIARIO_PLA_NUM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_CONTABLE_DIARIO_PLA> TRN_CONTABLE_DIARIO_PLA { get; set; }
    }
}
