//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEF_TRN_PLA_DET
    {
        public string CODIGO_DEF_TRN_PLANILLA { get; set; }
        public decimal NUMERO_LINEA_DEF_TRN_PLAN { get; set; }
        public string RESULTADO_DEF_TRN_PLANILL { get; set; }
        public string FACTOR1_CODIGO_OPERACION { get; set; }
        public string OPERACION_DEF_TRN_PLANILL { get; set; }
        public string FACTOR_2_CODIGO_OPERACION { get; set; }
        public string CONSTANTE_DEF_TRN_PLANILL { get; set; }
    
        public virtual DEF_TRN_PLA_CTL DEF_TRN_PLA_CTL { get; set; }
    }
}
