//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENTO_TABLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPARTAMENTO_TABLA()
        {
            this.ARTICULO_REQUISICION = new HashSet<ARTICULO_REQUISICION>();
            this.EMPLEADO_TABLA = new HashSet<EMPLEADO_TABLA>();
            this.RECETA_MASIVA_MEDICAMENTT = new HashSet<RECETA_MASIVA_MEDICAMENTT>();
            this.RECETA_TABLA = new HashSet<RECETA_TABLA>();
            this.RECETAS_SIN_DESPACHAR = new HashSet<RECETAS_SIN_DESPACHAR>();
            this.REQUISICION_CONTROL = new HashSet<REQUISICION_CONTROL>();
            this.REQUISICION_DETALLE = new HashSet<REQUISICION_DETALLE>();
            this.SERVICIO_HOSPITAL = new HashSet<SERVICIO_HOSPITAL>();
            this.SUBDEPARTAMENTO = new HashSet<SUBDEPARTAMENTO>();
            this.TRABAJO_NOMINA = new HashSet<TRABAJO_NOMINA>();
        }
    
        public string CODIGO_DE_DEPARTAMENTO { get; set; }
        public string NOMBRE_DE_DEPARTAMENTO { get; set; }
        public string ABREVIATURA_DE_DEPARTAMEN { get; set; }
        public string ESTATUS_DE_DEPARTAMENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO_REQUISICION> ARTICULO_REQUISICION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_TABLA> EMPLEADO_TABLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECETA_MASIVA_MEDICAMENTT> RECETA_MASIVA_MEDICAMENTT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECETA_TABLA> RECETA_TABLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECETAS_SIN_DESPACHAR> RECETAS_SIN_DESPACHAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUISICION_CONTROL> REQUISICION_CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUISICION_DETALLE> REQUISICION_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIO_HOSPITAL> SERVICIO_HOSPITAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBDEPARTAMENTO> SUBDEPARTAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRABAJO_NOMINA> TRABAJO_NOMINA { get; set; }
    }
}
