//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESCUENTOS_PHYSICAL_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DESCUENTOS_PHYSICAL_TABLE()
        {
            this.CLIENTE_DESCUENTO = new HashSet<CLIENTE_DESCUENTO>();
            this.ESCALAS_DE_DESCUENTO_PHYT = new HashSet<ESCALAS_DE_DESCUENTO_PHYT>();
        }
    
        public string CODIGO_DE_DESCUENTO { get; set; }
        public string DESCRIPCION_DE_DESCUENTO { get; set; }
        public string ABREVIATURA_DE_DESCUENTO { get; set; }
        public Nullable<decimal> PORCENTAJE_DE_DESCUENTO { get; set; }
        public Nullable<decimal> VALOR_DE_DESCUENTO { get; set; }
        public string TIPO_DE_DESCUENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_DESCUENTO> CLIENTE_DESCUENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESCALAS_DE_DESCUENTO_PHYT> ESCALAS_DE_DESCUENTO_PHYT { get; set; }
    }
}
