//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRIBUCION_COSTOS_INDIRECTOS
    {
        public string ORIGEN_DE_DISTRIBUCION { get; set; }
        public System.DateTime FECHA_DE_COSTOS { get; set; }
        public Nullable<int> ANO_DEL_PERIODO { get; set; }
        public Nullable<int> NUMERO_DEL_PERIODO { get; set; }
        public string CODIGO_CENTRO_DE_COSTO { get; set; }
        public Nullable<decimal> CANTIDAD_PACIENTES { get; set; }
        public Nullable<decimal> CANTIDAD_EMPLEADOS { get; set; }
        public Nullable<decimal> COSTO_DISTRIBUIDO { get; set; }
        public Nullable<decimal> COSTO_DISTRIBUIDO_EMPLEAD { get; set; }
        public string ESTADO_DE_LA_DISTRIBUCION { get; set; }
    
        public virtual CENTRO_DE_COSTO CENTRO_DE_COSTO { get; set; }
        public virtual PERIODO_CONTABLE PERIODO_CONTABLE { get; set; }
    }
}
