//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCTOR()
        {
            this.ATENCIONES_MEDICAS_CONTROL = new HashSet<ATENCIONES_MEDICAS_CONTROL>();
            this.CITAS_MEDICAS_CONTROL = new HashSet<CITAS_MEDICAS_CONTROL>();
            this.CITAS_MEDICAS_DETALLE_PHT = new HashSet<CITAS_MEDICAS_DETALLE_PHT>();
            this.ORDEN_ATENCION_MEDICA_CTL = new HashSet<ORDEN_ATENCION_MEDICA_CTL>();
            this.RECETA_TABLA = new HashSet<RECETA_TABLA>();
            this.RECETAS_SIN_DESPACHAR = new HashSet<RECETAS_SIN_DESPACHAR>();
        }
    
        public string CODIGO_BIC { get; set; }
        public string ESPECIALIDAD_DEL_DOCTOR { get; set; }
        public string ESTATUS_DEL_DOCTOR { get; set; }
        public Nullable<System.DateTime> HORA_ADICION { get; set; }
        public Nullable<System.DateTime> FECHA_ADICION { get; set; }
        public string USUARIO_ADICION { get; set; }
        public Nullable<System.DateTime> HORA_ULTIMO_CAMBIO { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_CAMBIO { get; set; }
        public string USUARIO_ULTIMO_CAMBIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATENCIONES_MEDICAS_CONTROL> ATENCIONES_MEDICAS_CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CITAS_MEDICAS_CONTROL> CITAS_MEDICAS_CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CITAS_MEDICAS_DETALLE_PHT> CITAS_MEDICAS_DETALLE_PHT { get; set; }
        public virtual EMPLEADO_TABLA EMPLEADO_TABLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_ATENCION_MEDICA_CTL> ORDEN_ATENCION_MEDICA_CTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECETA_TABLA> RECETA_TABLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECETAS_SIN_DESPACHAR> RECETAS_SIN_DESPACHAR { get; set; }
    }
}
