//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPAQUE_TABLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPAQUE_TABLA()
        {
            this.ARTICULO_REQUISICION = new HashSet<ARTICULO_REQUISICION>();
            this.TRANSFERENCIA_INVENTA3E4T = new HashSet<TRANSFERENCIA_INVENTA3E4T>();
        }
    
        public string CODIGO_DE_EMPAQUE { get; set; }
        public string DESCRIPCION_EMPAQUE { get; set; }
        public string ABREVIATURA_EMPAQUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO_REQUISICION> ARTICULO_REQUISICION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSFERENCIA_INVENTA3E4T> TRANSFERENCIA_INVENTA3E4T { get; set; }
    }
}
