//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO_EVALUACION_FACTORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO_EVALUACION_FACTORES()
        {
            this.EMPLEADO_EVALUACION_RESPUESTAS = new HashSet<EMPLEADO_EVALUACION_RESPUESTAS>();
        }
    
        public string CODIGO_BIC { get; set; }
        public string CUESTIONARIO { get; set; }
        public System.DateTime FECHA_DE_EVALUACION { get; set; }
        public string FACTOR_DE_EVALUACION { get; set; }
        public Nullable<decimal> CALIFICACION_DEL_FACTOR { get; set; }
    
        public virtual CUESTIONARIO_EVALUACION_FACTORES CUESTIONARIO_EVALUACION_FACTORES { get; set; }
        public virtual EMPLEADO_EVALUACION_CONTROL EMPLEADO_EVALUACION_CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_EVALUACION_RESPUESTAS> EMPLEADO_EVALUACION_RESPUESTAS { get; set; }
    }
}
