//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO_EXPERIENCIA_LABORAL
    {
        public string CODIGO_BIC { get; set; }
        public int CORRELATIVO_EXPERIENCIA_L { get; set; }
        public string PERIODO_EXPERIENCIA_LABOR { get; set; }
        public string LUGAR_EXPERIENCIA_LABORAL { get; set; }
        public string PUESTO_EXPERIENCIA_LABORA { get; set; }
        public string JEFE_EXPERIENCIA_LABORAL { get; set; }
        public string FUNCION_EXPERIENCIA_LABOR { get; set; }
    
        public virtual EMPLEADO_TABLA EMPLEADO_TABLA { get; set; }
    }
}
