//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO_TURNOS
    {
        public string CODIGO_BIC { get; set; }
        public decimal FECHA_DE_INICIO_DE_TURNO { get; set; }
        public string CODIGO_DE_HORARIO { get; set; }
        public Nullable<int> CODIGO_TURNO { get; set; }
        public string COMENTARIOS { get; set; }
    
        public virtual EMPLEADO_TABLA EMPLEADO_TABLA { get; set; }
        public virtual HORARIOS HORARIOS { get; set; }
        public virtual TURNOS TURNOS { get; set; }
    }
}
