//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO_RESUMEN_HORARIO
    {
        public string CODIGO_BIC { get; set; }
        public decimal FECHA8_DAY { get; set; }
        public decimal FECHA8_MONTH { get; set; }
        public decimal FECHA8_YEAR { get; set; }
        public Nullable<decimal> HORA_ENTRADA_HORA { get; set; }
        public Nullable<decimal> HORA_ENTRADA_MINUTO { get; set; }
        public Nullable<decimal> FECHA_SALIDA_INTERMED_DIA { get; set; }
        public Nullable<decimal> FECHA_SALIDA_INTERMED_MES { get; set; }
        public Nullable<decimal> FECHA_SALIDA_INTERMED_ANO { get; set; }
        public Nullable<decimal> HORA_SALIDA_INTERMEDIA_HORA { get; set; }
        public Nullable<decimal> HORA_SALIDA_INTERMED_MINUTO { get; set; }
        public Nullable<decimal> FECHA_ENTRADA_INTERMED_DIA { get; set; }
        public Nullable<decimal> FECHA_ENTRADA_INTERMED_MES { get; set; }
        public Nullable<decimal> FECHA_ENTRADA_INTERMED_ANO { get; set; }
        public Nullable<decimal> HORA_ENTRADA_INTERMED_HORA { get; set; }
        public Nullable<decimal> HORA_ENTRADA_INTERMED_MINUTO { get; set; }
        public Nullable<decimal> FECHA_SALIDA_DAY { get; set; }
        public Nullable<decimal> FECHA_SALIDA_MONTH { get; set; }
        public Nullable<decimal> FECHA_SALIDA_YEAR { get; set; }
        public Nullable<decimal> HORA_SALIDA_HORA { get; set; }
        public Nullable<decimal> HORA_SALIDA_MINUTO { get; set; }
        public Nullable<decimal> DIAS_FALTADOS { get; set; }
        public Nullable<decimal> HORAS_EXTRAS_SIN_RECARGO { get; set; }
        public Nullable<decimal> HORAS_EXTRAS_AL_25 { get; set; }
        public Nullable<decimal> HORAS_EXTRAS_AL_50 { get; set; }
        public Nullable<decimal> HORAS_EXTRAS_AL_75 { get; set; }
        public Nullable<decimal> HORAS_EXTRAS_DOBLES { get; set; }
        public Nullable<decimal> OTROS_DIAS { get; set; }
        public Nullable<decimal> OTRAS_HORAS { get; set; }
        public string ESTATUS_DE_LA_FECHA { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual EMPLEADO_TABLA EMPLEADO_TABLA { get; set; }
    }
}
