//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO_CARNET_ACTIVO
    {
        public string CODIGO_BIC { get; set; }
        public int NUMERO_DE_CARNET { get; set; }
        public string NOMBRE_DEL_EMPLEADO { get; set; }
        public string NOMBRE_CORTO_DEL_EMPLEADO { get; set; }
        public string ESTATUS_DEL_CARNET { get; set; }
        public string NOMBRE_DEL_PUESTO { get; set; }
        public string NOMBRE_DE_DEPARTAMENTO { get; set; }
        public string NOMBRE_DEL_ARCHIVO { get; set; }
        public Nullable<System.DateTime> FECHA_DE_EMISION { get; set; }
        public string EMITIDO_POR { get; set; }
        public string CARNET_IMPRESO { get; set; }
        public string IDENTIDAD_DEL_EMPLEADO { get; set; }
    
        public virtual EMPLEADO_TABLA EMPLEADO_TABLA { get; set; }
    }
}
