//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO_EDUCACION
    {
        public string CODIGO_BIC { get; set; }
        public string NIVEL_DE_EDUCACION { get; set; }
        public string NOMBRE_CENTRO_EDUCATIVO { get; set; }
        public Nullable<int> AÑO_INICIAL_DE_ESTUDIO { get; set; }
        public Nullable<int> AÑO_FINAL_DE_ESTUDIO { get; set; }
        public Nullable<int> PERIODO_DE_ESTUDIO_AÑOS { get; set; }
        public Nullable<int> PERIODO_DE_ESTUDIO_MESES { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual EMPLEADO_TABLA EMPLEADO_TABLA { get; set; }
        public virtual NIVEL_DE_EDUCACION_TABLA NIVEL_DE_EDUCACION_TABLA { get; set; }
    }
}
