//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENFERMEDAD_TABLA
    {
        public string ENTERMEDAD { get; set; }
        public string NOMBRE_DE_LA_ENFERMEDAD { get; set; }
        public string NOMBRE_CONOCIDO_DE_ENFERM { get; set; }
        public string SINTOMAS_DE_LA_ENFERMEDAD { get; set; }
        public string TRATAMIENTO_DE_LA_ENFERME { get; set; }
    }
}
