//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENSAMBLE_DE_ARTICULO
    {
        public string ARTICULO_ENSAMBLADO_CODIG { get; set; }
        public string CODIGO_DE_ARTICULO { get; set; }
        public string CODIGO_DE_EMPAQUE { get; set; }
        public string CODIGO_UNIDAD_DE_MEDIDA { get; set; }
        public Nullable<decimal> CONTENIDO { get; set; }
        public string NOMBRE_DEL_ENSAMBLE { get; set; }
    
        public virtual ARTICULO_TABLA ARTICULO_TABLA { get; set; }
        public virtual PRESENTACION_TABLA PRESENTACION_TABLA { get; set; }
    }
}
