//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCALAS_DE_DESCUENTO_PHYT
    {
        public string CODIGO_DE_DESCUENTO { get; set; }
        public int NUMERO_DE_ESCALA { get; set; }
        public Nullable<decimal> PORCENTAJE_DE_DESCUENTO { get; set; }
        public Nullable<decimal> VALOR_DE_DESCUENTO { get; set; }
        public Nullable<decimal> VOLUMEN_INICIAL_DE_VENTAS { get; set; }
        public Nullable<decimal> VOLUMEN_FINAL_DE_VENTAS { get; set; }
        public string TIPO_DESCUENTO_POR_ESCALA { get; set; }
    
        public virtual DESCUENTOS_PHYSICAL_TABLE DESCUENTOS_PHYSICAL_TABLE { get; set; }
    }
}
