//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_FINANCIERO_DET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTADO_FINANCIERO_DET()
        {
            this.ESTADO_FINANCIERO_CTA_COL = new HashSet<ESTADO_FINANCIERO_CTA_COL>();
            this.ESTADO_FINANCIERO_CUENTAS = new HashSet<ESTADO_FINANCIERO_CUENTAS>();
        }
    
        public string CODIGO_DE_ESTADO_FINANCIE { get; set; }
        public decimal LINEA_ESTADO_FINANCIERO { get; set; }
        public string TEXTO_LINEA_ESTADO_FINANC { get; set; }
        public string VALOR_1_LINEA_ESTADO_FINA { get; set; }
        public string VALOR_2_LINEA_ESTADO_FINA { get; set; }
        public string VALOR_3_LINEA_ESTADO_FINA { get; set; }
        public string VALOR_4_LINEA_ESTADO_FINA { get; set; }
        public string VALOR_5_LINEA_ESTADO_FINA { get; set; }
        public string VALOR_6_LINEA_ESTADO_FINA { get; set; }
        public string OPERACION_1_LINEA_EST_FIN { get; set; }
        public string OPERACION_2_LINEA_EST_FIN { get; set; }
        public string OPERACION_3_LINEA_EST_FIN { get; set; }
        public string OPERACION_4_LINEA_EST_FIN { get; set; }
        public string OPERACION_5_LINEA_EST_FIN { get; set; }
        public string OPERACION_6_LINEA_EST_FIN { get; set; }
        public string CAMPO_1_LINEA_EST_FIN { get; set; }
        public string CAMPO_2_LINEA_EST_FIN { get; set; }
        public string CAMPO_3_LINEA_EST_FIN { get; set; }
        public string CAMPO_4_LINEA_EST_FIN { get; set; }
        public string CAMPO_5_LINEA_EST_FIN { get; set; }
        public string CAMPO_6_LINEA_EST_FIN { get; set; }
        public string SIGNO_1_LINEA_EST_FIN { get; set; }
        public string SIGNO_2_LINEA_EST_FIN { get; set; }
        public string SIGNO_3_LINEA_EST_FIN { get; set; }
        public string SIGNO_4_LINEA_EST_FIN { get; set; }
        public string SIGNO_5_LINEA_EST_FIN { get; set; }
        public string SIGNO_6_LINEA_EST_FIN { get; set; }
        public string LETRA_NEGRITA_LINEA_EST_F { get; set; }
        public string SUBRAYADO { get; set; }
        public string IMPRIME_LINEA { get; set; }
        public string LADO_DE_LA_IMPRESION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTADO_FINANCIERO_CTA_COL> ESTADO_FINANCIERO_CTA_COL { get; set; }
        public virtual ESTADO_FINANCIERO_CTL ESTADO_FINANCIERO_CTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTADO_FINANCIERO_CUENTAS> ESTADO_FINANCIERO_CUENTAS { get; set; }
    }
}
