//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_FINANCIERO_CTL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTADO_FINANCIERO_CTL()
        {
            this.ESTADO_FINANCIERO_DET = new HashSet<ESTADO_FINANCIERO_DET>();
        }
    
        public string CODIGO_DE_ESTADO_FINANCIE { get; set; }
        public string NOMBRE_DEL_ESTADO_FINANCI { get; set; }
        public string SUBTITULO_DEL_ESTADO_FINA { get; set; }
        public string COLUMNA_1_ESTADO_FINANCIE { get; set; }
        public string COLUMNA_2_ESTADO_FINANCIE { get; set; }
        public string COLUMNA_3_ESTADO_FINANCIE { get; set; }
        public string COLUMNA_4_ESTADO_FINANCIE { get; set; }
        public string COLUMNA_5_ESTADO_FINANCIE { get; set; }
        public string COLUMNA_6_ESTADO_FINANCIE { get; set; }
        public string SIGNO_ESTADO_FINANCIERO { get; set; }
        public string TIPO_ESTADO_FINANCIERO { get; set; }
        public Nullable<int> NUMERO_DE_DECIMALES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTADO_FINANCIERO_DET> ESTADO_FINANCIERO_DET { get; set; }
    }
}
