//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_FINANCIERO_CTA_COL
    {
        public string CODIGO_DE_ESTADO_FINANCIE { get; set; }
        public decimal LINEA_ESTADO_FINANCIERO { get; set; }
        public decimal COLUMNA { get; set; }
        public string CODIGO_DE_CUENTA { get; set; }
        public string OPERACION { get; set; }
    
        public virtual CATALOGO_DE_CUENTAS CATALOGO_DE_CUENTAS { get; set; }
        public virtual ESTADO_FINANCIERO_DET ESTADO_FINANCIERO_DET { get; set; }
    }
}
