//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTRUCTURA_ESTADO_CUENTA
    {
        public string CODIGO_BIC { get; set; }
        public string CUENTA_BANCARIA { get; set; }
        public string CHEQUE_FECHA_FORMATO { get; set; }
        public string CREDITO_TRAE_SIGNO_NEGATI { get; set; }
        public string DELIMITADOR_ENTRE_CAMPOS { get; set; }
        public string SI_ES_OTRO_DELIMITADOR_QU { get; set; }
    
        public virtual CUENTA_DE_BANCO CUENTA_DE_BANCO { get; set; }
    }
}
