//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTRUCTURA_PRESUPUESTO
    {
        public string CODIGO_DE_COMPANIA { get; set; }
        public string MANEJA_PRESUPUESTO { get; set; }
        public string NOMBRE_PRESUPUESTO_1 { get; set; }
        public Nullable<int> INICIO_PRESUPUESTO_1 { get; set; }
        public Nullable<int> LONGITUD_PRESUPUESTO_1 { get; set; }
        public string SEPARADOR_PRESUPUESTO_1 { get; set; }
        public string VALOR_POR_OMISION_1 { get; set; }
        public string NOMBRE_PRESUPUESTO_2 { get; set; }
        public Nullable<int> INICIO_PRESUPUESTO_2 { get; set; }
        public Nullable<int> LONGITUD_PRESUPUESTO_2 { get; set; }
        public string SEPARADOR_PRESUPUESTO_2 { get; set; }
        public string VALOR_POR_OMISION_2 { get; set; }
        public string NOMBRE_PRESUPUESTO_3 { get; set; }
        public Nullable<int> INICIO_PRESUPUESTO_3 { get; set; }
        public Nullable<int> LONGITUD_PRESUPUESTO_3 { get; set; }
        public string SEPARADOR_PRESUPUESTO_3 { get; set; }
        public string VALOR_POR_OMISION_3 { get; set; }
        public string NOMBRE_PRESUPUESTO_4 { get; set; }
        public Nullable<int> INICIO_PRESUPUESTO_4 { get; set; }
        public Nullable<int> LONGITUD_PRESUPUESTO_4 { get; set; }
        public string SEPARADOR_PRESUPUESTO_4 { get; set; }
        public string VALOR_POR_OMISION_4 { get; set; }
        public string NOMBRE_PRESUPUESTO_5 { get; set; }
        public Nullable<int> INICIO_PRESUPUESTO_5 { get; set; }
        public Nullable<int> LONGITUD_PRESUPUESTO_5 { get; set; }
        public string SEPARADOR_PRESUPUESTO_5 { get; set; }
        public string VALOR_POR_OMISION_5 { get; set; }
        public string NOMBRE_PRESUPUESTO_6 { get; set; }
        public Nullable<int> INICIO_PRESUPUESTO_6 { get; set; }
        public Nullable<int> LONGITUD_PRESUPUESTO_6 { get; set; }
        public string SEPARADOR_PRESUPUESTO_6 { get; set; }
        public string VALOR_POR_OMISION_6 { get; set; }
        public string NOMBRE_PRESUPUESTO_7 { get; set; }
        public Nullable<int> INICIO_PRESUPUESTO_7 { get; set; }
        public Nullable<int> LONGITUD_PRESUPUESTO_7 { get; set; }
        public string SEPARADOR_PRESUPUESTO_7 { get; set; }
        public string VALOR_POR_OMISION_7 { get; set; }
        public string NOMBRE_PRESUPUESTO_8 { get; set; }
        public Nullable<int> INICIO_PRESUPUESTO_8 { get; set; }
        public Nullable<int> LONGITUD_PRESUPUESTO_8 { get; set; }
        public string SEPARADOR_PRESUPUESTO_8 { get; set; }
        public string VALOR_POR_OMISION_8 { get; set; }
        public string NOMBRE_PRESUPUESTO_9 { get; set; }
        public Nullable<int> INICIO_PRESUPUESTO_9 { get; set; }
        public Nullable<int> LONGITUD_PRESUPUESTO_9 { get; set; }
        public string VALOR_POR_OMISION_9 { get; set; }
    }
}
