//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTRUCTURA_FACTURA_ADUANERA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTRUCTURA_FACTURA_ADUANERA()
        {
            this.FACTURA_AGENTE_ADUANERO_DET = new HashSet<FACTURA_AGENTE_ADUANERO_DET>();
        }
    
        public decimal LINEA_DE_ESTRUCTURA { get; set; }
        public string NOMBRE_DE_ESTRUCTURA { get; set; }
        public string PIDE_ESTRUCTURA { get; set; }
        public string ADICIONA_CLIENTE_A_LA_CUE { get; set; }
        public string TIPO_DE_CALCULO { get; set; }
        public Nullable<decimal> VALOR_POR_OMISION { get; set; }
        public string TEXTO_POR_OMISION { get; set; }
        public string COLUMNA_DE_IMPRESION { get; set; }
        public string ACUMULE_PARA_IMPUESTO { get; set; }
        public string CODIGO_DE_CUENTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_AGENTE_ADUANERO_DET> FACTURA_AGENTE_ADUANERO_DET { get; set; }
    }
}
