//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_DIARIA_CONTROL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURA_DIARIA_CONTROL()
        {
            this.FACTURA_DIARIA_DETALLE = new HashSet<FACTURA_DIARIA_DETALLE>();
            this.FACTURA_DIARIA_DETALLE_PAGOS = new HashSet<FACTURA_DIARIA_DETALLE_PAGOS>();
        }
    
        public string PREFIJO_PARTIDA_CONTABLE { get; set; }
        public int NUMFACTURA { get; set; }
        public Nullable<System.DateTime> FECHA_DE_FACTURA { get; set; }
        public string CODIGO_BIC { get; set; }
        public string MONEDA_ORIGEN_CODIGO_DE_M { get; set; }
        public string DOCUMENTO_1 { get; set; }
        public string DOCUMENTO_2 { get; set; }
        public string ORDEN_COMPRA_DEL_CLIENTE { get; set; }
        public string REFERENCIA_DEL_CLIENTE { get; set; }
        public string DIRECCION_DE_FACTURACION { get; set; }
        public string CIUDAD_DE_FACTURACION { get; set; }
        public string ENTREGAR_A { get; set; }
        public string DIRECCION_DE_ENTREGA { get; set; }
        public string CIUDAD_DE_ENTREGA { get; set; }
        public string OBSERVACIONES { get; set; }
        public string STATUS_DE_LA_FACTURA { get; set; }
        public string STATUS_DE_DESPACHO { get; set; }
        public string STATUS_DE_COBRO { get; set; }
        public Nullable<decimal> VALOR_TASA_DE_CAMBIO { get; set; }
        public Nullable<decimal> TOTAL_DESCUENTO { get; set; }
        public Nullable<decimal> TOTAL_DESCUENTO_FINANCIERO { get; set; }
        public Nullable<decimal> TOTAl_DESCUENTO_REEXPR { get; set; }
        public Nullable<decimal> TOTAL_IMPUESTO { get; set; }
        public Nullable<decimal> TOTAL_IMPUESTO_FINANCIERO { get; set; }
        public Nullable<decimal> TOTAL_IMPUESTO_REEXPR { get; set; }
        public Nullable<decimal> TOTAL_IMPUESTO_2 { get; set; }
        public Nullable<decimal> TOTAL_IMPUESTO2_FINANCIERO { get; set; }
        public Nullable<decimal> TOTAL_IMPUESTO2_REEXPR { get; set; }
        public Nullable<decimal> TOTAL_COMISION_VENTA { get; set; }
        public Nullable<decimal> TOTAL_COMISION_FINANCIERO { get; set; }
        public Nullable<decimal> TOTAL_COMISION_REEXPR { get; set; }
        public Nullable<decimal> TOTAL_COMISION_COBRO { get; set; }
        public Nullable<decimal> TOTAL_COMISION_COBRO_FINAN { get; set; }
        public Nullable<decimal> TOTAL_COMISION_COBRO_REEXPR { get; set; }
        public Nullable<decimal> TOTAL_COMISION_3 { get; set; }
        public Nullable<decimal> TOTAL_COMISION3_FINAN { get; set; }
        public Nullable<decimal> TOTAL_COMISION3_REEXPR { get; set; }
        public Nullable<decimal> TOTAL_COMISION_4 { get; set; }
        public Nullable<decimal> TOTAL_COMISION4_FINAN { get; set; }
        public Nullable<decimal> TOTAL_COMISION4_REEXPR { get; set; }
        public Nullable<decimal> TOTAL_DE_FACTURA { get; set; }
        public Nullable<decimal> TOTAL_FACTURA_FINANCIERO { get; set; }
        public Nullable<decimal> TOTAL_FACTURA_REEXPR { get; set; }
        public string PARTIDA_CONTABLE_GENERADA { get; set; }
        public string AFECTACION_AL_INVENTARIO { get; set; }
        public string AFECTO_CUENTAS_POR_COBRAR { get; set; }
        public string VENDEDOR_CODIGO_BIC { get; set; }
        public string CAJERO_CODIGO_BIC { get; set; }
        public string COBRADOR_CODIGO_BIC { get; set; }
        public string TECNICO_CODIGO_BIC { get; set; }
        public string PUNTO_DE_VENTA_CODIGO_BIC { get; set; }
        public Nullable<int> ANO_DEL_PERIODO { get; set; }
        public Nullable<int> NUMERO_DEL_PERIODO { get; set; }
        public string CODIGO_DE_BODEGA { get; set; }
        public string CODIGO_FORMAS_PAGO { get; set; }
        public string VIN { get; set; }
        public string NOMBRE_MARCA { get; set; }
        public string NOMBRE_MODELO { get; set; }
        public string PLACA { get; set; }
        public Nullable<int> AÑO_DEL_VEHICULO { get; set; }
        public Nullable<System.DateTime> HORA_ADICION { get; set; }
        public Nullable<System.DateTime> FECHA_ADICION { get; set; }
        public string USUARIO_ADICION { get; set; }
        public Nullable<System.DateTime> HORA_ULTIMO_CAMBIO { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_CAMBIO { get; set; }
        public string USUARIO_ULTIMO_CAMBIO { get; set; }
    
        public virtual BODEGA_TABLA BODEGA_TABLA { get; set; }
        public virtual CLIENTE_TABLA CLIENTE_TABLA { get; set; }
        public virtual FORMAS_DE_PAGO FORMAS_DE_PAGO { get; set; }
        public virtual MONEDA_TABLA MONEDA_TABLA { get; set; }
        public virtual NUMERACION_PARTIDAS NUMERACION_PARTIDAS { get; set; }
        public virtual PUNTO_DE_VENTA PUNTO_DE_VENTA { get; set; }
        public virtual PERIODO_CONTABLE PERIODO_CONTABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_DIARIA_DETALLE> FACTURA_DIARIA_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_DIARIA_DETALLE_PAGOS> FACTURA_DIARIA_DETALLE_PAGOS { get; set; }
    }
}
