//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_DIARIA_DETALLE
    {
        public string PREFIJO_PARTIDA_CONTABLE { get; set; }
        public int NUMFACTURA { get; set; }
        public int NUMERO_DE_LINEA { get; set; }
        public string CODIGO_DE_ARTICULO { get; set; }
        public string CODIGO_DE_EMPAQUE { get; set; }
        public string CODIGO_UNIDAD_DE_MEDIDA { get; set; }
        public string CODIGO_DE_BODEGA { get; set; }
        public string NOMBRE_DEL_ARTICULO { get; set; }
        public Nullable<decimal> CANTIDAD_A_FACTURAR { get; set; }
        public Nullable<decimal> CANTIDAD_ENTREGADA { get; set; }
        public Nullable<decimal> PRECIO_DE_VENTA { get; set; }
        public Nullable<decimal> FINANCIERO_PRECIO_DE_VENT { get; set; }
        public Nullable<decimal> REEXPRESION_PRECIO_DE_VEN { get; set; }
        public Nullable<decimal> PRECIO_REAL_DE_VENTA { get; set; }
        public string DESCRIPCION_DETALLE_DE_FA { get; set; }
        public Nullable<decimal> VALOR_DEL_IMPUESTO { get; set; }
        public Nullable<decimal> VALOR_DEL_DESCUENTO { get; set; }
        public string ESTATUS_DETALLE_FACTURA { get; set; }
        public string ESTATUS_DE_IMPRESION { get; set; }
        public Nullable<decimal> VALOR_COMISION_VENDEDOR { get; set; }
        public Nullable<decimal> VALOR_COMISION_SUPERVISOR { get; set; }
        public Nullable<decimal> VALOR_COMISION_GERENTE { get; set; }
        public Nullable<decimal> PORCENTAJE_DEL_IMPUESTO { get; set; }
        public Nullable<decimal> PORCENTAJE_DE_DESCUENTO { get; set; }
        public Nullable<decimal> PORCENTAJE_COMISION_VENDE { get; set; }
        public Nullable<decimal> PORCENTAJE_COMISION_SUPER { get; set; }
        public Nullable<decimal> PORCENTAJE_COMISION_GEREN { get; set; }
        public string DOCUMENTO_1 { get; set; }
        public string CODIGO_LISTA_PRECIOS { get; set; }
        public string VENDEDOR_CODIGO_BIC { get; set; }
        public string TECNICO_CODIGO_BIC { get; set; }
    
        public virtual ARTICULO_BODEGA_PRES ARTICULO_BODEGA_PRES { get; set; }
        public virtual ARTICULO_TABLA ARTICULO_TABLA { get; set; }
        public virtual FACTURA_DIARIA_CONTROL FACTURA_DIARIA_CONTROL { get; set; }
        public virtual LISTA_DE_PRECIO_CONTROL LISTA_DE_PRECIO_CONTROL { get; set; }
        public virtual PRESENTACION_TABLA PRESENTACION_TABLA { get; set; }
    }
}
