//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_AGENTE_ADUANERO_CTL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURA_AGENTE_ADUANERO_CTL()
        {
            this.FACTURA_AGENTE_ADUANERO_DET = new HashSet<FACTURA_AGENTE_ADUANERO_DET>();
        }
    
        public string PREFIJO_PARTIDA_CONTABLE { get; set; }
        public int NUMFACTURA { get; set; }
        public Nullable<int> CODIGO_DE_AGENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_DE_FACTURA { get; set; }
        public string CODIGO_BIC { get; set; }
        public string LIQUIDACION_Y_GASTOS_DE { get; set; }
        public string MARCA_EN_POLIZA { get; set; }
        public string REMITIDO_POR { get; set; }
        public string FACTURA_COMERCIAL { get; set; }
        public string EN_VAPOR { get; set; }
        public Nullable<decimal> PESO_KG { get; set; }
        public Nullable<decimal> VALOR_CIF { get; set; }
        public Nullable<System.DateTime> FECHA_DE_PAGO_POLIZA { get; set; }
        public string STATUS_DE_FACTURA { get; set; }
        public string USUARIO { get; set; }
        public string DEFINICION_DEL_PROCESO { get; set; }
        public Nullable<int> ANO_DEL_PERIODO { get; set; }
        public Nullable<int> NUMERO_DEL_PERIODO { get; set; }
    
        public virtual AGENCIA AGENCIA { get; set; }
        public virtual CLIENTE_TABLA CLIENTE_TABLA { get; set; }
        public virtual NUMERACION_PARTIDAS NUMERACION_PARTIDAS { get; set; }
        public virtual PERIODO_CONTABLE PERIODO_CONTABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_AGENTE_ADUANERO_DET> FACTURA_AGENTE_ADUANERO_DET { get; set; }
    }
}
