//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_AGENTE_ADUANERO_DET
    {
        public string PREFIJO_PARTIDA_CONTABLE { get; set; }
        public int NUMFACTURA { get; set; }
        public decimal LINEA_DE_ESTRUCTURA { get; set; }
        public string TEXTO_SOLICITADO { get; set; }
        public Nullable<decimal> VALOR_SOLICITADO { get; set; }
    
        public virtual ESTRUCTURA_FACTURA_ADUANERA ESTRUCTURA_FACTURA_ADUANERA { get; set; }
        public virtual FACTURA_AGENTE_ADUANERO_CTL FACTURA_AGENTE_ADUANERO_CTL { get; set; }
    }
}
