//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_DIARIA_DETALLE_PAGOS
    {
        public string PREFIJO_PARTIDA_CONTABLE { get; set; }
        public int NUMFACTURA { get; set; }
        public int LINEA { get; set; }
        public string CODIGO_FORMAS_PAGO { get; set; }
        public string CODIGO_BIC { get; set; }
        public string TARJETA_DE_CREDITO { get; set; }
        public string NUMERO_DE_CHEQUERA { get; set; }
        public Nullable<int> NUMERO_DE_CHEQUE { get; set; }
        public string NUMERO_DE_TARJETA_DE_CRED { get; set; }
        public string MONEDA_ORIGEN_CODIGO_DE_M { get; set; }
        public Nullable<decimal> VALOR_PAGADO { get; set; }
        public Nullable<decimal> VALOR_PAGADO_FINANCIERO { get; set; }
        public Nullable<decimal> VALOR_PAGADO_REEXPRESION { get; set; }
        public Nullable<decimal> VALOR_TASA_DE_CAMBIO { get; set; }
        public string COMENTARIOS { get; set; }
        public Nullable<int> MES_VENCIMIENTO_TARJETA { get; set; }
        public Nullable<int> AÑO_VENCIMIENTO_TARJETA { get; set; }
    
        public virtual FACTURA_DIARIA_CONTROL FACTURA_DIARIA_CONTROL { get; set; }
        public virtual FORMAS_DE_PAGO FORMAS_DE_PAGO { get; set; }
        public virtual MONEDA_TABLA MONEDA_TABLA { get; set; }
    }
}
