//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURAS_SERVICIOS_DETALLE
    {
        public int NUMERO_DE_FACTURA_DE_SERV { get; set; }
        public decimal LINEA_DETALLE_DEL_SERVICI { get; set; }
        public Nullable<decimal> CANTIDAD_DE_SERVICIOS { get; set; }
        public string CODIGO_DE_SERVICIO { get; set; }
        public string CODIGO_TIPO_SERVICIO { get; set; }
        public string CODIGO_DETALLE_SERVICIO { get; set; }
        public string DESCRIPCION_DEL_SERVICIO { get; set; }
        public Nullable<decimal> VALOR_DEL_SERVICIO { get; set; }
        public string SITIO_A_DEL_CONTRATO { get; set; }
        public string SITIO_B_DEL_CONTRATO { get; set; }
    
        public virtual DETALLE_DEL_SERVICIO_PHYT DETALLE_DEL_SERVICIO_PHYT { get; set; }
        public virtual FACTURAS_SERVICIOS_CONTROL FACTURAS_SERVICIOS_CONTROL { get; set; }
    }
}
