//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICHA_DE_GRABACION_NOMINT
    {
        public string CODIGO_CLASE_DE_PLANILLA { get; set; }
        public string CODIGO_TIPO_DE_PLANILLA { get; set; }
        public string DESCRIPCION_FICHA_GRABACI { get; set; }
        public string CODIGO_DEF_TRN_PLANILLA { get; set; }
        public string A_CODIGO_DEF_TRN_PLANILLA { get; set; }
        public string A_CODIGO_DEF_TRN_PLANI5V7 { get; set; }
        public string A_CODIGO_DEF_TRN_PLANI5V9 { get; set; }
        public string A_CODIGO_DEF_TRN_PLANI5VB { get; set; }
        public string A_CODIGO_DEF_TRN_PLANI5VD { get; set; }
        public string A_CODIGO_DEF_TRN_PLANI5VF { get; set; }
        public string A_CODIGO_DEF_TRN_PLANI5VH { get; set; }
        public string A_CODIGO_DEF_TRN_PLANI5VJ { get; set; }
        public string A0_CODIGO_DEF_TRN_PLANILL { get; set; }
    
        public virtual CLASE_DE_PLANILLA CLASE_DE_PLANILLA { get; set; }
        public virtual DEF_TRN_PLA_CTL DEF_TRN_PLA_CTL { get; set; }
        public virtual TIPO_DE_PLANILLA TIPO_DE_PLANILLA { get; set; }
    }
}
