//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONES_DEL_MENU
    {
        public string OS39A { get; set; }
        public string NOMBRE_DE_FUNCION { get; set; }
        public string CODIGO_DE_MODULO { get; set; }
        public string SUBMODULO { get; set; }
    
        public virtual MODULO MODULO { get; set; }
    }
}
