//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABILIDADES_PHYSICAL_TABT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HABILIDADES_PHYSICAL_TABT()
        {
            this.EMPLEADO_HABILIDADES = new HashSet<EMPLEADO_HABILIDADES>();
        }
    
        public string CODIGO_DE_HABILIDAD { get; set; }
        public string DESCRIPCION_DE_HABILIDAD { get; set; }
        public string HABILIDAD_APLICA_AL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_HABILIDADES> EMPLEADO_HABILIDADES { get; set; }
    }
}
