//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class hbs003
    {
        public string CODIGO_OPERACION_NOMINA { get; set; }
        public string DESCRIPCION_OPERACION_NOM { get; set; }
        public string SUBRUTINA_A_LLAMAR { get; set; }
    }
}
