//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_DEPREC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HISTORIAL_DEPREC()
        {
            this.HISTORIAL_DEPREC_DT = new HashSet<HISTORIAL_DEPREC_DT>();
        }
    
        public int ANO_DEL_PERIODO { get; set; }
        public int NUMERO_DEL_PERIODO { get; set; }
        public string DESCRIPCION_DEPRECIACION { get; set; }
        public string STATUS_DEPRECIACION { get; set; }
        public Nullable<System.DateTime> FECHAEJECUCIONDEPRECIACIO { get; set; }
        public string EJECUTADO_POR { get; set; }
    
        public virtual PERIODO_CONTABLE PERIODO_CONTABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_DEPREC_DT> HISTORIAL_DEPREC_DT { get; set; }
    }
}
