//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_DEPREC_DT
    {
        public int ANO_DEL_PERIODO { get; set; }
        public int NUMERO_DEL_PERIODO { get; set; }
        public string CODIGO_ACTIVO_FIJO { get; set; }
        public int ENSAMBLE_ACTIVO_FIJO { get; set; }
        public Nullable<System.DateTime> FECHA_DEPRECIACION { get; set; }
        public Nullable<decimal> DEPREC_ACUM_MONEDA_ORIGEN { get; set; }
        public Nullable<decimal> DEPREC_ACUM_MONEDA_FINANC { get; set; }
        public Nullable<decimal> DEPREC_ACUM_MONEDA_REEXPR { get; set; }
        public Nullable<decimal> VALOR_LIBROS_ORIGEN { get; set; }
        public Nullable<decimal> FINANCIERA_VALOR_LIBROS_O { get; set; }
        public Nullable<decimal> REEXPRECION_VALOR_LIBROS { get; set; }
        public Nullable<decimal> VALOR_DEPRECIADO_ORIGEN { get; set; }
        public Nullable<decimal> FINANCIERA_VALOR_DEPRECIA { get; set; }
        public Nullable<decimal> REEXPRECION_VALOR_DEPRECI { get; set; }
        public Nullable<System.DateTime> FECHAEJECUCIONDEPRECIACIO { get; set; }
        public string STATUS_DEPRECIACION { get; set; }
    
        public virtual ACTIVO_FIJO_TABLA ACTIVO_FIJO_TABLA { get; set; }
        public virtual HISTORIAL_DEPREC HISTORIAL_DEPREC { get; set; }
    }
}
