//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_SALARIAL
    {
        public string CODIGO_BIC { get; set; }
        public System.DateTime FECHA_VIGENCIA_AUMENTO { get; set; }
        public Nullable<decimal> SUELDO_MENSUAL { get; set; }
        public Nullable<decimal> SUELDO_QUINCENAL { get; set; }
        public Nullable<decimal> SUELDO_SEMANAL { get; set; }
        public Nullable<decimal> SUELDO_DIARIO { get; set; }
        public string COMENTARIOS_DE_AUMENTO { get; set; }
        public string CODIGO_CAUSA_AUMENTO { get; set; }
    
        public virtual CAUSAS_DE_AUMENTO CAUSAS_DE_AUMENTO { get; set; }
        public virtual EMPLEADO_TABLA EMPLEADO_TABLA { get; set; }
    }
}
