//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN_PROMPTU_CONTROL_DIARIO
    {
        public System.DateTime FECHA_DEL_IN_PROMPTU { get; set; }
        public decimal NUMERO_DEL_IN_PROMPTU { get; set; }
        public Nullable<int> EXPEDIENTE { get; set; }
        public string APELLIDO_1_DEL_PACIENTE { get; set; }
        public string APELLIDO_2_DEL_PACIENTE { get; set; }
        public string NOMBRES_DEL_PACIENTE { get; set; }
        public string IDENTIDAD_DEL_PACIENTE { get; set; }
        public string FECHA_DE_NACIMIENTO { get; set; }
        public Nullable<decimal> LR6izA { get; set; }
        public Nullable<decimal> LR6j1A { get; set; }
        public Nullable<decimal> LR6j0A { get; set; }
        public string Sexo { get; set; }
        public string NOMBRE_DE_LA_MADRE { get; set; }
        public string NOMBRE_DEL_PADRE { get; set; }
        public string PERSONA_QUE_TRAJO_AL_PACI { get; set; }
        public string SECTOR_SOCIOECONOMICO { get; set; }
        public string DIRECCION { get; set; }
        public string CIUDAD { get; set; }
        public string TELEFONO_DEL_PACIENTE { get; set; }
        public string SINTOMA_PRINCIPAL { get; set; }
        public string DIAGNOSTICO_DE_ENTRADA_EN { get; set; }
        public string DIAGNOSTICO_DE_SALIDA_ENT { get; set; }
        public string CODIGO_BIC { get; set; }
        public string DESTINO_DEL_PACIENTE { get; set; }
        public string FUE_REALMENTE_UNA_EMERGEN { get; set; }
        public string ESTATUS_DEL_IN_PROMPTU { get; set; }
    
        public virtual SECTOR_SOCIOECONOMICO SECTOR_SOCIOECONOMICO1 { get; set; }
    }
}
