//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCIDENCIAS_RECURSOS_HUMT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INCIDENCIAS_RECURSOS_HUMT()
        {
            this.INCIDENCIAS_EMPLEADO = new HashSet<INCIDENCIAS_EMPLEADO>();
        }
    
        public string CODIGO_INCIDENCIA { get; set; }
        public string DESCRIPCION_INCIDENCIA { get; set; }
        public string TITULO_FECHA_INICIAL { get; set; }
        public string TITULO_FECHA_FINAL { get; set; }
        public string GENERA_TRANSACCION_PLANIL { get; set; }
        public string CODIGO_DEF_TRN_PLANILLA { get; set; }
        public string CAMBIAR_ESTATUS_A_INACTIV { get; set; }
        public string CAMBIAR_ESTATUS_A_ACTIVO { get; set; }
        public string CAMBIAR_ESTATUS_A_BAJA { get; set; }
        public string GENERA_ACCION_DE_PERSONAL { get; set; }
        public string FORMATO_ACCION_DE_PERSONA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INCIDENCIAS_EMPLEADO> INCIDENCIAS_EMPLEADO { get; set; }
    }
}
