//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTRUCTOR_PHYSICAL_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSTRUCTOR_PHYSICAL_TABLE()
        {
            this.GRUPO_DE_CURSO = new HashSet<GRUPO_DE_CURSO>();
        }
    
        public string CODIGO_BIC { get; set; }
        public string TIPO_DEL_INSTRUCTOR { get; set; }
    
        public virtual BASE_INFO_CENTRAL BASE_INFO_CENTRAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRUPO_DE_CURSO> GRUPO_DE_CURSO { get; set; }
    }
}
