//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTEGRADOR_REPORTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INTEGRADOR_REPORTES()
        {
            this.INTEGRADOR_REPORTES_DATOS = new HashSet<INTEGRADOR_REPORTES_DATOS>();
            this.INTEGRADOR_REPORTES_PARA = new HashSet<INTEGRADOR_REPORTES_PARA>();
        }
    
        public decimal SURROGATE { get; set; }
        public string TITULO_DEL_REPORTE { get; set; }
        public string ARCHIVO_DEL_REPORTE { get; set; }
        public string CODIGO_DE_MODULO { get; set; }
    
        public virtual MODULO MODULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTEGRADOR_REPORTES_DATOS> INTEGRADOR_REPORTES_DATOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTEGRADOR_REPORTES_PARA> INTEGRADOR_REPORTES_PARA { get; set; }
    }
}
