//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTEGRADOR_REPORTES_DATOS
    {
        public decimal SURROGATE { get; set; }
        public string OS4sA { get; set; }
        public string FUNCION { get; set; }
        public decimal LY7gkA { get; set; }
        public string LY7gmA { get; set; }
        public Nullable<decimal> LY7gnA { get; set; }
        public Nullable<System.DateTime> LR6fvA { get; set; }
        public Nullable<System.DateTime> ly953A { get; set; }
    
        public virtual INTEGRADOR_REPORTES INTEGRADOR_REPORTES { get; set; }
        public virtual INTEGRADOR_REPORTES_PARA INTEGRADOR_REPORTES_PARA { get; set; }
    }
}
