//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA_DE_PRECIO_CONTROL_T
    {
        public string CODIGO_LISTA_PRECIOS { get; set; }
        public Nullable<System.DateTime> FECHA_VIGENCIA_PRECIOS { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_PRECIOS { get; set; }
        public string DESCRIPCION_LISTA_PRECIOS { get; set; }
        public string ly7ttA { get; set; }
    }
}
