//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIA_PRIMA_Y_MATERIALT
    {
        public string CODIGO { get; set; }
        public string NUMERO_DE_RESOLUCION_DEI { get; set; }
        public Nullable<decimal> CANT_RESOLUCION { get; set; }
        public string CODIGO_UNIDAD_DE_MEDIDA { get; set; }
        public string DESCRIPCION_UNIDAD_DE_MED { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
    
        public virtual MATERIA_PRIMA_Y_MAT_CTRL MATERIA_PRIMA_Y_MAT_CTRL { get; set; }
        public virtual UNIDAD_MEDIDA_TBL UNIDAD_MEDIDA_TBL { get; set; }
    }
}
