//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class NIVEL_JERARQUIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NIVEL_JERARQUIA()
        {
            this.PUESTO_PHYSICAL_TABLE = new HashSet<PUESTO_PHYSICAL_TABLE>();
        }
    
        public int NIVEL_DE_JERARQUIA { get; set; }
        public string DESCRIPCION_NIVEL_JERARQU { get; set; }
        public string ABREVIATURA_NIVEL_JERARQU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUESTO_PHYSICAL_TABLE> PUESTO_PHYSICAL_TABLE { get; set; }
    }
}
