//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJETO_DEL_GASTO_TABLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBJETO_DEL_GASTO_TABLA()
        {
            this.PG_CUENTA_PRESUPUESTO = new HashSet<PG_CUENTA_PRESUPUESTO>();
        }
    
        public string OBJETO_DEL_GASTO { get; set; }
        public string NOMBRE_DEL_OBJETO_DEL_GAS { get; set; }
        public string ABREVIATURA_OBJETO_GASTO { get; set; }
        public string PERMITE_MOVIMIENTO { get; set; }
        public string ERP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PG_CUENTA_PRESUPUESTO> PG_CUENTA_PRESUPUESTO { get; set; }
    }
}
