//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_ATENCION_MEDICA_CTL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDEN_ATENCION_MEDICA_CTL()
        {
            this.ORDEN_ATENCION_MEDICA_DET = new HashSet<ORDEN_ATENCION_MEDICA_DET>();
        }
    
        public int ANO_DEL_PERIODO { get; set; }
        public int NUMERO_DE_FACTURA { get; set; }
        public Nullable<System.DateTime> FECHA_DE_FACTURA { get; set; }
        public Nullable<int> EXPEDIENTE { get; set; }
        public Nullable<System.DateTime> LH759A { get; set; }
        public Nullable<decimal> LH75aA { get; set; }
        public string ASIGNADO_A_UN_CENTRO_DE_C { get; set; }
        public string CODIGO_BIC { get; set; }
        public string TIPO_DE_SERVICIO { get; set; }
        public string TIPO_DE_CITA { get; set; }
        public string ESTATUS_DE_LA_FACTURA { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO_HOSPITALIZA { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA_HOSPITALIZACIO { get; set; }
        public string TIPO_PACIENTE { get; set; }
        public Nullable<System.DateTime> HORA_ADICION { get; set; }
        public Nullable<System.DateTime> FECHA_ADICION { get; set; }
        public string USUARIO_ADICION { get; set; }
        public Nullable<System.DateTime> HORA_ULTIMO_CAMBIO { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_CAMBIO { get; set; }
        public string USUARIO_ULTIMO_CAMBIO { get; set; }
    
        public virtual CENTRO_DE_COSTO CENTRO_DE_COSTO { get; set; }
        public virtual DOCTOR DOCTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_ATENCION_MEDICA_DET> ORDEN_ATENCION_MEDICA_DET { get; set; }
    }
}
