//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_COMPRA_CTRL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDEN_COMPRA_CTRL()
        {
            this.ORDEN_COMPRA_DET = new HashSet<ORDEN_COMPRA_DET>();
        }
    
        public int NUMERO_ORDEN_DE_COMPRA { get; set; }
        public string TIPO_DE_ORDEN { get; set; }
        public Nullable<System.DateTime> FECHA_DE_ORDEN { get; set; }
        public string CHEQUE_PAGO_DE_ORDEN { get; set; }
        public string ESTATUS_DE_ORDEN { get; set; }
        public string UTILIZADA_EN { get; set; }
        public Nullable<int> NUMERO_DE_COTIZACION { get; set; }
        public string CODIGO_BIC { get; set; }
        public string APROBADA_POR_CODIGO_BIC { get; set; }
    
        public virtual PROVEEDOR_TABLA PROVEEDOR_TABLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_COMPRA_DET> ORDEN_COMPRA_DET { get; set; }
    }
}
