//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANISMO_FINANCIADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORGANISMO_FINANCIADOR()
        {
            this.PG_CUENTA_PRESUPUESTO = new HashSet<PG_CUENTA_PRESUPUESTO>();
        }
    
        public string ORGANISMO_FINANCIADOR1 { get; set; }
        public string NOMBRE_ORGANISMO_FINANCIA { get; set; }
        public string ABREVIATURA_ORGANISMO_FIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PG_CUENTA_PRESUPUESTO> PG_CUENTA_PRESUPUESTO { get; set; }
    }
}
