//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORIGEN_DE_LOS_FONDOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORIGEN_DE_LOS_FONDOS()
        {
            this.APERTURA_CIERRE_CAJERO = new HashSet<APERTURA_CIERRE_CAJERO>();
            this.ARQUEO_CAJERO_HOSPITAL_PT = new HashSet<ARQUEO_CAJERO_HOSPITAL_PT>();
            this.ORIGEN_DE_LOS_FONDOS_DIST = new HashSet<ORIGEN_DE_LOS_FONDOS_DIST>();
            this.RECIBO_SERVICIOS_HOSPITAL_CTL = new HashSet<RECIBO_SERVICIOS_HOSPITAL_CTL>();
        }
    
        public string CODIGO_ORIGEN_DEL_FONDO { get; set; }
        public string DESCRIPCION_ORIGEN_DEL_FO { get; set; }
        public string ABREVIATURA_ORIGEN_DEL_FO { get; set; }
        public Nullable<decimal> LH74dA { get; set; }
        public string CODIGO_DE_CUENTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APERTURA_CIERRE_CAJERO> APERTURA_CIERRE_CAJERO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARQUEO_CAJERO_HOSPITAL_PT> ARQUEO_CAJERO_HOSPITAL_PT { get; set; }
        public virtual CATALOGO_DE_CUENTAS CATALOGO_DE_CUENTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORIGEN_DE_LOS_FONDOS_DIST> ORIGEN_DE_LOS_FONDOS_DIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECIBO_SERVICIOS_HOSPITAL_CTL> RECIBO_SERVICIOS_HOSPITAL_CTL { get; set; }
    }
}
