//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSgT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OSgT()
        {
            this.OS12T = new HashSet<OS12T>();
            this.OS20T = new HashSet<OS20T>();
            this.OS4T = new HashSet<OS4T>();
        }
    
        public Nullable<System.DateTime> OBF002 { get; set; }
        public Nullable<System.DateTime> OBF003 { get; set; }
        public Nullable<System.DateTime> OBF005 { get; set; }
        public Nullable<System.DateTime> OBF006 { get; set; }
        public string OS3dA { get; set; }
        public string OS3eA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OS12T> OS12T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OS20T> OS20T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OS4T> OS4T { get; set; }
    }
}
