//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE_CRONICOS_OTROHSD
    {
        public string CODIGO_DEL_HOSPITAL { get; set; }
        public int EXPEDIENTE { get; set; }
        public string CODIGO_DE_ARTICULO { get; set; }
        public System.DateTime FECHA_DE_ENTREGA { get; set; }
        public decimal CORRELATIVO_CRONICO { get; set; }
        public Nullable<decimal> CANTIDAD_PRESCRITA { get; set; }
        public Nullable<decimal> CANTIDAD_ENTREGADA { get; set; }
        public Nullable<decimal> COSTO_TOTAL { get; set; }
        public Nullable<int> DURACION_EN_DIAS { get; set; }
        public Nullable<decimal> DOSIS_DIARIA { get; set; }
        public Nullable<System.DateTime> FECHA_DE_PROXIMA_CITA { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<int> NUMERO_DE_RECETA { get; set; }
        public Nullable<decimal> NUMERO_LINEA { get; set; }
    
        public virtual PACIENTE_CRONICOS_OTROHSP PACIENTE_CRONICOS_OTROHSP { get; set; }
    }
}
