//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACIENTE()
        {
            this.ATENCIONES_MEDICAS_DETALLE = new HashSet<ATENCIONES_MEDICAS_DETALLE>();
            this.CITAS_MEDICAS_DETALLE_PHT = new HashSet<CITAS_MEDICAS_DETALLE_PHT>();
            this.PACIENTE_CRONICO_CONTROL = new HashSet<PACIENTE_CRONICO_CONTROL>();
            this.PACIENTE_ARCHIVO_GRAFICT = new HashSet<PACIENTE_ARCHIVO_GRAFICT>();
        }
    
        public int EXPEDIENTE { get; set; }
        public string APELLIDO_1_DEL_PACIENTE { get; set; }
        public string APELLIDO_2_DEL_PACIENTE { get; set; }
        public string NOMBRES_DEL_PACIENTE { get; set; }
        public Nullable<System.DateTime> FECHA_DE_NACIMIENTO_DEL_P { get; set; }
        public string Sexo { get; set; }
        public string IDENTIDAD_DEL_PACIENTE { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION_EXPEDIENTE { get; set; }
        public string NOMBRE_DEL_PADRE { get; set; }
        public string APELLIDO_DEL_PADRE { get; set; }
        public string IDENTIDAD_DEL_PADRE { get; set; }
        public string NOMBRE_DE_LA_MADRE { get; set; }
        public string APELLIDO_DE_LA_MADRE { get; set; }
        public string IDENTIDAD_DE_LA_MADRE { get; set; }
        public string SECTOR_SOCIOECONOMICO { get; set; }
        public string NACIONALIDAD { get; set; }
        public string DIRECCION { get; set; }
        public string CIUDAD { get; set; }
        public string TELEFONO_DEL_PACIENTE { get; set; }
        public string ZONA_GEOGRAFICA { get; set; }
        public string SITUACION_DEL_EXPEDIENTE { get; set; }
        public string EXPEDIENTE_PRESTADO_A { get; set; }
        public Nullable<System.DateTime> FECHA_PRESTAMO_EXPEDIENTE { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMA_CONSULTA { get; set; }
        public string ESTATUS_DEL_PACIENTE { get; set; }
        public Nullable<System.DateTime> HORA_ADICION { get; set; }
        public Nullable<System.DateTime> FECHA_ADICION { get; set; }
        public string USUARIO_ADICION { get; set; }
        public Nullable<System.DateTime> HORA_ULTIMO_CAMBIO { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_CAMBIO { get; set; }
        public string USUARIO_ULTIMO_CAMBIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATENCIONES_MEDICAS_DETALLE> ATENCIONES_MEDICAS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CITAS_MEDICAS_DETALLE_PHT> CITAS_MEDICAS_DETALLE_PHT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_CRONICO_CONTROL> PACIENTE_CRONICO_CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_ARCHIVO_GRAFICT> PACIENTE_ARCHIVO_GRAFICT { get; set; }
    }
}
