//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE_ARCHIVO_GRAFICT
    {
        public int EXPEDIENTE { get; set; }
        public decimal NUMERO_DE_GRAFICO { get; set; }
        public string DESCRIPCION_DE_GRAFICO { get; set; }
        public Nullable<System.DateTime> FECHA_DEL_GRAFICO { get; set; }
        public Nullable<System.DateTime> HORA_DEL_GRAFICO { get; set; }
        public string TIPO_DE_GRAFICO { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
