//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE
    {
        public int EXPEDIENTE { get; set; }
        public string APELLIDO_1_DEL_PACIENTE { get; set; }
        public string APELLIDO_2_DEL_PACIENTE { get; set; }
        public string NOMBRES_DEL_PACIENTE { get; set; }
        public Nullable<System.DateTime> FECHA_DE_NACIMIENTO_DEL_P { get; set; }
        public string Sexo { get; set; }
        public string IDENTIDAD_DEL_PACIENTE { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION_EXPEDIENTE { get; set; }
        public string NOMBRE_DEL_PADRE { get; set; }
        public string APELLIDO_DEL_PADRE { get; set; }
        public string IDENTIDAD_DEL_PADRE { get; set; }
        public string NOMBRE_DE_LA_MADRE { get; set; }
        public string APELLIDO_DE_LA_MADRE { get; set; }
        public string IDENTIDAD_DE_LA_MADRE { get; set; }
        public string SECTOR_SOCIOECONOMICO { get; set; }
        public string NACIONALIDAD { get; set; }
        public string DIRECCION { get; set; }
        public string CIUDAD { get; set; }
        public string TELEFONO_DEL_PACIENTE { get; set; }
        public string ZONA_GEOGRAFICA { get; set; }
        public string SITUACION_DEL_EXPEDIENTE { get; set; }
        public string EXPEDIENTE_PRESTADO_A { get; set; }
        public Nullable<System.DateTime> FECHA_PRESTAMO_EXPEDIENTE { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMA_CONSULTA { get; set; }
        public string ESTATUS_DEL_PACIENTE { get; set; }
        public Nullable<System.DateTime> HORA_ADICION { get; set; }
        public Nullable<System.DateTime> FECHA_ADICION { get; set; }
        public string USUARIO_ADICION { get; set; }
        public Nullable<System.DateTime> HORA_ULTIMO_CAMBIO { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_CAMBIO { get; set; }
        public string USUARIO_ULTIMO_CAMBIO { get; set; }
    }
}
