//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIS_PHYSICAL_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAIS_PHYSICAL_TABLE()
        {
            this.BASE_INFO_CENTRAL = new HashSet<BASE_INFO_CENTRAL>();
            this.EMPLEADO_TABLA = new HashSet<EMPLEADO_TABLA>();
        }
    
        public string CODIGO_DE_PAIS { get; set; }
        public string NOMBRE_DE_PAIS { get; set; }
        public string ABREVIATURA_DE_PAIS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BASE_INFO_CENTRAL> BASE_INFO_CENTRAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_TABLA> EMPLEADO_TABLA { get; set; }
    }
}
