//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERIODO_DE_PLANILLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERIODO_DE_PLANILLA()
        {
            this.PLANILLA_HISTORICA = new HashSet<PLANILLA_HISTORICA>();
            this.TRABAJO_NOMINA = new HashSet<TRABAJO_NOMINA>();
            this.TRANSAC_PLA_CTL = new HashSet<TRANSAC_PLA_CTL>();
            this.TRN_CNT_DIARIO_PLA_NUM = new HashSet<TRN_CNT_DIARIO_PLA_NUM>();
            this.TRN_CONTABLE_DIARIO_PLA = new HashSet<TRN_CONTABLE_DIARIO_PLA>();
        }
    
        public string CODIGO_CLASE_DE_PLANILLA { get; set; }
        public string CODIGO_TIPO_DE_PLANILLA { get; set; }
        public int ANO_PLANILLA { get; set; }
        public int PERIODO_PLANILLA { get; set; }
        public string DESCRIPCION_PERIODO_PLANI { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_DE_PAGO { get; set; }
        public Nullable<System.DateTime> FECHA_FINAL_DE_PAGO { get; set; }
        public string NOMBRE_VARIABLES_DEL_PERI { get; set; }
        public string NOMBRE_VARIABLES_DEL_P2DG { get; set; }
        public string NOMBRE_VARIABLES_DEL_P2DI { get; set; }
        public string NOMBRE_VARIABLES_DEL_P2DK { get; set; }
        public string NOMBRE_VARIABLES_DEL_P2DM { get; set; }
        public Nullable<decimal> VALOR_VARIABLES_DEL_PERIO { get; set; }
        public Nullable<decimal> VALOR_VARIABLES_DEL_PE2DP { get; set; }
        public Nullable<decimal> VALOR_VARIABLES_DEL_PE2DR { get; set; }
        public Nullable<decimal> VALOR_VARIABLES_DEL_PE2DT { get; set; }
        public Nullable<decimal> VALOR_VARIABLES_DEL_PE2DV { get; set; }
        public string ESTATUS_DEL_PERIODO_DE_PL { get; set; }
        public Nullable<int> ANO_DEL_PERIODO { get; set; }
        public Nullable<int> NUMERO_DEL_PERIODO { get; set; }
    
        public virtual CLASE_DE_PLANILLA CLASE_DE_PLANILLA { get; set; }
        public virtual PERIODO_CONTABLE PERIODO_CONTABLE { get; set; }
        public virtual TIPO_DE_PLANILLA TIPO_DE_PLANILLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANILLA_HISTORICA> PLANILLA_HISTORICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRABAJO_NOMINA> TRABAJO_NOMINA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSAC_PLA_CTL> TRANSAC_PLA_CTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_CNT_DIARIO_PLA_NUM> TRN_CNT_DIARIO_PLA_NUM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_CONTABLE_DIARIO_PLA> TRN_CONTABLE_DIARIO_PLA { get; set; }
    }
}
