//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PG_SUBUNIDAD_EJECUTORA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PG_SUBUNIDAD_EJECUTORA()
        {
            this.PG_CUENTA_PRESUPUESTO = new HashSet<PG_CUENTA_PRESUPUESTO>();
        }
    
        public string INSTITUCION { get; set; }
        public string DESCENTRALIZADA { get; set; }
        public string UNIDAD_EJECUTORA { get; set; }
        public string SUBUNIDAD_EJECUTORA { get; set; }
        public string NOMBRE_SUBUNIDAD_EJECUTOR { get; set; }
        public string ABREVIATURA_SUBUNIDAD_EJE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PG_CUENTA_PRESUPUESTO> PG_CUENTA_PRESUPUESTO { get; set; }
        public virtual PG_DESCENTRALIZADA PG_DESCENTRALIZADA { get; set; }
        public virtual PG_INSTITUCION PG_INSTITUCION { get; set; }
        public virtual PG_UNIDAD_EJECUTORA PG_UNIDAD_EJECUTORA { get; set; }
    }
}
