//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PG_TRN_PRESUPUESTO_ORDEN_DETALLE
    {
        public string DEFINICION_DEL_PROCESO { get; set; }
        public int NUMERO_DE_PARTIDA { get; set; }
        public string INSTITUCION { get; set; }
        public string DESCENTRALIZADA { get; set; }
        public string UNIDAD_EJECUTORA { get; set; }
        public string SUBUNIDAD_EJECUTORA { get; set; }
        public string PROGRAMA { get; set; }
        public string SUBPROGRAMA { get; set; }
        public string PROYECTO { get; set; }
        public string ACTIVIDAD { get; set; }
        public string OBJETO_DEL_GASTO { get; set; }
        public string FUENTE_DE_FINANCIAMIENTO { get; set; }
        public string ORGANISMO_FINANCIADOR { get; set; }
        public string CODIGO_DE_BENEFICIARIO { get; set; }
        public int PARTIDA { get; set; }
        public Nullable<decimal> CANTIDAD_PEDIDA { get; set; }
        public string MEDIDA_CODIGO_UNIDAD_DE_M { get; set; }
        public string DESCRIPCION_ORDEN_DE_COMP { get; set; }
        public Nullable<decimal> PRECIO_POR_UNIDAD { get; set; }
        public string PAGA_IMPUESTO { get; set; }
        public string CODIGO_DE_IMPUESTO { get; set; }
        public string CODIGO_DE_ARTICULO { get; set; }
        public string CODIGO_DE_EMPAQUE { get; set; }
        public string CODIGO_UNIDAD_DE_MEDIDA { get; set; }
    
        public virtual IMPUESTOS_TABLA IMPUESTOS_TABLA { get; set; }
        public virtual PG_TRN_PRESUPUESTO_AFEC_CONTABLE PG_TRN_PRESUPUESTO_AFEC_CONTABLE { get; set; }
        public virtual UNIDAD_MEDIDA_TBL UNIDAD_MEDIDA_TBL { get; set; }
    }
}
