//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PG_TRN_PRESUPUESTO_AFEC_CONTABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PG_TRN_PRESUPUESTO_AFEC_CONTABLE()
        {
            this.PG_TRN_PRESUPUESTO_ORDEN_DETALLE = new HashSet<PG_TRN_PRESUPUESTO_ORDEN_DETALLE>();
        }
    
        public string DEFINICION_DEL_PROCESO { get; set; }
        public int NUMERO_DE_PARTIDA { get; set; }
        public string INSTITUCION { get; set; }
        public string DESCENTRALIZADA { get; set; }
        public string UNIDAD_EJECUTORA { get; set; }
        public string SUBUNIDAD_EJECUTORA { get; set; }
        public string PROGRAMA { get; set; }
        public string SUBPROGRAMA { get; set; }
        public string PROYECTO { get; set; }
        public string ACTIVIDAD { get; set; }
        public string OBJETO_DEL_GASTO { get; set; }
        public string FUENTE_DE_FINANCIAMIENTO { get; set; }
        public string ORGANISMO_FINANCIADOR { get; set; }
        public string CODIGO_DE_BENEFICIARIO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public Nullable<System.DateTime> HORA_ADICION { get; set; }
        public Nullable<System.DateTime> FECHA_ADICION { get; set; }
        public string USUARIO_ADICION { get; set; }
        public Nullable<System.DateTime> HORA_ULTIMO_CAMBIO { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_CAMBIO { get; set; }
        public string USUARIO_ULTIMO_CAMBIO { get; set; }
    
        public virtual PG_CUENTA_PRESUPUESTO PG_CUENTA_PRESUPUESTO { get; set; }
        public virtual PG_TRN_PRESUPUESTO_CONTROL PG_TRN_PRESUPUESTO_CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PG_TRN_PRESUPUESTO_ORDEN_DETALLE> PG_TRN_PRESUPUESTO_ORDEN_DETALLE { get; set; }
    }
}
