//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PG_TRN_PRESUPUESTO_CONTROL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PG_TRN_PRESUPUESTO_CONTROL()
        {
            this.PG_TRN_PRESUPUESTO_AFEC_CONTABLE = new HashSet<PG_TRN_PRESUPUESTO_AFEC_CONTABLE>();
            this.PG_TRN_PRESUPUESTO_BENEFICIARIOS = new HashSet<PG_TRN_PRESUPUESTO_BENEFICIARIOS>();
            this.PG_TRN_PRESUPUESTO_CONTROL_PAGOS = new HashSet<PG_TRN_PRESUPUESTO_CONTROL_PAGOS>();
            this.PG_TRN_PRESUPUESTO_INICIAL = new HashSet<PG_TRN_PRESUPUESTO_INICIAL>();
            this.PG_TRN_PRESUPUESTO_RETEN_DEDUC = new HashSet<PG_TRN_PRESUPUESTO_RETEN_DEDUC>();
        }
    
        public string DEFINICION_DEL_PROCESO { get; set; }
        public int NUMERO_DE_PARTIDA { get; set; }
        public string INSTITUCION { get; set; }
        public Nullable<System.DateTime> FECHA_DE_ELABORACION { get; set; }
        public Nullable<int> NUMERO_DOCUMENTO_ORIGINAL { get; set; }
        public string SIGLA_GERENCIA_ADM { get; set; }
        public Nullable<decimal> AÑO_DE_PRESUPUESTO { get; set; }
        public Nullable<int> FORMULARIO_ANTERIOR { get; set; }
        public string EFECTO_CONTABLE { get; set; }
        public string CLASE_DE_GASTO { get; set; }
        public string FUENTE_DE_FINANCIAMIENTO { get; set; }
        public string ORGANISMO_FINANCIADOR { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESTATUS_DEL_FORMULARIO { get; set; }
        public Nullable<decimal> DEDUCCIONES { get; set; }
        public Nullable<System.DateTime> HORA_ADICION { get; set; }
        public Nullable<System.DateTime> FECHA_ADICION { get; set; }
        public string USUARIO_ADICION { get; set; }
        public Nullable<System.DateTime> HORA_ULTIMO_CAMBIO { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_CAMBIO { get; set; }
        public string USUARIO_ULTIMO_CAMBIO { get; set; }
    
        public virtual INFORMACION_CENTRAL INFORMACION_CENTRAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PG_TRN_PRESUPUESTO_AFEC_CONTABLE> PG_TRN_PRESUPUESTO_AFEC_CONTABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PG_TRN_PRESUPUESTO_BENEFICIARIOS> PG_TRN_PRESUPUESTO_BENEFICIARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PG_TRN_PRESUPUESTO_CONTROL_PAGOS> PG_TRN_PRESUPUESTO_CONTROL_PAGOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PG_TRN_PRESUPUESTO_INICIAL> PG_TRN_PRESUPUESTO_INICIAL { get; set; }
        public virtual PG_TRN_PRESUPUESTO_ORDEN_CONTROL PG_TRN_PRESUPUESTO_ORDEN_CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PG_TRN_PRESUPUESTO_RETEN_DEDUC> PG_TRN_PRESUPUESTO_RETEN_DEDUC { get; set; }
    }
}
