//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PG_TRN_PRESUPUESTO_BENEFICIARIOS
    {
        public string DEFINICION_DEL_PROCESO { get; set; }
        public int NUMERO_DE_PARTIDA { get; set; }
        public string CODIGO_BIC { get; set; }
        public string TIPO_DOCUMENTO_BENEFICIAR { get; set; }
        public string NUMERO_DOCUMENTO_BENEFICI { get; set; }
        public Nullable<decimal> MONTO { get; set; }
    
        public virtual BASE_INFO_CENTRAL BASE_INFO_CENTRAL { get; set; }
        public virtual PG_TRN_PRESUPUESTO_CONTROL PG_TRN_PRESUPUESTO_CONTROL { get; set; }
    }
}
