//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANILLA_HISTORICA
    {
        public string CODIGO_BIC { get; set; }
        public string CODIGO_CLASE_DE_PLANILLA { get; set; }
        public string CODIGO_TIPO_DE_PLANILLA { get; set; }
        public int ANO_PLANILLA { get; set; }
        public int PERIODO_PLANILLA { get; set; }
        public string CODIGO_DEF_TRN_PLANILLA { get; set; }
        public System.DateTime FECHA_GRABADO { get; set; }
        public Nullable<decimal> VALOR_CALCULO { get; set; }
        public Nullable<decimal> DIAS_CALCULO { get; set; }
        public Nullable<decimal> HORAS_CALCULO { get; set; }
        public Nullable<decimal> UNIDADES_CALCULO { get; set; }
        public string DESCRIPCION_DE_TRANSACCIO { get; set; }
        public string CODIGO_DE_CUENTA { get; set; }
    
        public virtual DEF_TRN_PLA_CTL DEF_TRN_PLA_CTL { get; set; }
        public virtual EMPLEADO_TABLA EMPLEADO_TABLA { get; set; }
        public virtual PERIODO_DE_PLANILLA PERIODO_DE_PLANILLA { get; set; }
    }
}
