//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANILLA_MENSUAL_CTL_HOSPITAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLANILLA_MENSUAL_CTL_HOSPITAL()
        {
            this.PLANILLA_MENSUAL_DET_HOSPITAL = new HashSet<PLANILLA_MENSUAL_DET_HOSPITAL>();
            this.PLANILLA_MENSUAL_PDA_HOSPITAL = new HashSet<PLANILLA_MENSUAL_PDA_HOSPITAL>();
        }
    
        public int ANO_DEL_PERIODO { get; set; }
        public int NUMERO_DEL_PERIODO { get; set; }
        public string DESCRIPCION_DE_LA_TRANSAC { get; set; }
        public string ESTADO_DE_LA_PLANILLA { get; set; }
    
        public virtual PERIODO_CONTABLE PERIODO_CONTABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANILLA_MENSUAL_DET_HOSPITAL> PLANILLA_MENSUAL_DET_HOSPITAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANILLA_MENSUAL_PDA_HOSPITAL> PLANILLA_MENSUAL_PDA_HOSPITAL { get; set; }
    }
}
