//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESENTACION_TABLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRESENTACION_TABLA()
        {
            this.ARTICULO_BODEGA_PRES = new HashSet<ARTICULO_BODEGA_PRES>();
            this.COMPRA_DETALLE = new HashSet<COMPRA_DETALLE>();
            this.ENSAMBLE_DE_ARTICULO = new HashSet<ENSAMBLE_DE_ARTICULO>();
            this.FACTURA_DIARIA_DETALLE = new HashSet<FACTURA_DIARIA_DETALLE>();
            this.LISTA_DE_PRECIO_DETALLE = new HashSet<LISTA_DE_PRECIO_DETALLE>();
            this.REQUISICION_DETALLE = new HashSet<REQUISICION_DETALLE>();
            this.SERVICIOS_HOSPITAL_COMPONENTEART = new HashSet<SERVICIOS_HOSPITAL_COMPONENTEART>();
            this.TRANSFERENCIA_INVENTA3E4T = new HashSet<TRANSFERENCIA_INVENTA3E4T>();
            this.TRN_INVENTARIO_HIST_DET = new HashSet<TRN_INVENTARIO_HIST_DET>();
        }
    
        public string CODIGO_DE_ARTICULO { get; set; }
        public string CODIGO_DE_EMPAQUE { get; set; }
        public string CODIGO_UNIDAD_DE_MEDIDA { get; set; }
        public Nullable<decimal> CONTENIDO_DE_PRESENTACION { get; set; }
        public string DESCRIPCION_DE_PRESENTACI { get; set; }
        public string ABREVIATURA_DE_PRESENTACI { get; set; }
        public Nullable<decimal> PESO_POR_UNIDAD_EN_LIBRAS { get; set; }
        public Nullable<decimal> PESO_POR_UNIDAD_EN_KILOS { get; set; }
        public Nullable<decimal> VOLUMEN_EN_PIES_CUBICOS { get; set; }
        public Nullable<decimal> VOLUMEN_EN_METROS_CUBICOS { get; set; }
        public Nullable<decimal> ALTO_EN_METROS { get; set; }
        public Nullable<decimal> ANCHO_EN_METROS { get; set; }
        public Nullable<decimal> FONDO_EN_METROS { get; set; }
        public Nullable<decimal> ALTO_EN_PULGADAS { get; set; }
        public Nullable<decimal> ANCHO_EN_PULGADAS { get; set; }
        public Nullable<decimal> FONDO_EN_PULGADAS { get; set; }
        public string ES_LA_UNIDAD_ESTANDARD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO_BODEGA_PRES> ARTICULO_BODEGA_PRES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA_DETALLE> COMPRA_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENSAMBLE_DE_ARTICULO> ENSAMBLE_DE_ARTICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_DIARIA_DETALLE> FACTURA_DIARIA_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTA_DE_PRECIO_DETALLE> LISTA_DE_PRECIO_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUISICION_DETALLE> REQUISICION_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIOS_HOSPITAL_COMPONENTEART> SERVICIOS_HOSPITAL_COMPONENTEART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSFERENCIA_INVENTA3E4T> TRANSFERENCIA_INVENTA3E4T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_INVENTARIO_HIST_DET> TRN_INVENTARIO_HIST_DET { get; set; }
    }
}
