//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFESION_TABLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROFESION_TABLA()
        {
            this.EMPLEADO_PROFESION = new HashSet<EMPLEADO_PROFESION>();
        }
    
        public string PROFESION { get; set; }
        public string NOMBRE_DE_PROFESION { get; set; }
        public string ABREVIATURA_DE_PROFESION { get; set; }
        public string NIVEL_DE_EDUCACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_PROFESION> EMPLEADO_PROFESION { get; set; }
        public virtual NIVEL_DE_EDUCACION_TABLA NIVEL_DE_EDUCACION_TABLA { get; set; }
    }
}
