//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRAMA_DE_VACACIONES
    {
        public string CODIGO_BIC { get; set; }
        public int ANO_DE_CICLO_DE_VACACIONE { get; set; }
        public int NUMERO_DE_CICLO_DE_VACACI { get; set; }
        public System.DateTime FECHA_INICIO_PROGRAMA { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_PROGRAMA { get; set; }
        public Nullable<decimal> DIAS_PROGRAMADOS { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO_VACACIONES { get; set; }
        public string ESTATUS_DEL_PROGRAMA_VACA { get; set; }
    
        public virtual SALDOS_DE_VACACIONES SALDOS_DE_VACACIONES { get; set; }
    }
}
