//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR_AGRUPACION
    {
        public string CODIGO_BIC { get; set; }
        public string AGRUPACION_PROVEEDOR_CONT { get; set; }
        public string AGRUPACION_PROVEEDOR_DETA { get; set; }
    
        public virtual AGRUPACION_PROVEEDOR_CTL AGRUPACION_PROVEEDOR_CTL { get; set; }
        public virtual AGRUPACION_PROVEEDOR_DET AGRUPACION_PROVEEDOR_DET { get; set; }
        public virtual PROVEEDOR_TABLA PROVEEDOR_TABLA { get; set; }
    }
}
