//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUESTO_PHYSICAL_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUESTO_PHYSICAL_TABLE()
        {
            this.PLAZA_PHYSICAL_TABLE = new HashSet<PLAZA_PHYSICAL_TABLE>();
        }
    
        public string CODIGO_DE_PUESTO { get; set; }
        public string NOMBRE_DEL_PUESTO { get; set; }
        public string DESCRIPCION_DEL_PUESTO { get; set; }
        public string OBJETIVOS_DEL_PUESTO { get; set; }
        public string FUNCIONES_DEL_PUESTO { get; set; }
        public Nullable<int> NIVEL_DE_JERARQUIA { get; set; }
        public string CODIGO_BIC { get; set; }
    
        public virtual NIVEL_JERARQUIA NIVEL_JERARQUIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLAZA_PHYSICAL_TABLE> PLAZA_PHYSICAL_TABLE { get; set; }
    }
}
