//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUNTO_DE_VENTA_USUARIO
    {
        public string CODIGO_BIC { get; set; }
        public string OS4sA { get; set; }
        public string RELACION_CON_PUNTO_DE_VEN { get; set; }
    
        public virtual OS12T OS12T { get; set; }
        public virtual PUNTO_DE_VENTA PUNTO_DE_VENTA { get; set; }
    }
}
