//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUNTO_DE_VENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUNTO_DE_VENTA()
        {
            this.FACTURA_DIARIA_CONTROL = new HashSet<FACTURA_DIARIA_CONTROL>();
            this.ORDEN_DE_TRABAJO_CONTROL = new HashSet<ORDEN_DE_TRABAJO_CONTROL>();
            this.PUNTO_DE_VENTA_USUARIO = new HashSet<PUNTO_DE_VENTA_USUARIO>();
        }
    
        public string CODIGO_BIC { get; set; }
        public string DESCRIPCION_PUNTO_VENTA { get; set; }
        public string ABREVIATURA_PUNTO_VENTA { get; set; }
        public string ESTATUS_PUNTO_DE_VENTA { get; set; }
        public string NUMERACION_FACTURA_CREDITO { get; set; }
        public string NUMERACION_DE_RECIBOS { get; set; }
        public string NUMERACION_FACTURAS_CONTADO { get; set; }
        public string NUMERACION_LISTA_EMBARQUE { get; set; }
        public string NUMERACION_DE_DEBITOS { get; set; }
        public string NUMERACION_DE_CREDITOS { get; set; }
        public string ORDEN_DE_TRABAJO_PREFIJO { get; set; }
        public Nullable<int> CODIGO_DE_AGENCIA { get; set; }
        public string CODIGO_DE_BODEGA { get; set; }
        public Nullable<decimal> VALOR_DE_USUARIO { get; set; }
        public string TEXTO_DE_USUARIO { get; set; }
        public string DISEÑO_DE_FACTURA { get; set; }
        public string DISEÑO_DE_RECIBO { get; set; }
        public string CODIGO_LISTA_PRECIOS { get; set; }
        public string CLIENTE_DE_CONTADO_CODIGO { get; set; }
        public string CODIGO_FORMAS_PAGO { get; set; }
    
        public virtual AGENCIA AGENCIA { get; set; }
        public virtual BASE_INFO_CENTRAL BASE_INFO_CENTRAL { get; set; }
        public virtual BODEGA_TABLA BODEGA_TABLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_DIARIA_CONTROL> FACTURA_DIARIA_CONTROL { get; set; }
        public virtual FORMAS_DE_PAGO FORMAS_DE_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_DE_TRABAJO_CONTROL> ORDEN_DE_TRABAJO_CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUNTO_DE_VENTA_USUARIO> PUNTO_DE_VENTA_USUARIO { get; set; }
    }
}
