//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETAS_SIN_DESPACHAR
    {
        public int NUMERO_DE_RECETA { get; set; }
        public decimal NUMERO_LINEA { get; set; }
        public Nullable<System.DateTime> FECHA_DE_RECETA { get; set; }
        public Nullable<decimal> CANTIDAD_SOLICITADA { get; set; }
        public Nullable<decimal> COSTO_UNIDADES_ENTREGADAS { get; set; }
        public Nullable<int> EXPEDIENTE { get; set; }
        public Nullable<System.DateTime> FECHA_DEL_IN_PROMPTU { get; set; }
        public Nullable<decimal> NUMERO_DEL_IN_PROMPTU { get; set; }
        public string CODIGO_CENTRO_DE_COSTO { get; set; }
        public string CODIGO_DE_DEPARTAMENTO { get; set; }
        public string CODIGO_DE_ARTICULO { get; set; }
        public string CODIGO_BIC { get; set; }
        public string CODIGO_DE_BODEGA { get; set; }
    
        public virtual ARTICULO_TABLA ARTICULO_TABLA { get; set; }
        public virtual BODEGA_TABLA BODEGA_TABLA { get; set; }
        public virtual CENTRO_DE_COSTO CENTRO_DE_COSTO { get; set; }
        public virtual DEPARTAMENTO_TABLA DEPARTAMENTO_TABLA { get; set; }
        public virtual DOCTOR DOCTOR { get; set; }
    }
}
