//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETA_MASIVA_MEDICAM6HXT
    {
        public System.DateTime LH6hoA { get; set; }
        public string CODIGO_CENTRO_DE_COSTO { get; set; }
        public string CODIGO_DE_DEPARTAMENTO { get; set; }
        public string CODIGO_DE_BODEGA { get; set; }
        public string CODIGO_DE_ARTICULO { get; set; }
        public Nullable<decimal> CANTIDAD_SOLICITADA { get; set; }
        public Nullable<decimal> CANTIDAD_ENTREGADA { get; set; }
    
        public virtual ARTICULO_TABLA ARTICULO_TABLA { get; set; }
        public virtual RECETA_MASIVA_MEDICAMENTT RECETA_MASIVA_MEDICAMENTT { get; set; }
    }
}
