//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class recicontro
    {
        public decimal NUMERO_RECIBO_HOSPITALARI { get; set; }
        public Nullable<System.DateTime> FECHA_DEL_RECIBO { get; set; }
        public string TIPO_PACIENTE { get; set; }
        public Nullable<int> EXPEDIENTE { get; set; }
        public Nullable<System.DateTime> FECHA_DEL_IN_PROMPTU { get; set; }
        public Nullable<decimal> NUMERO_DEL_IN_PROMPTU { get; set; }
        public Nullable<int> ANO_DEL_PERIODO { get; set; }
        public Nullable<int> NUMERO_DE_FACTURA { get; set; }
        public string NOMBRES_DEL_PACIENTE { get; set; }
        public string APELLIDO_1_DEL_PACIENTE { get; set; }
        public string APELLIDO_2_DEL_PACIENTE { get; set; }
        public string DIRECCION { get; set; }
        public string ESTADO_DEL_RECIBO { get; set; }
        public string ESTA_IMPRESO_EL_RECIBO { get; set; }
    }
}
