//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFERENCIAS_EMPLEADO
    {
        public string CODIGO_BIC { get; set; }
        public int CORRELATIVO_REFERENCIA { get; set; }
        public string PERSONA_REFERENCIA { get; set; }
        public string TELEFONO_REFERENCIA { get; set; }
        public string DATOS_REFERENCIA { get; set; }
        public string VALOR_REFERENCIA { get; set; }
    
        public virtual EMPLEADO_TABLA EMPLEADO_TABLA { get; set; }
    }
}
