//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELACIONES_FAMILIARES_PHT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RELACIONES_FAMILIARES_PHT()
        {
            this.DEPENDIENTES_EMPLEADO = new HashSet<DEPENDIENTES_EMPLEADO>();
        }
    
        public string CODIGO_RELACION_FAMILIAR { get; set; }
        public string NOMBRE_RELACION_FAMILIAR { get; set; }
        public string ABREVIATURA_RELACION_FAMI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPENDIENTES_EMPLEADO> DEPENDIENTES_EMPLEADO { get; set; }
    }
}
