//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELACION_LABORAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RELACION_LABORAL()
        {
            this.EMPLEADO_TABLA = new HashSet<EMPLEADO_TABLA>();
        }
    
        public string CODIGO_RELACION_LABORAL { get; set; }
        public string DESCRIPCION_RELACION_LABO { get; set; }
        public string ABREVIATURA_RELACION_LABO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_TABLA> EMPLEADO_TABLA { get; set; }
    }
}
