//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUISICION_CONTROL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REQUISICION_CONTROL()
        {
            this.REQUISICION_DETALLE = new HashSet<REQUISICION_DETALLE>();
        }
    
        public string DEFINICION_DEL_PROCESO { get; set; }
        public int NUMERO_DE_REQUISICION { get; set; }
        public Nullable<System.DateTime> FECHA_DE_REQUISICION { get; set; }
        public Nullable<System.DateTime> FECHA_DE_APROBACION_REQUI { get; set; }
        public Nullable<System.DateTime> FECHA_DE_DESPACHO_REQUISI { get; set; }
        public string CODIGO_CENTRO_DE_COSTO { get; set; }
        public string CODIGO_DE_DEPARTAMENTO { get; set; }
        public string CODIGO_DE_BODEGA { get; set; }
        public string SOLICITADO_POR_CODIGO_BIC { get; set; }
        public string APROBADO_POR_CODIGO_BIC { get; set; }
        public string DESPACHADO_POR_CODIGO_BIC { get; set; }
        public string ESTATUS_DE_LA_REQUISICION { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<decimal> AÑO_DE_PRESUPUESTO { get; set; }
        public Nullable<int> PERIODO_DEL_PRESUPUESTO { get; set; }
        public string TIPO_DE_REQUISICION { get; set; }
        public string REQ_DESPACHADA_COMO { get; set; }
        public Nullable<int> NUMERO_DE_TRANSFERENCIA { get; set; }
    
        public virtual BODEGA_TABLA BODEGA_TABLA { get; set; }
        public virtual CENTRO_DE_COSTO CENTRO_DE_COSTO { get; set; }
        public virtual DEPARTAMENTO_TABLA DEPARTAMENTO_TABLA { get; set; }
        public virtual EMPLEADO_TABLA EMPLEADO_TABLA { get; set; }
        public virtual INFORMACION_CENTRAL INFORMACION_CENTRAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUISICION_DETALLE> REQUISICION_DETALLE { get; set; }
    }
}
