//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUISICION_DETALLE
    {
        public string DEFINICION_DEL_PROCESO { get; set; }
        public int NUMERO_DE_REQUISICION { get; set; }
        public string CODIGO_DE_ARTICULO { get; set; }
        public string CODIGO_DE_EMPAQUE { get; set; }
        public string CODIGO_UNIDAD_DE_MEDIDA { get; set; }
        public string CODIGO_CENTRO_DE_COSTO { get; set; }
        public string CODIGO_DE_DEPARTAMENTO { get; set; }
        public string CODIGO_BIC { get; set; }
        public string CODIGO_DE_BODEGA { get; set; }
        public Nullable<int> ANO_DE_INVENTARIO { get; set; }
        public string CODIGO_LOTE_SERIE { get; set; }
        public Nullable<int> LOTE { get; set; }
        public Nullable<decimal> CANTIDAD_PEDIDA { get; set; }
        public Nullable<decimal> CANTIDAD_ENTREGADA { get; set; }
        public string NOTAS { get; set; }
        public Nullable<System.DateTime> FECHA_DE_DESPACHO_REQUISI { get; set; }
        public string CODIGO_TIPO_DE_GASTO { get; set; }
    
        public virtual ARTICULO_BODEGA_PRES ARTICULO_BODEGA_PRES { get; set; }
        public virtual ARTICULO_TABLA ARTICULO_TABLA { get; set; }
        public virtual BODEGA_TABLA BODEGA_TABLA { get; set; }
        public virtual CENTRO_DE_COSTO CENTRO_DE_COSTO { get; set; }
        public virtual DEPARTAMENTO_TABLA DEPARTAMENTO_TABLA { get; set; }
        public virtual EMPLEADO_TABLA EMPLEADO_TABLA { get; set; }
        public virtual PRESENTACION_TABLA PRESENTACION_TABLA { get; set; }
        public virtual REQUISICION_CONTROL REQUISICION_CONTROL { get; set; }
    }
}
