//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUISICION_IMPORTADO_DETALLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REQUISICION_IMPORTADO_DETALLE()
        {
            this.REQUISICION_IMPORTADO_LOTES = new HashSet<REQUISICION_IMPORTADO_LOTES>();
        }
    
        public string DEFINICION_DEL_PROCESO { get; set; }
        public int NUMERO_DE_REQUISICION { get; set; }
        public string CODIGO_DE_ARTICULO { get; set; }
        public string NOMBRE_DEL_ARTICULO { get; set; }
        public string DESCRIPCION_DEL_ARTICULO { get; set; }
        public string NOMBRE_CORTO_DEL_ARTICULO { get; set; }
        public string TIPO_DE_ARTICULO { get; set; }
        public string ESTATUS_DEL_ARTICULO { get; set; }
        public string CODIGO_DE_EMPAQUE { get; set; }
        public string DESCRIPCION_EMPAQUE { get; set; }
        public string CODIGO_UNIDAD_DE_MEDIDA { get; set; }
        public string DESCRIPCION_UNIDAD_DE_MED { get; set; }
        public Nullable<decimal> CANTIDAD_ENTREGADA { get; set; }
        public Nullable<decimal> VALOR_TOTAL_RECIBIDO { get; set; }
    
        public virtual REQUISICION_IMPORTADO_CONTROL REQUISICION_IMPORTADO_CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUISICION_IMPORTADO_LOTES> REQUISICION_IMPORTADO_LOTES { get; set; }
    }
}
