//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUISICION_IMPORTADO_LOTES
    {
        public string DEFINICION_DEL_PROCESO { get; set; }
        public int NUMERO_DE_REQUISICION { get; set; }
        public string CODIGO_DE_ARTICULO { get; set; }
        public int CORRELATIVO { get; set; }
        public string CODIGO_LOTE_SERIE { get; set; }
        public Nullable<int> LOTE { get; set; }
        public Nullable<decimal> Cantidad_Lote_Usado { get; set; }
        public Nullable<decimal> Costo_Lote_Usado { get; set; }
        public Nullable<System.DateTime> FECHA_VENCE_LOTE { get; set; }
    
        public virtual REQUISICION_IMPORTADO_DETALLE REQUISICION_IMPORTADO_DETALLE { get; set; }
    }
}
