//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESOLUCION_DEI_RESOLUCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESOLUCION_DEI_RESOLUCION()
        {
            this.RESOLUCION_DEI_ITEMS = new HashSet<RESOLUCION_DEI_ITEMS>();
        }
    
        public string NUMERO_DE_RESOLUCION_DEI { get; set; }
        public Nullable<System.DateTime> LH7f4A { get; set; }
        public Nullable<System.DateTime> LH7f5A { get; set; }
        public Nullable<int> ANO_DEL_PERIODO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESOLUCION_DEI_ITEMS> RESOLUCION_DEI_ITEMS { get; set; }
    }
}
