//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESOLUCION_DEI_ARTICULOS
    {
        public string NUMERO_DE_RESOLUCION_DEI { get; set; }
        public int LINEA { get; set; }
        public string CODIGO_DE_ARTICULO { get; set; }
        public string DESCRIPCION_DEL_ARTICULO { get; set; }
        public Nullable<decimal> ly92oA { get; set; }
        public string CODIGO_UNIDAD_DE_MEDIDA { get; set; }
    
        public virtual UNIDAD_MEDIDA_TBL UNIDAD_MEDIDA_TBL { get; set; }
        public virtual RESOLUCION_DEI_ITEMS RESOLUCION_DEI_ITEMS { get; set; }
    }
}
