//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETENCIONES_DEDUCCIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RETENCIONES_DEDUCCIONES()
        {
            this.PG_TRN_PRESUPUESTO_RETEN_DEDUC = new HashSet<PG_TRN_PRESUPUESTO_RETEN_DEDUC>();
        }
    
        public string RETENCION_O_DEDUCCION { get; set; }
        public string DESCRIPCION_RETENCION_DED { get; set; }
        public string ABREVIATURA_RETENCION_DED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PG_TRN_PRESUPUESTO_RETEN_DEDUC> PG_TRN_PRESUPUESTO_RETEN_DEDUC { get; set; }
    }
}
