//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALDOS_DE_PROVEEDOR_PHYST
    {
        public string CODIGO_BIC { get; set; }
        public int PROVEEDOR_ANO_SALDO_CLIEN { get; set; }
        public Nullable<decimal> PROVEEDOR_SALDO_INICIA4L6 { get; set; }
        public Nullable<decimal> PROVEEDOR_SALDO_INIC_CLIE { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_FINANCIERO { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_FINANCI3SX { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_FINANCI3SZ { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_FINANCI3T1 { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_FINANCI3T3 { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_FINANCI3T5 { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_FINANCI3T7 { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_FINANCI3T9 { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_FINANCI3TB { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_FINANCI3TD { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_FINANCI3TF { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_FINANCI3TH { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_FINANCIER { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_FINANC3UU { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_FINANC3UW { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_FINANC3UY { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_FINANC3V0 { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_FINANC3V2 { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_FINANC3V4 { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_FINANC3V6 { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_FINANC3V8 { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_FINANC3VA { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_FINANC3VC { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_FINANC3VE { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_REEXPRESIO { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_REEXPRE3TK { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_REEXPRE3TM { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_REEXPRE3TO { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_REEXPRE3TQ { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_REEXPRE3TS { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_REEXPRE3TU { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_REEXPRE3TW { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_REEXPRE3TY { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_REEXPRE3U0 { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_REEXPRE3U2 { get; set; }
        public Nullable<decimal> DEBITO_CLIENTE_REEXPRE3U4 { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_REEXPRESI { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_REEXPR3VH { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_REEXPR3VJ { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_REEXPR3VL { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_REEXPR3VN { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_REEXPR3VP { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_REEXPR3VR { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_REEXPR3VT { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_REEXPR3VV { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_REEXPR3VX { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_REEXPR3VZ { get; set; }
        public Nullable<decimal> CREDITO_CLIENTE_REEXPR3W1 { get; set; }
    
        public virtual PROVEEDOR_TABLA PROVEEDOR_TABLA { get; set; }
    }
}
