//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALDOS_CONTABLES_CONSOLIDADO
    {
        public string CODIGO_DE_COMPANIA { get; set; }
        public string CODIGO_DE_CUENTA { get; set; }
        public int ANO_CONTABLE { get; set; }
        public Nullable<decimal> SALDO_INICIO_ANO_FINANCIE { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_FINAN_01 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_FINAN_02 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_FINAN_03 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_FINAN_04 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_FINAN_05 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_FINAN_06 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_FINAN_07 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_FINAN_08 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_FINAN_09 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_FINAN_10 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_FINAN_11 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_FINAN_12 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_FINAN_13 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_FINA_01 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_FINA_02 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_FINA_03 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_FINA_04 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_FINA_05 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_FINA_06 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_FINA_07 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_FINA_08 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_FINA_09 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_FINA_10 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_FINA_11 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_FINA_12 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_FINA_13 { get; set; }
        public Nullable<decimal> SALDO_INICIO_ANO_REEXPRES { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_REEXP_01 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_REEXP_02 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_REEXP_03 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_REEXP_04 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_REEXP_05 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_REEXP_06 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_REEXP_07 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_REEXP_08 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_REEXP_09 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_REEXP_10 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_REEXP_11 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_REEXP_12 { get; set; }
        public Nullable<decimal> DEBITOS_CONTABLE_REEXP_13 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_REEX_01 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_REEX_02 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_REEX_03 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_REEX_04 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_REEX_05 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_REEX_06 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_REEX_07 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_REEX_08 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_REEX_09 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_REEX_10 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_REEX_11 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_REEX_12 { get; set; }
        public Nullable<decimal> CREDITOS_CONTABLE_REEX_13 { get; set; }
    
        public virtual CATALOGO_CONTABLE_CONSOLIDADO CATALOGO_CONTABLE_CONSOLIDADO { get; set; }
    }
}
