//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOS_HOSPITAL_COMPONENTECTO
    {
        public string SERVICIO_HOSPITALARIO { get; set; }
        public string LH6zaA { get; set; }
        public int ANO_DEL_PERIODO { get; set; }
        public int NUMERO_DEL_PERIODO { get; set; }
        public Nullable<decimal> COSTO_DEL_PROTOCOLO { get; set; }
    
        public virtual PERIODO_CONTABLE PERIODO_CONTABLE { get; set; }
        public virtual SERVICIO_HOSPITAL_COMPONENTE SERVICIO_HOSPITAL_COMPONENTE { get; set; }
    }
}
