//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOS_HOSPITAL_COMPONENTEART
    {
        public string SERVICIO_HOSPITALARIO { get; set; }
        public string LH6zaA { get; set; }
        public string CODIGO_DE_ARTICULO { get; set; }
        public string CODIGO_DE_EMPAQUE { get; set; }
        public string CODIGO_UNIDAD_DE_MEDIDA { get; set; }
        public Nullable<decimal> UNIDADES_DEBITO_INV { get; set; }
    
        public virtual PRESENTACION_TABLA PRESENTACION_TABLA { get; set; }
        public virtual SERVICIO_HOSPITAL_COMPONENTE SERVICIO_HOSPITAL_COMPONENTE { get; set; }
    }
}
