//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO_HOSPITAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIO_HOSPITAL()
        {
            this.RECIBO_SERVICIOS_HOSPITAL_DET = new HashSet<RECIBO_SERVICIOS_HOSPITAL_DET>();
            this.SERVICIO_HOSPITAL_COMPONENTE = new HashSet<SERVICIO_HOSPITAL_COMPONENTE>();
            this.SERVICIOS_HOSPITAL_CUOTA = new HashSet<SERVICIOS_HOSPITAL_CUOTA>();
            this.GRUPOS_SERVICIOS_HOSPITALARIOS = new HashSet<GRUPOS_SERVICIOS_HOSPITALARIOS>();
        }
    
        public string SERVICIO_HOSPITALARIO { get; set; }
        public string NOMBRE_SERVICIO_HOSPITAL { get; set; }
        public string CODIGO_DE_DEPARTAMENTO { get; set; }
        public Nullable<decimal> LH6ykA { get; set; }
        public Nullable<decimal> TIEMPO_DEL_SERVICIO { get; set; }
        public Nullable<decimal> PESO_DEL_SERVICIO { get; set; }
        public Nullable<System.DateTime> HORA_ADICION { get; set; }
        public Nullable<System.DateTime> FECHA_ADICION { get; set; }
        public string USUARIO_ADICION { get; set; }
        public Nullable<System.DateTime> HORA_ULTIMO_CAMBIO { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_CAMBIO { get; set; }
        public string USUARIO_ULTIMO_CAMBIO { get; set; }
    
        public virtual DEPARTAMENTO_TABLA DEPARTAMENTO_TABLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECIBO_SERVICIOS_HOSPITAL_DET> RECIBO_SERVICIOS_HOSPITAL_DET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIO_HOSPITAL_COMPONENTE> SERVICIO_HOSPITAL_COMPONENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIOS_HOSPITAL_CUOTA> SERVICIOS_HOSPITAL_CUOTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRUPOS_SERVICIOS_HOSPITALARIOS> GRUPOS_SERVICIOS_HOSPITALARIOS { get; set; }
    }
}
