//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_PAGO_CTL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOLICITUD_PAGO_CTL()
        {
            this.SOLICITUD_PAGO_DET = new HashSet<SOLICITUD_PAGO_DET>();
        }
    
        public int NUMERO_SOLICITUD_PAGO { get; set; }
        public string CODIGO_BIC { get; set; }
        public Nullable<decimal> VALOR_SOLICITUD_PAGO { get; set; }
        public string FORMA_DE_PAGO { get; set; }
        public string DESCRIPCION_SOLICITUD_PAG { get; set; }
        public string DOCUMENTO_SOLICITUD_PAGO { get; set; }
        public Nullable<System.DateTime> FECHA_APROX_SOLICITUD_PAG { get; set; }
        public Nullable<decimal> TOTAL_DEBITOS_SOLICITUD_P { get; set; }
        public Nullable<decimal> TOTAL_CREDITOS_SOLICITUD { get; set; }
        public string ESTATUS_SOLICITUD_PAGO { get; set; }
        public string SOLICITUD_PAGO_EN_ERROR { get; set; }
        public string BANCO_TRANSFERENCIA { get; set; }
        public string TIPO_CUENTA_TRANSFERENCIA { get; set; }
        public string CUENTA_TRANSFERENCIA { get; set; }
        public string SOLICITADO_POR_PAGO { get; set; }
        public Nullable<System.DateTime> FECHA_SOLICITUD_PAGO { get; set; }
        public Nullable<System.DateTime> HORA_SOLICITADO_POR_PAGO { get; set; }
        public string REVISADO_POR_PAGO { get; set; }
        public Nullable<System.DateTime> FECHA_REVISADO_POR_PAGO { get; set; }
        public Nullable<System.DateTime> HORA_REVISADO_POR_PAGO { get; set; }
        public string APROBADO_POR_PAGO { get; set; }
        public Nullable<System.DateTime> HORA_APROBADO_POR_PAGO { get; set; }
        public Nullable<System.DateTime> FECHA_APROBADO_POR_PAGO { get; set; }
        public string CUENTA_BANCARIA_CODIGO_BI { get; set; }
        public string CUENTA_BANCARIA_CUENTA_BA { get; set; }
        public Nullable<int> ANO_DEL_PERIODO { get; set; }
        public Nullable<int> NUMERO_DEL_PERIODO { get; set; }
        public string DEFINICION_DEL_PROCESO { get; set; }
        public string CODIGO_DE_MONEDA { get; set; }
        public string PREFIJO_PARTIDA_CONTABLE { get; set; }
        public Nullable<int> NUMERO_DE_PARTIDA { get; set; }
    
        public virtual BASE_INFO_CENTRAL BASE_INFO_CENTRAL { get; set; }
        public virtual MONEDA_TABLA MONEDA_TABLA { get; set; }
        public virtual PERIODO_CONTABLE PERIODO_CONTABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD_PAGO_DET> SOLICITUD_PAGO_DET { get; set; }
    }
}
