//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSACCTA
    {
        public string CCCTA { get; set; }
        public string CCNOMBRE { get; set; }
        public Nullable<double> CCNIVEL { get; set; }
        public string CCTIPO { get; set; }
        public string CCSTIPO { get; set; }
        public string CCPERMIT { get; set; }
        public string CCUSER { get; set; }
        public Nullable<System.DateTime> CCFECHA { get; set; }
        public bool CCPRES { get; set; }
        public string CCSINON { get; set; }
    }
}
