//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBDEPARTAMENTO
    {
        public string CODIGO_DE_DEPARTAMENTO { get; set; }
        public string SUBDEPARTAMENTO1 { get; set; }
        public string Nombre_del_SubDepartamento { get; set; }
    
        public virtual DEPARTAMENTO_TABLA DEPARTAMENTO_TABLA { get; set; }
    }
}
