//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSUBTIPO_ACTIVO
    {
        public string TIPO_DE_ACTIVO_FIJO { get; set; }
        public string SUBTIPO_DE_ACTIVO_FIJO { get; set; }
        public string SUBSUBTIPO_DE_ACTIVO_FIJO { get; set; }
        public string LY5v0A { get; set; }
        public string CUENTA_DE_ACTIVOS_CODIGO { get; set; }
        public string CUENTA_DE_RESERVA_CODIGO { get; set; }
        public string CUENTA_DE_GASTOS_CODIGO_D { get; set; }
        public string DEFINICION_DEL_PROCESO { get; set; }
    
        public virtual TIPO_ACTIVO_FIJO TIPO_ACTIVO_FIJO { get; set; }
        public virtual SUBTIPO_ACT_FIJO SUBTIPO_ACT_FIJO { get; set; }
    }
}
