//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSUBTIPO_DE_INVENTARIT
    {
        public string CODIGO_TIPO_INVENTARIO { get; set; }
        public string SUBTIPO_DE_INVENTARIO { get; set; }
        public string SUBSUBTIPO_DE_INVENTARIO { get; set; }
        public string NOMBRE_SUBSUBTIPO_INVENTA { get; set; }
    
        public virtual SUBTIPO_DE_INVENTARIO_PHT SUBTIPO_DE_INVENTARIO_PHT { get; set; }
    }
}
