//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBTIPO_DE_CUENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBTIPO_DE_CUENTA()
        {
            this.CATALOGO_CONTABLE_CONSOLIDADO = new HashSet<CATALOGO_CONTABLE_CONSOLIDADO>();
            this.CATALOGO_DE_CUENTAS = new HashSet<CATALOGO_DE_CUENTAS>();
        }
    
        public string CODIGO_TIPO_DE_CUENTA { get; set; }
        public string CODIGO_SUBTIPO_DE_CUENTA { get; set; }
        public string NOMBRE_SUBTIPO_DE_CUENTA { get; set; }
        public string ABREVIATURA_SUBTIPO_DE_CU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATALOGO_CONTABLE_CONSOLIDADO> CATALOGO_CONTABLE_CONSOLIDADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATALOGO_DE_CUENTAS> CATALOGO_DE_CUENTAS { get; set; }
        public virtual TIPO_DE_CUENTA TIPO_DE_CUENTA { get; set; }
    }
}
