//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBTIPO_ACT_FIJO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBTIPO_ACT_FIJO()
        {
            this.SUBSUBTIPO_ACTIVO = new HashSet<SUBSUBTIPO_ACTIVO>();
        }
    
        public string TIPO_DE_ACTIVO_FIJO { get; set; }
        public string SUBTIPO_DE_ACTIVO_FIJO { get; set; }
        public string NOMBRE_SUBTIPO_ACT_FIJO { get; set; }
        public string CUENTA_DE_ACTIVO_CODIGO_D { get; set; }
        public string CUENTA_DE_RESERVA_CODIGO { get; set; }
        public string CUENTA_DE_GASTOS_CODIGO_D { get; set; }
        public string DEFINICION_DEL_PROCESO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBSUBTIPO_ACTIVO> SUBSUBTIPO_ACTIVO { get; set; }
        public virtual TIPO_ACTIVO_FIJO TIPO_ACTIVO_FIJO { get; set; }
    }
}
