//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREAS_HOSPITALARIAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAREAS_HOSPITALARIAS()
        {
            this.SERVICIO_HOSPITAL_COMPONENTE = new HashSet<SERVICIO_HOSPITAL_COMPONENTE>();
        }
    
        public string LH6zaA { get; set; }
        public string LH6zbA { get; set; }
        public string LH6zcA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIO_HOSPITAL_COMPONENTE> SERVICIO_HOSPITAL_COMPONENTE { get; set; }
    }
}
