//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARJETAS_DE_CREDITO
    {
        public string TARJETA_DE_CREDITO { get; set; }
        public string NOMBRE_EMISOR_TARJETA_CRE { get; set; }
        public Nullable<decimal> COMISION_POR_COBRO { get; set; }
        public Nullable<decimal> RECARGO_POR_USO { get; set; }
        public string CODIGO_BIC { get; set; }
    
        public virtual BANCO_TABLA BANCO_TABLA { get; set; }
    }
}
