//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASA_DE_MORA_PHYSICAL_TAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TASA_DE_MORA_PHYSICAL_TAT()
        {
            this.ANTIGUEDAD_SALDOS_CXC = new HashSet<ANTIGUEDAD_SALDOS_CXC>();
        }
    
        public string TASA_DE_MORA { get; set; }
        public string NOMBRE_TASA_DE_MORA { get; set; }
        public string ABREVIATURA_TASA_DE_MORA { get; set; }
        public string TIPO_TASA_DE_MORA { get; set; }
        public Nullable<decimal> VALOR_TASA_DE_MORA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANTIGUEDAD_SALDOS_CXC> ANTIGUEDAD_SALDOS_CXC { get; set; }
    }
}
