//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASAS_DE_CAMBIO
    {
        public string CODIGO_DE_MONEDA { get; set; }
        public string MONEDA_DE_CONVERSION_CODI { get; set; }
        public System.DateTime FECHA_DE_VIGENCIA_TASA_CA { get; set; }
        public string OPERADOR_CALCULO { get; set; }
        public Nullable<decimal> VALOR_TASA_DE_CAMBIO { get; set; }
    
        public virtual MONEDA_TABLA MONEDA_TABLA { get; set; }
        public virtual MONEDA_TABLA MONEDA_TABLA1 { get; set; }
    }
}
