//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_CLIENTE()
        {
            this.CLIENTE_TABLA = new HashSet<CLIENTE_TABLA>();
        }
    
        public string CODIGO_TIPO_DE_CLIENTE { get; set; }
        public string DESCRIPCION_TIPO_DE_CLIEN { get; set; }
        public string ABREVIATURA_TIPO_DE_CLIEN { get; set; }
        public string CODIGO_DE_CUENTA { get; set; }
    
        public virtual CATALOGO_DE_CUENTAS CATALOGO_DE_CUENTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_TABLA> CLIENTE_TABLA { get; set; }
    }
}
