//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_DE_PLANILLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_DE_PLANILLA()
        {
            this.EMPLEADO_TRN_FIJAS_PHYSIT = new HashSet<EMPLEADO_TRN_FIJAS_PHYSIT>();
            this.PERIODO_DE_PLANILLA = new HashSet<PERIODO_DE_PLANILLA>();
            this.TRANSAC_PLA_CTL = new HashSet<TRANSAC_PLA_CTL>();
        }
    
        public string CODIGO_CLASE_DE_PLANILLA { get; set; }
        public string CODIGO_TIPO_DE_PLANILLA { get; set; }
        public string DESCRIPCION_TIPO_DE_PLANI { get; set; }
        public string ABREVIATURA_TIPO_DE_PLANI { get; set; }
        public string NOMBRE_VARIABLE_TIPO_P01 { get; set; }
        public string NOMBRE_VARIABLE_TIPO_P02 { get; set; }
        public string NOMBRE_VARIABLE_TIPO_P03 { get; set; }
        public string NOMBRE_VARIABLE_TIPO_P04 { get; set; }
        public string NOMBRE_VARIABLE_TIPO_P05 { get; set; }
        public Nullable<decimal> VALOR_VARIABLE_TIPO_PL01 { get; set; }
        public Nullable<decimal> VALOR_VARIABLE_TIPO_PL02 { get; set; }
        public Nullable<decimal> VALOR_VARIABLE_TIPO_PL03 { get; set; }
        public Nullable<decimal> VALOR_VARIABLE_TIPO_PL04 { get; set; }
        public Nullable<decimal> VALOR_VARIABLE_TIPO_PL05 { get; set; }
    
        public virtual CLASE_DE_PLANILLA CLASE_DE_PLANILLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_TRN_FIJAS_PHYSIT> EMPLEADO_TRN_FIJAS_PHYSIT { get; set; }
        public virtual FICHA_DE_GRABACION_NOMINT FICHA_DE_GRABACION_NOMINT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERIODO_DE_PLANILLA> PERIODO_DE_PLANILLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSAC_PLA_CTL> TRANSAC_PLA_CTL { get; set; }
    }
}
