//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_INVENTARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_INVENTARIO()
        {
            this.ARTICULO_TABLA = new HashSet<ARTICULO_TABLA>();
            this.SUBTIPO_DE_INVENTARIO_PHT = new HashSet<SUBTIPO_DE_INVENTARIO_PHT>();
            this.TIPO_INVENTARIO_CUENTA = new HashSet<TIPO_INVENTARIO_CUENTA>();
        }
    
        public string CODIGO_TIPO_INVENTARIO { get; set; }
        public string DESCRIPCION_TIPO_INVENTAR { get; set; }
        public string ABREVIATURA_TIPO_INVENTAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO_TABLA> ARTICULO_TABLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBTIPO_DE_INVENTARIO_PHT> SUBTIPO_DE_INVENTARIO_PHT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_INVENTARIO_CUENTA> TIPO_INVENTARIO_CUENTA { get; set; }
    }
}
