//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_PROVEEDOR()
        {
            this.PROVEEDOR_TABLA = new HashSet<PROVEEDOR_TABLA>();
        }
    
        public string TIPO_DE_PROVEEDOR { get; set; }
        public string DESCRIPCION_TIPO_DE_PROVE { get; set; }
        public string ABREVIATURA_TIPO_DE_PROVE { get; set; }
        public string CODIGO_DE_CUENTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROVEEDOR_TABLA> PROVEEDOR_TABLA { get; set; }
    }
}
