//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_DE_GASTO
    {
        public string CODIGO_TIPO_DE_GASTO { get; set; }
        public string DESCRIPCION_TIPO_DE_GASTO { get; set; }
        public string ABREVIATURA_TIPO_DE_GASTO { get; set; }
    }
}
