//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRABAJO_NOMINA
    {
        public string CODIGO_CLASE_DE_PLANILLA { get; set; }
        public string CODIGO_TIPO_DE_PLANILLA { get; set; }
        public int ANO_PLANILLA { get; set; }
        public int PERIODO_PLANILLA { get; set; }
        public string CODIGO_BIC { get; set; }
        public int LINEA { get; set; }
        public string CODIGO_DE_DEPARTAMENTO { get; set; }
        public string DEVENGADO_CODIGO_DEF_TRN { get; set; }
        public Nullable<decimal> DEVENGADO_UNIDADES_CALCUL { get; set; }
        public Nullable<decimal> DEVENGADO_VALOR_CALCULO { get; set; }
        public string DEDUCCION_CODIGO_DEF_TRN { get; set; }
        public Nullable<decimal> DEDUCCION_UNIDADES_CALCUL { get; set; }
        public Nullable<decimal> DEDUCCION_VALOR_CALCULO { get; set; }
        public Nullable<System.DateTime> DEVENGADO_FECHA_GRABADO { get; set; }
        public Nullable<System.DateTime> DEDUCCION_FECHA_GRABADO { get; set; }
    
        public virtual DEPARTAMENTO_TABLA DEPARTAMENTO_TABLA { get; set; }
        public virtual EMPLEADO_TABLA EMPLEADO_TABLA { get; set; }
        public virtual PERIODO_DE_PLANILLA PERIODO_DE_PLANILLA { get; set; }
    }
}
