//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSAC_PLA_DET
    {
        public string CODIGO_CLASE_DE_PLANILLA { get; set; }
        public string CODIGO_TIPO_DE_PLANILLA { get; set; }
        public int ANO_PLANILLA { get; set; }
        public int PERIODO_PLANILLA { get; set; }
        public string CODIGO_DEF_TRN_PLANILLA { get; set; }
        public string CODIGO_BIC { get; set; }
        public Nullable<int> SECUENCIA_CALC_DEF_TRN_PL { get; set; }
        public Nullable<decimal> VALOR_GRABADO { get; set; }
        public Nullable<decimal> DIAS_GRABADO { get; set; }
        public Nullable<decimal> HORAS_GRABADO { get; set; }
        public Nullable<decimal> UNIDADES_GRABADO { get; set; }
        public System.DateTime FECHA_GRABADO { get; set; }
        public string DESCRIPCION_DE_TRANSACCIO { get; set; }
        public Nullable<decimal> VALOR_CALCULO { get; set; }
        public Nullable<decimal> DIAS_CALCULO { get; set; }
        public Nullable<decimal> HORAS_CALCULO { get; set; }
        public Nullable<decimal> UNIDADES_CALCULO { get; set; }
        public Nullable<System.DateTime> FECHA_CALCULO { get; set; }
        public string ESTADO_DE_TRANSACCION { get; set; }
        public string ESTATUS_INGRESO_TRN_PLANI { get; set; }
        public string CODIGO_DE_CUENTA { get; set; }
    
        public virtual EMPLEADO_TABLA EMPLEADO_TABLA { get; set; }
        public virtual TRANSAC_PLA_CTL TRANSAC_PLA_CTL { get; set; }
    }
}
