//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCIONES_ICP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSACCIONES_ICP()
        {
            this.TRN_INVENTARIO_HIST_DET = new HashSet<TRN_INVENTARIO_HIST_DET>();
        }
    
        public string DEFINICION_DEL_PROCESO { get; set; }
        public int CORRELATIVO_ICP { get; set; }
        public string BIC_1_CODIGO_BIC { get; set; }
        public string BIC_2_CODIGO_BIC { get; set; }
        public string BIC_3_CODIGO_BIC { get; set; }
        public Nullable<System.DateTime> FECHA_TRANSACCION_ICP_1 { get; set; }
        public Nullable<System.DateTime> FECHA_TRANSACCION_ICP_2 { get; set; }
        public Nullable<System.DateTime> FECHA_TRANSACCION_ICP_3 { get; set; }
        public Nullable<decimal> VALOR_TRANSACCION_ICP_1 { get; set; }
        public Nullable<decimal> VALOR_TRANSACCION_ICP_2 { get; set; }
        public Nullable<decimal> VALOR_TRANSACCION_ICP_3 { get; set; }
        public string DOCUMENTO_TRANSACCION_ICP { get; set; }
        public string DOCUMENTO_TRANSACCION_2FQ { get; set; }
        public string DOCUMENTO_TRANSACCION_2FS { get; set; }
        public string DESCRIPCION_TRANSACCION_I { get; set; }
        public string ESTATUS_DE_TRANSACCION_IC { get; set; }
        public string CODIGO_CENTRO_DE_COSTO { get; set; }
        public string CODIGO_TIPO_DE_GASTO { get; set; }
        public Nullable<System.DateTime> OBF002 { get; set; }
        public Nullable<System.DateTime> OBF003 { get; set; }
        public Nullable<System.DateTime> OBF005 { get; set; }
        public Nullable<System.DateTime> OBF006 { get; set; }
        public string USUARIO_CREACION { get; set; }
        public string USUARIO_ULTIMA_MODIFICACI { get; set; }
    
        public virtual INFORMACION_CENTRAL INFORMACION_CENTRAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_INVENTARIO_HIST_DET> TRN_INVENTARIO_HIST_DET { get; set; }
        public virtual TRN_INVENTARIO_X_AGENCIT TRN_INVENTARIO_X_AGENCIT { get; set; }
    }
}
