//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCIONES_MENSAJERIT
    {
        public string TIPO_DOCUMENTO { get; set; }
        public string CODIGO_RUTA_MENSAJERIA { get; set; }
        public string USUARIO_DE_WINDOWS { get; set; }
    
        public virtual RUTAS_MENSAJERIA_CONTROT RUTAS_MENSAJERIA_CONTROT { get; set; }
    }
}
