//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_CONTABLE_DIARIO_INV
    {
        public string PREFIJO_PARTIDA_CONTABLE { get; set; }
        public int NUMERO_DE_PARTIDA { get; set; }
        public int NUMERO_TRN_DIARIO_DETALLE { get; set; }
        public string DESCRIPCION_PARTIDA_DETAL { get; set; }
        public string DOCUMENTO_PARTIDA_DETALLE { get; set; }
        public Nullable<System.DateTime> FECHA_DE_PARTIDA_DETALLE { get; set; }
        public Nullable<decimal> VALOR_TRANSACCION_ORIGEN { get; set; }
        public Nullable<decimal> VALOR_TRANSACCION_ORIG2JT { get; set; }
        public string CODIGO_DE_CUENTA { get; set; }
        public Nullable<int> ANO_DEL_PERIODO { get; set; }
        public Nullable<int> NUMERO_DEL_PERIODO { get; set; }
        public string CODIGO_TIPO_DE_GASTO { get; set; }
        public string CODIGO_CENTRO_DE_COSTO { get; set; }
        public string CODIGO_DE_MONEDA { get; set; }
        public string LY3qeA { get; set; }
        public string CLIENTE_CODIGO_BIC { get; set; }
        public Nullable<decimal> UNIDADES { get; set; }
        public Nullable<decimal> VALOR_TASA_DE_CAMBIO { get; set; }
        public string SUBCATALOGO_1 { get; set; }
        public string SUBCATALOGO_2 { get; set; }
        public string SUBCATALOGO_3 { get; set; }
    }
}
