//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_CLIENTE_HIST_DETALLT
    {
        public string PREFIJO_PARTIDA_CONTABLE { get; set; }
        public int NUMERO_DE_PARTIDA { get; set; }
        public int NUMERO_CLIENTE_DIARIO_DET { get; set; }
        public string CUENTAS_X_COBRAR_DEFINICI { get; set; }
        public Nullable<int> CUENTAS_X_COBRAR_CORRELAT { get; set; }
        public string CUENTAS_X_COBRAR_CODIGO_F { get; set; }
        public Nullable<decimal> MONEDA_ORIGEN_VALOR_TRANS { get; set; }
        public Nullable<decimal> MONEDA_ORIGEN_VALOR_TR4QZ { get; set; }
        public Nullable<decimal> MONEDA_FINANCIERA_VALOR_T { get; set; }
        public Nullable<decimal> MONEDA_FINANCIERA_VALO4R2 { get; set; }
        public Nullable<decimal> MONEDA_REEXPRESION_VALOR { get; set; }
        public Nullable<decimal> MONEDA_REEXPRESION_VAL4R5 { get; set; }
        public Nullable<System.DateTime> FECHA_DEL_DOCUMENTO_ORIGI { get; set; }
        public Nullable<System.DateTime> FECHA_DETALLADA_DEL_CLIEN { get; set; }
        public string DOCUMENTO_TRANSACCION_ICP { get; set; }
        public string DOCUMENTO_TRANSACCION_2FQ { get; set; }
        public string DOCUMENTO_TRANSACCION_2FS { get; set; }
        public string DESCRIPCION_DE_LA_TRANSAC { get; set; }
        public string BANCO_CLIENTE_DIARIO { get; set; }
        public string CUENTA_CLIENTE_DIARIO { get; set; }
        public string NUMERO_CHEQUE_CLIENTE_DIA { get; set; }
        public string TARJETA_CREDITO_CLIENTE_D { get; set; }
        public Nullable<System.DateTime> FECHA_VENCE_TARJETA_CREDI { get; set; }
        public string CLIENTE_CODIGO_BIC { get; set; }
        public string CAJERO_CODIGO_BIC { get; set; }
        public string COBRADOR_CODIGO_BIC { get; set; }
        public string MONEDA_ORIGEN_CODIGO_DE_M { get; set; }
        public Nullable<decimal> VALOR_TASA_DE_CAMBIO { get; set; }
        public Nullable<int> ANO_DEL_PERIODO { get; set; }
        public Nullable<int> NUMERO_DEL_PERIODO { get; set; }
    
        public virtual CLIENTE_TABLA CLIENTE_TABLA { get; set; }
        public virtual MONEDA_TABLA MONEDA_TABLA { get; set; }
        public virtual PERIODO_CONTABLE PERIODO_CONTABLE { get; set; }
        public virtual TRN_CONTABLE_HISTORICO_TT TRN_CONTABLE_HISTORICO_TT { get; set; }
    }
}
