//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_CONTABLE_HISTORIC3N9T
    {
        public string PREFIJO_PARTIDA_CONTABLE { get; set; }
        public int NUMERO_DE_PARTIDA { get; set; }
        public int NUMERO_TRN_DIARIO_DETALLE { get; set; }
        public string DESCRIPCION_PARTIDA_DETAL { get; set; }
        public string DOCUMENTO_PARTIDA_DETALLE { get; set; }
        public Nullable<System.DateTime> FECHA_DE_PARTIDA_DETALLE { get; set; }
        public Nullable<decimal> VALOR_TRANSACCION_ORIGEN { get; set; }
        public Nullable<decimal> VALOR_TRANSACCION_ORIG2JT { get; set; }
        public Nullable<decimal> FINANCIERA_VALOR_TRANSACC { get; set; }
        public Nullable<decimal> FINANCIERA_VALOR_TRANS3Q3 { get; set; }
        public Nullable<decimal> REEXPRESION_VALOR_TRANSAC { get; set; }
        public Nullable<decimal> REEXPRESION_VALOR_TRAN3Q6 { get; set; }
        public string CODIGO_DE_CUENTA { get; set; }
        public Nullable<int> ANO_DEL_PERIODO { get; set; }
        public Nullable<int> NUMERO_DEL_PERIODO { get; set; }
        public string CODIGO_TIPO_DE_GASTO { get; set; }
        public string CODIGO_CENTRO_DE_COSTO { get; set; }
        public string CODIGO_DE_MONEDA { get; set; }
        public string LY3qeA { get; set; }
        public string CLIENTE_CODIGO_BIC { get; set; }
        public string CUENTA_DE_BANCO_CODIGO_BI { get; set; }
        public string CUENTA_DE_BANCO_CUENTA_BA { get; set; }
        public Nullable<decimal> UNIDADES { get; set; }
        public Nullable<decimal> VALOR_TASA_DE_CAMBIO { get; set; }
        public string SUBCATALOGO_1 { get; set; }
        public string SUBCATALOGO_2 { get; set; }
        public string SUBCATALOGO_3 { get; set; }
        public Nullable<System.DateTime> HORA_ADICION { get; set; }
        public Nullable<System.DateTime> FECHA_ADICION { get; set; }
        public string USUARIO_ADICION { get; set; }
        public Nullable<System.DateTime> HORA_ULTIMO_CAMBIO { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_CAMBIO { get; set; }
        public string USUARIO_ULTIMO_CAMBIO { get; set; }
    
        public virtual CATALOGO_DE_CUENTAS CATALOGO_DE_CUENTAS { get; set; }
        public virtual MONEDA_TABLA MONEDA_TABLA { get; set; }
        public virtual PERIODO_CONTABLE PERIODO_CONTABLE { get; set; }
        public virtual TRN_CONTABLE_HISTORICO_TT TRN_CONTABLE_HISTORICO_TT { get; set; }
    }
}
