//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_CONTABLE_DIARIO_TEMPT
    {
        public string PREFIJO_PARTIDA_CONTABLE { get; set; }
        public int NUMERO_DE_PARTIDA { get; set; }
        public string DESCRIPCION_DE_PARTIDA { get; set; }
        public Nullable<System.DateTime> FECHA_DE_PARTIDA { get; set; }
        public Nullable<decimal> CONTROL_DEBITOS_PARTIDA { get; set; }
        public Nullable<decimal> CONTROL_CREDITOS_PARTIDA { get; set; }
        public Nullable<decimal> CIFRA_DE_CONTROL { get; set; }
        public string ORIGEN_DE_PARTIDA { get; set; }
        public string ESTATUS_DE_TRANSACCION_IC { get; set; }
        public Nullable<int> ANO_DEL_PERIODO { get; set; }
        public Nullable<int> NUMERO_DEL_PERIODO { get; set; }
        public string CODIGO_DE_MONEDA { get; set; }
        public string PROCESO_ICP_DEFINICION_DE { get; set; }
        public Nullable<int> TRANSACCIONES_ICP_CORRELA { get; set; }
    }
}
