//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_INVENTARIO_HIST_DET
    {
        public string DEFINICION_DEL_PROCESO { get; set; }
        public int CORRELATIVO_ICP { get; set; }
        public int CORRELATIVO_INVENTARIO_HI { get; set; }
        public Nullable<int> ANO_DEL_PERIODO { get; set; }
        public Nullable<int> NUMERO_DEL_PERIODO { get; set; }
        public string CODIGO_DE_ARTICULO { get; set; }
        public string CODIGO_DE_EMPAQUE { get; set; }
        public string CODIGO_UNIDAD_DE_MEDIDA { get; set; }
        public string CODIGO_DE_BODEGA { get; set; }
        public Nullable<int> ANO_DE_INVENTARIO { get; set; }
        public string CODIGO_DE_DEPARTAMENTO { get; set; }
        public string CODIGO_CENTRO_DE_COSTO { get; set; }
        public string CODIGO_TIPO_DE_GASTO { get; set; }
        public Nullable<System.DateTime> FECHA_TRN_INV { get; set; }
        public string CODIGO_DE_MONEDA { get; set; }
        public Nullable<decimal> VALOR_DEBITO_MONEDA_ORIGE { get; set; }
        public Nullable<decimal> VALOR_CREDITO_MONEDA_ORIG { get; set; }
        public Nullable<decimal> VALOR_DEBITO_MONEDA_FINAN { get; set; }
        public Nullable<decimal> VALOR_CREDITO_MONEDA_FINA { get; set; }
        public Nullable<decimal> VALOR_DEBITO_MONEDA_REEXP { get; set; }
        public Nullable<decimal> VALOR_CREDITO_MONEDA_REEX { get; set; }
        public Nullable<decimal> UNIDADES_DEBITO_INV { get; set; }
        public Nullable<decimal> UNIDADES_CREDITO_INV { get; set; }
        public string ESTATUS_TRN_INV { get; set; }
        public string CODIGO_LOTE_SERIE { get; set; }
        public Nullable<int> LOTE { get; set; }
    
        public virtual ARTICULO_TABLA ARTICULO_TABLA { get; set; }
        public virtual BODEGA_TABLA BODEGA_TABLA { get; set; }
        public virtual MONEDA_TABLA MONEDA_TABLA { get; set; }
        public virtual PERIODO_CONTABLE PERIODO_CONTABLE { get; set; }
        public virtual PRESENTACION_TABLA PRESENTACION_TABLA { get; set; }
        public virtual SALDO_DE_ARTICULO SALDO_DE_ARTICULO { get; set; }
        public virtual TRANSACCIONES_ICP TRANSACCIONES_ICP { get; set; }
        public virtual TRN_INVENTARIO_HIST_VENCT TRN_INVENTARIO_HIST_VENCT { get; set; }
    }
}
