//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_CONVERSION_HIST_DETAT
    {
        public string DEFINICION_DEL_PROCESO { get; set; }
        public int CORRELATIVO_ICP { get; set; }
        public int CORRELATIVO_INVENTARIO_HI { get; set; }
        public string CODIGO_DE_ARTICULO { get; set; }
        public string CODIGO_DE_EMPAQUE { get; set; }
        public string CODIGO_UNIDAD_DE_MEDIDA { get; set; }
        public Nullable<int> ANO_DE_INVENTARIO { get; set; }
        public string CODIGO_DE_BODEGA { get; set; }
        public string CODIGO_LOTE_SERIE { get; set; }
        public Nullable<int> LOTE { get; set; }
        public Nullable<decimal> VALOR_DEBITO_MONEDA_ORIGE { get; set; }
        public Nullable<decimal> VALOR_DEBITO_MONEDA_FINAN { get; set; }
        public Nullable<decimal> VALOR_DEBITO_MONEDA_REEXP { get; set; }
        public Nullable<decimal> UNIDADES_DEBITO_INV { get; set; }
    }
}
