//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_CONTABLE_DIARIO_AF_NUM
    {
        public string OBF007 { get; set; }
        public Nullable<int> LAST_ANO_DEL_PERIODO { get; set; }
        public Nullable<int> LAST_NUMERO_DEL_PERIODO { get; set; }
        public string LAST_PREFIJO_PARTIDA_CONT { get; set; }
        public Nullable<int> LAST_NUMERO_TRN_DIARIO_DE { get; set; }
    }
}
