//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_PRESUPUESTO_PRIVADA_CTL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRN_PRESUPUESTO_PRIVADA_CTL()
        {
            this.TRN_PRESUPUESTO_PRIVADA_DET = new HashSet<TRN_PRESUPUESTO_PRIVADA_DET>();
        }
    
        public string PREFIJO_PARTIDA_CONTABLE { get; set; }
        public int NUMERO_DE_PARTIDA { get; set; }
        public string CODIGO_DE_MONEDA { get; set; }
        public Nullable<System.DateTime> FECHA_DE_PRESUPUESTO { get; set; }
        public Nullable<decimal> AÑO_DE_PRESUPUESTO { get; set; }
        public string ESTATUS_TRANSACCION_PRESU { get; set; }
        public string COMENTARIOS { get; set; }
        public Nullable<System.DateTime> HORA_ADICION { get; set; }
        public Nullable<System.DateTime> FECHA_ADICION { get; set; }
        public string USUARIO_ADICION { get; set; }
        public Nullable<System.DateTime> HORA_ULTIMO_CAMBIO { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_CAMBIO { get; set; }
        public string USUARIO_ULTIMO_CAMBIO { get; set; }
    
        public virtual MONEDA_TABLA MONEDA_TABLA { get; set; }
        public virtual NUMERACION_PARTIDAS NUMERACION_PARTIDAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_PRESUPUESTO_PRIVADA_DET> TRN_PRESUPUESTO_PRIVADA_DET { get; set; }
    }
}
