//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_PRESUPUESTO_GOBIERNT
    {
        public string DEFINICION_DEL_PROCESO { get; set; }
        public int NUMERO_DE_PARTIDA { get; set; }
        public string CUENTA_ORIGEN_INSTITUCION { get; set; }
        public string CUENTA_ORIGEN_DESCENTRALI { get; set; }
        public string CUENTA_ORIGEN_UNIDAD_EJEC { get; set; }
        public string CUENTA_ORIGEN_SUBUNIDAD_E { get; set; }
        public string CUENTA_ORIGEN_PROGRAMA { get; set; }
        public string CUENTA_ORIGEN_SUBPROGRAMA { get; set; }
        public string CUENTA_ORIGEN_PROYECTO { get; set; }
        public string CUENTA_ORIGEN_ACTIVIDAD { get; set; }
        public string CUENTA_ORIGEN_OBJETO_DEL { get; set; }
        public string CUENTA_ORIGEN_FUENTE_DE_F { get; set; }
        public string CUENTA_ORIGEN_ORGANISMO_F { get; set; }
        public string CUENTA_ORIGEN_CODIGO_DE_B { get; set; }
        public string CUENTA_DESTINO_INSTITUCIO { get; set; }
        public string CUENTA_DESTINO_DESCENTRAL { get; set; }
        public string CUENTA_DESTINO_UNIDAD_EJE { get; set; }
        public string CUENTA_DESTINO_SUBUNIDAD { get; set; }
        public string CUENTA_DESTINO_PROGRAMA { get; set; }
        public string CUENTA_DESTINO_SUBPROGRAM { get; set; }
        public string CUENTA_DESTINO_PROYECTO { get; set; }
        public string CUENTA_DESTINO_ACTIVIDAD { get; set; }
        public string CUENTA_DESTINO_OBJETO_DEL { get; set; }
        public string CUENTA_DESTINO_FUENTE_DE { get; set; }
        public string CUENTA_DESTINO_ORGANISMO { get; set; }
        public string CUENTA_DESTINO_CODIGO_DE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> MONTO { get; set; }
    }
}
