//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_HIST_BANCO_DET
    {
        public string PREFIJO_PARTIDA_CONTABLE { get; set; }
        public int NUMERO_DE_PARTIDA { get; set; }
        public string CODIGO_BIC { get; set; }
        public string CUENTA_BANCARIA { get; set; }
        public string DOCUMENTO_PARTIDA_DETALLE { get; set; }
        public Nullable<System.DateTime> FECHA_DE_TRANSACCION { get; set; }
        public Nullable<int> DIAS_CONGELAMIENTO_DEPOSI { get; set; }
        public string ly8vzA { get; set; }
        public Nullable<decimal> VALOR_DBT_ORIGEN { get; set; }
        public string MONEDA_ORIGEN_CODIGO_DE_M { get; set; }
        public Nullable<decimal> VALOR_CRD_ORIGEN { get; set; }
        public string DESCRIPCION_TRANSACCION_B { get; set; }
        public Nullable<decimal> VALOR_DBT_FINANCIERO { get; set; }
        public Nullable<decimal> VALOR_CRD_FINANCIERO { get; set; }
        public Nullable<decimal> VALOR_DBT_REEXPRESION { get; set; }
        public Nullable<decimal> VALOR_CRD_REEXPRESION { get; set; }
        public Nullable<int> ANO_DEL_PERIODO { get; set; }
        public Nullable<int> NUMERO_DEL_PERIODO { get; set; }
    }
}
