//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURNOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TURNOS()
        {
            this.EMPLEADO_TURNOS = new HashSet<EMPLEADO_TURNOS>();
            this.TURNO_EXCEPCIONES_TABLA = new HashSet<TURNO_EXCEPCIONES_TABLA>();
        }
    
        public string CODIGO_DE_HORARIO { get; set; }
        public int CODIGO_TURNO { get; set; }
        public string DESCRIPCION_DEL_TURNO { get; set; }
        public Nullable<int> DIAS_DE_LA_SEMANA { get; set; }
        public Nullable<short> HORAS_BASE_PAGO_DIARIO { get; set; }
        public Nullable<short> HORAS_BASE_PAGO_SEMANAL { get; set; }
        public Nullable<short> MINUTOS_DE_TOLERANCIA { get; set; }
        public Nullable<short> HORAS_TOTALES_LUNES { get; set; }
        public Nullable<short> HORA_ENTRADA_LUNES_HORA { get; set; }
        public Nullable<short> HORA_ENTRADA_LUNES_MINUTO { get; set; }
        public Nullable<short> HORA_SALIDA_INTERMEDIA_LU { get; set; }
        public Nullable<short> HORA_SALIDA_INTERMEDIA25Z { get; set; }
        public Nullable<short> HORA_ENTRADA_INTERMEDIA_L { get; set; }
        public Nullable<short> HORA_ENTRADA_INTERMEDI252 { get; set; }
        public Nullable<short> HORA_SALIDA_LUNES_HORA { get; set; }
        public Nullable<short> HORA_SALIDA_LUNES_MINUTO { get; set; }
        public Nullable<short> HORAS_TOTALES_MARTES { get; set; }
        public Nullable<short> HORA_ENTRADA_MARTES_HORA { get; set; }
        public Nullable<short> HORA_ENTRADA_MARTES_MINUT { get; set; }
        public Nullable<short> HORA_SALIDA_INTERMEDIA_MA { get; set; }
        public Nullable<short> HORA_SALIDA_INTERMEDIA264 { get; set; }
        public Nullable<short> HORA_ENTRADA_INTERMEDIA_M { get; set; }
        public Nullable<short> HORA_ENTRADA_INTERMEDI257 { get; set; }
        public Nullable<short> HORA_SALIDA_MARTES_HORA { get; set; }
        public Nullable<short> HORA_SALIDA_MARTES_MINUTO { get; set; }
        public Nullable<short> HORAS_TOTALES_MIERCOLES { get; set; }
        public Nullable<short> HORA_ENTRADA_MIERCOLES_HO { get; set; }
        public Nullable<short> HORA_ENTRADA_MIERCOLES_MI { get; set; }
        public Nullable<short> HORA_SALIDA_INTERMEDIA_MI { get; set; }
        public Nullable<short> HORA_SALIDA_INTERMEDIA269 { get; set; }
        public Nullable<short> HORA_ENTRADA_INTERMED_MIE { get; set; }
        public Nullable<short> HORA_ENTRADA_INTERMED_25C { get; set; }
        public Nullable<short> HORA_SALIDA_MIERCOLES_HOR { get; set; }
        public Nullable<short> HORA_SALIDA_MIERCOLES_MIN { get; set; }
        public Nullable<short> HORAS_TOTALES_JUEVES { get; set; }
        public Nullable<short> HORA_ENTRADA_JUEVES_HORA { get; set; }
        public Nullable<short> HORA_ENTRADA_JUEVES_MINUT { get; set; }
        public Nullable<short> HORA_SALIDA_INTERMEDIA_JU { get; set; }
        public Nullable<short> HORA_SALIDA_INTERMEDIA26E { get; set; }
        public Nullable<short> HORA_ENTRADA_INTERMEDIA_J { get; set; }
        public Nullable<short> HORA_ENTRADA_INTERMEDI25H { get; set; }
        public Nullable<short> HORA_SALIDA_JUEVES_HORA { get; set; }
        public Nullable<short> HORA_SALIDA_JUEVES_MINUTO { get; set; }
        public Nullable<short> HORAS_TOTALES_VIERNES { get; set; }
        public Nullable<short> HORA_ENTRADA_VIERNES_HORA { get; set; }
        public Nullable<short> HORA_ENTRADA_VIERNES_MINU { get; set; }
        public Nullable<short> HORA_SALIDA_INTERMEDIA_VI { get; set; }
        public Nullable<short> HORA_SALIDA_INTERMEDIA26J { get; set; }
        public Nullable<short> HORA_ENTRADA_INTERMEDIA_V { get; set; }
        public Nullable<short> HORA_ENTRADA_INTERMEDI25M { get; set; }
        public Nullable<short> HORA_SALIDA_VIERNES_HORA { get; set; }
        public Nullable<short> HORA_SALIDA_VIERNES_MINUT { get; set; }
        public Nullable<short> HORAS_TOTALES_SABADO { get; set; }
        public Nullable<short> HORA_ENTRADA_SABADO_HORA { get; set; }
        public Nullable<short> HORA_ENTRADA_SABADO_MINUT { get; set; }
        public Nullable<short> HORA_SALIDA_INTERMEDIA_SA { get; set; }
        public Nullable<short> HORA_SALIDA_INTERMEDIA26O { get; set; }
        public Nullable<short> HORA_ENTRADA_INTERMEDIA_S { get; set; }
        public Nullable<short> HORA_ENTRADA_INTERMEDI25R { get; set; }
        public Nullable<short> HORA_SALIDA_SABADO_HORA { get; set; }
        public Nullable<short> HORA_SALIDA_SABADO_MINUTO { get; set; }
        public Nullable<short> HORAS_TOTALES_DOMINGO { get; set; }
        public Nullable<short> HORA_ENTRADA_DOMINGO_HORA { get; set; }
        public Nullable<short> HORA_ENTRADA_DOMINGO_MINU { get; set; }
        public Nullable<short> HORA_SALIDA_INTERMEDIA_DO { get; set; }
        public Nullable<short> HORA_SALIDA_INTERMEDIA26T { get; set; }
        public Nullable<short> HORA_ENTRADA_INTERMEDIA_D { get; set; }
        public Nullable<short> HORA_ENTRADA_INTERMEDI25W { get; set; }
        public Nullable<short> HORA_SALIDA_DOMINGO_HORA { get; set; }
        public Nullable<short> HORA_SALIDA_DOMINGO_MINUT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_TURNOS> EMPLEADO_TURNOS { get; set; }
        public virtual HORARIOS HORARIOS { get; set; }
        public virtual TURNO_DATOS_ADICIONALES TURNO_DATOS_ADICIONALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TURNO_EXCEPCIONES_TABLA> TURNO_EXCEPCIONES_TABLA { get; set; }
    }
}
