//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURNO_DATOS_ADICIONALES
    {
        public string CODIGO_DE_HORARIO { get; set; }
        public int CODIGO_TURNO { get; set; }
        public Nullable<decimal> HORAS_25_LUNES { get; set; }
        public Nullable<decimal> HORAS_50_LUNES { get; set; }
        public Nullable<decimal> HORAS_75_LUNES { get; set; }
        public Nullable<decimal> HORAS_100_LUNES { get; set; }
        public Nullable<decimal> HORAS_25_MARTES { get; set; }
        public Nullable<decimal> HORAS_50_MARTES { get; set; }
        public Nullable<decimal> HORAS_75_MARTES { get; set; }
        public Nullable<decimal> HORAS_100_MARTES { get; set; }
        public Nullable<decimal> HORAS_25_MIERCOLES { get; set; }
        public Nullable<decimal> HORAS_50_MIERCOLES { get; set; }
        public Nullable<decimal> HORAS_75_MIERCOLES { get; set; }
        public Nullable<decimal> HORAS_100_MIERCOLES { get; set; }
        public Nullable<decimal> HORAS_25_JUEVES { get; set; }
        public Nullable<decimal> HORAS_50_JUEVES { get; set; }
        public Nullable<decimal> HORAS_75_JUEVES { get; set; }
        public Nullable<decimal> HORAS_100_JUEVES { get; set; }
        public Nullable<decimal> HORAS_25_VIERNES { get; set; }
        public Nullable<decimal> HORAS_50_VIERNES { get; set; }
        public Nullable<decimal> HORAS_75_VIERNES { get; set; }
        public Nullable<decimal> HORAS_100_VIERNES { get; set; }
        public Nullable<decimal> HORAS_25_SABADO { get; set; }
        public Nullable<decimal> HORAS_50_SABADO { get; set; }
        public Nullable<decimal> HORAS_75_SABADO { get; set; }
        public Nullable<decimal> HORAS_100_SABADO { get; set; }
        public Nullable<decimal> HORAS_25_DOMINGO { get; set; }
        public Nullable<decimal> HORAS_50_DOMINGO { get; set; }
        public Nullable<decimal> HORAS_75_DOMINGO { get; set; }
        public Nullable<decimal> HORAS_100_DOMINGO { get; set; }
        public string TRN_ORDINARIO_CODIGO_DEF { get; set; }
        public string TRN_HORAS_25_CODIGO_DEF_T { get; set; }
        public string TRN_HORAS_50_CODIGO_DEF_T { get; set; }
        public string TRN_HORAS_75_CODIGO_DEF_T { get; set; }
        public string TRN_HORAS_100_CODIGO_DEF { get; set; }
        public string TRN_LLEGADA_TARDE_CODIGO { get; set; }
        public string TRN_DIA_FALTADO_CODIGO_DE { get; set; }
        public string SEPTIMO_DIA_CODIGO_DEF_TR { get; set; }
        public Nullable<short> REDONDEO_A_MEDIA_HORA_DES { get; set; }
        public Nullable<short> REDONDEO_A_MEDIA_HORA_HAS { get; set; }
        public Nullable<short> REDONDEO_A_UNA_HORA_DESDE { get; set; }
        public Nullable<short> REDONDEO_A_UNA_HORA_HASTA { get; set; }
        public Nullable<decimal> DIAS_SEPTIMO_DIA_DESDE { get; set; }
        public Nullable<decimal> DIAS_SEPTIMO_DIA_HASTA { get; set; }
        public string TIPO_DE_JORNADA { get; set; }
    
        public virtual TURNOS TURNOS { get; set; }
    }
}
