//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURNO_EXCEPCIONES_TABLA
    {
        public string CODIGO_DE_HORARIO { get; set; }
        public int CODIGO_TURNO { get; set; }
        public System.DateTime ly953A { get; set; }
        public Nullable<short> HORA_ENTRADA_LUNES_HORA { get; set; }
        public Nullable<short> HORA_ENTRADA_LUNES_MINUTO { get; set; }
        public Nullable<short> HORA_SALIDA_INTERMEDIA_LU { get; set; }
        public Nullable<short> HORA_SALIDA_INTERMEDIA25Z { get; set; }
        public Nullable<short> HORA_ENTRADA_INTERMEDIA_L { get; set; }
        public Nullable<short> HORA_ENTRADA_INTERMEDI252 { get; set; }
        public Nullable<short> HORA_SALIDA_LUNES_HORA { get; set; }
        public Nullable<short> HORA_SALIDA_LUNES_MINUTO { get; set; }
        public Nullable<short> HORAS_TOTALES_LUNES { get; set; }
        public Nullable<decimal> HORAS_25_LUNES { get; set; }
        public Nullable<decimal> HORAS_50_LUNES { get; set; }
        public Nullable<decimal> HORAS_75_LUNES { get; set; }
        public Nullable<decimal> HORAS_100_LUNES { get; set; }
        public string COMENTARIOS { get; set; }
    
        public virtual TURNOS TURNOS { get; set; }
    }
}
