//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_PHYSICAL_TABLE
    {
        public string USUARIO { get; set; }
        public string NOMBRE_DEL_USUARIO { get; set; }
        public string PALABRA_CLAVE_DEL_USUARIO { get; set; }
        public string ESTATUS_DEL_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_VENCE_AUTORIZACION { get; set; }
    }
}
