//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Hoja = new HashSet<Hoja>();
        }
    
        public int IdUsuario { get; set; }
        public string Usuario { get; set; }
        public string Contra { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaModificado { get; set; }
        public int IdEstado { get; set; }
        public int IdTipoUsuario { get; set; }
    
        public virtual EstadoUsuario EstadoUsuario { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoja> Hoja { get; set; }
    }
}
