//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALORES_DEL_SISTEMA_POR_DEFAULT
    {
        public string CODIGO_DE_COMPANIA { get; set; }
        public string PREFIJO_CONTABLE_DE_CIERR { get; set; }
        public string CUENTA_PERDIDAS_Y_GANANCI { get; set; }
    
        public virtual COMPANIA COMPANIA { get; set; }
    }
}
