//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO_TABLA
    {
        public string VIN { get; set; }
        public string PLACA { get; set; }
        public string NOMBRE_MARCA { get; set; }
        public string NOMBRE_MODELO { get; set; }
        public Nullable<int> AÑO_DEL_VEHICULO { get; set; }
        public string TIPO_DE_FRENOS { get; set; }
        public string TIPO_DE_BLOCK { get; set; }
        public string TRANSMISION { get; set; }
        public string TRACCION { get; set; }
        public string MOTOR { get; set; }
        public string VIN_MOTOR { get; set; }
        public Nullable<int> VELOCIDADES { get; set; }
        public string CHASIS { get; set; }
        public string COLOR { get; set; }
        public string COMBUSTIBLE { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual MARCA_TABLA MARCA_TABLA { get; set; }
        public virtual MODELO_TABLA MODELO_TABLA { get; set; }
    }
}
