//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEDOR_TABLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENDEDOR_TABLA()
        {
            this.CONTRATO_SERVICIOS_CONTROL = new HashSet<CONTRATO_SERVICIOS_CONTROL>();
            this.FACTURAS_SERVICIOS_CONTROL = new HashSet<FACTURAS_SERVICIOS_CONTROL>();
        }
    
        public string CODIGO_BIC { get; set; }
        public string ESTATUS_DEL_VENDEDOR { get; set; }
        public string NOTAS_SOBRE_VENDEDOR { get; set; }
    
        public virtual BASE_INFO_CENTRAL BASE_INFO_CENTRAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO_SERVICIOS_CONTROL> CONTRATO_SERVICIOS_CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURAS_SERVICIOS_CONTROL> FACTURAS_SERVICIOS_CONTROL { get; set; }
    }
}
