//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class WINPT
    {
        public string WINSTA { get; set; }
        public Nullable<decimal> WINRTE { get; set; }
        public string WINOBK { get; set; }
        public Nullable<decimal> WINOBR { get; set; }
        public string WINBNK { get; set; }
        public Nullable<decimal> WINBRN { get; set; }
        public string WINCCY { get; set; }
        public Nullable<decimal> WINGLN { get; set; }
        public Nullable<decimal> WINACC { get; set; }
        public string WINTCD { get; set; }
        public Nullable<decimal> WINVDM { get; set; }
        public Nullable<decimal> WINVDD { get; set; }
        public Nullable<decimal> WINVDY { get; set; }
        public string WINTDS { get; set; }
        public Nullable<decimal> WINDRA { get; set; }
        public Nullable<decimal> WINCR1 { get; set; }
        public Nullable<decimal> WINUN1 { get; set; }
        public Nullable<decimal> WINCR2 { get; set; }
        public Nullable<decimal> WINUN2 { get; set; }
        public Nullable<decimal> WINCR3 { get; set; }
        public Nullable<decimal> WINUN3 { get; set; }
        public Nullable<decimal> WINCR4 { get; set; }
        public Nullable<decimal> WINUN4 { get; set; }
        public Nullable<decimal> WINMDM { get; set; }
        public Nullable<decimal> WINMDD { get; set; }
        public Nullable<decimal> WINMDY { get; set; }
        public decimal WINKBT { get; set; }
        public decimal WINKSQ { get; set; }
        public Nullable<decimal> WINNID { get; set; }
        public string WINDLF { get; set; }
        public string WINREM { get; set; }
        public Nullable<decimal> WINPYT { get; set; }
        public Nullable<decimal> WINCCN { get; set; }
        public Nullable<decimal> WINFER { get; set; }
        public string WINMEF { get; set; }
        public Nullable<decimal> WINTRN { get; set; }
        public string WINATY { get; set; }
        public string WINAPC { get; set; }
        public Nullable<decimal> WINRTN { get; set; }
        public string WINODF { get; set; }
        public string WINREF { get; set; }
        public Nullable<decimal> WINBDM { get; set; }
        public Nullable<decimal> WINBDD { get; set; }
        public Nullable<decimal> WINBDY { get; set; }
        public Nullable<decimal> WINTTR { get; set; }
        public string WINUID { get; set; }
        public string WINARF { get; set; }
        public string WINBPR { get; set; }
        public string WINMBT { get; set; }
        public string WINFDF { get; set; }
        public Nullable<decimal> WINCUN { get; set; }
        public Nullable<decimal> WINCKN { get; set; }
        public string WINSVF { get; set; }
        public Nullable<decimal> WINBDC { get; set; }
        public Nullable<decimal> WINVDC { get; set; }
        public Nullable<decimal> WINDRR { get; set; }
        public Nullable<decimal> WINTIM { get; set; }
        public string WINFL1 { get; set; }
        public string WINFL2 { get; set; }
        public string WINFL3 { get; set; }
        public string WINFL4 { get; set; }
        public Nullable<decimal> WINEQV { get; set; }
        public Nullable<decimal> WINACR { get; set; }
        public Nullable<decimal> WINCNU { get; set; }
        public Nullable<decimal> WINCST { get; set; }
    }
}
